### ISSUE TITLE
Deck tracking switches up player and opponent

### ISSUE THREAD

**Issue by ArsileLuci** [HearthSim/Hearthstone-Deck-Tracker#3743] opened 2018-08-03 05:02 UTC
### Expected Behavior
Default tracking of my game

### Actual Behavior
HDT counted my cards as oponents and oponents as mine

### Steps to reproduce behavior
It happend twice in a row, while I've been playing as quest warior against BakuPaladin
In the first game after some time moved my cards to oponent(left side)

### Log/Screenshots
![image](https://user-images.githubusercontent.com/42055415/43625020-507a516a-96f3-11e8-829d-3ecdb889401f.png)

P.S. Next game against hunter tracked as expected
![image](https://user-images.githubusercontent.com/42055415/43625201-67639372-96f4-11e8-8f31-d0c0b969df82.png)

**Comment by riQQ** [comment] 2018-08-03 06:35
Please post the HDT log of this session: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues#hdt-log-files

**Comment by ArsileLuci** [comment] 2018-08-03 06:43
[hdt_log_1533278372.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2256288/hdt_log_1533278372.txt)

btw it'happend again while I've been playing on Warlock against Mage

**Comment by ElektroStudios** [comment] 2018-08-09 13:10
This exact problem is also happening to me.

**Comment by riQQ** [comment] 2018-08-09 17:30
Is this only happening if the opponent is playing Baku?

**Comment by riQQ** [comment] 2018-08-09 17:53
Logs reflect your statement:
Hero and opponent are switch up, but the correct deck is selected
```
9:24:14 AM|Info|GameV2.CurrentMode >> TOURNAMENT
9:24:35 AM|Info|GameEventHandler.HandleGameStart >> --- Game start ---
9:24:35 AM|Info|GameV2.Reset >> -------- Reset ---------
9:24:35 AM|Info|GameV2.CacheMatchInfo >> Arsile#2326 vs Hatzogloug#2126
9:24:35 AM|Info|TurnTimer.Start >> Starting turn timer
9:24:35 AM|Warning|TurnTimer.Start >> Waiting for player entity
9:24:36 AM|Info|TagChangeActions.SetHeroAsync >> Found hero with id=64
9:24:36 AM|Info|GameEventHandler.SetOpponentHero >> Opponent=Warlock
9:24:36 AM|Info|TagChangeActions.SetHeroAsync >> Found hero with id=66
9:24:36 AM|Info|GameEventHandler.SetPlayerHero >> Player=Mage
9:24:37 AM|Info|GameV2.CurrentMode >> GAMEPLAY
9:24:39 AM|Info|Player.Draw >> [Opponent] id=31, cardId=, cardName=, zonePos=1,Info={turn=0, originalZone=DECK, hasOutstandingTagChanges=true, hidden=true, OriginalController=1}
9:24:39 AM|Info|Player.Draw >> [Opponent] id=23, cardId=, cardName=, zonePos=2,Info={turn=0, originalZone=DECK, hasOutstandingTagChanges=true, hidden=true, OriginalController=1}
9:24:39 AM|Info|Player.Draw >> [Opponent] id=12, cardId=, cardName=, zonePos=3,Info={turn=0, originalZone=DECK, hasOutstandingTagChanges=true, hidden=true, OriginalController=1}
9:24:54 AM|Info|MainWindow.SelectDeck >> Switched to deck: Dog's Mill (v1.0)
9:24:54 AM|Info|DeckList.ActiveDeck >> Set active deck to: Dog's Mill (Warlock)
9:24:55 AM|Info|GameV2.Reset >> -------- Reset ---------
```

**Comment by ArsileLuci** [comment] 2018-08-09 18:09
No, it happend several times against elemental mage without Baku
Also this bug not so critical, but still it's uncomfortable to play with it because I can't track remaining cards(if I don't remember my deck) and this games don't provide stats and replays

**Comment by azeier** [comment] 2018-08-11 20:35
Here's a test build with a potential fix and improved logging that should help us figure out what's going on: https://github.com/HearthSim/HDT-dev-builds/releases/download/v1.7.5-dev3680/HDT-Installer.exe

This version will overwrite your current HDT installation but keep all stats/settings and will update to the next full release once it's available. 

Please let us know whether you still experience the same issues with this release and include new logs if you do.

**Comment by ElektroStudios** [comment] 2018-08-11 22:01
The problem still happen with the debug version. @riQQ has pointed a hint about this issue could be related Baku, the next log file has logged two matches, the one was all ok, but the second the opponent had Baku and HDT changed our decks...

[hdt_log - Baku changes cards.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2280574/hdt_log.-.Baku.changes.cards.txt)

**Comment by azeier** [comment] 2018-08-11 22:43
We may have figured out what's causing this. Try this build: https://github.com/HearthSim/HDT-dev-builds/releases/download/v1.7.5-dev3681/HDT-Installer.exe

Same procedure: let us know whether you still experience the same issues with this release and include new logs if you do.

**Comment by azeier** [comment] 2018-08-11 23:07
Could you also post your `<Hearthstone-Installation>/Logs/Power.log` file?  Even if the issue is fixed with 3181, this would be good to have to maybe get some insight into the underlying cause.

**Comment by riQQ** [comment] 2018-08-13 22:17
@ElektroStudios have you tested with the latest version yet?

**Comment by riQQ** [comment] 2018-08-28 06:40
Anyone still having this issue or is it fixed? (@ArsileLuci, @ElektroStudios)

**Comment by ElektroStudios** [comment] 2018-08-28 06:41
I don't have it anymore.

**Closed** 2018-08-28 15:25 UTC
Labels: bug, decktracker, help wanted
