### ISSUE TITLE
Weasel tunnler does not track

### ISSUE THREAD

**Issue by s0urc3d3v3l0pm3nt** [HearthSim/Hearthstone-Deck-Tracker#3470] opened 2017-11-01 16:46 UTC
Weasel tunnler does not track when shuffled into your deck!

**Comment by azeier** [comment] 2017-11-01 16:56
Please provide a log https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by s0urc3d3v3l0pm3nt** [comment] 2017-11-03 03:54
When weasel tunneler is mixed into my deck, the tracker does not show its presence.

[hearthstone_2017_11_02_19_48_12.log](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1440053/hearthstone_2017_11_02_19_48_12.log)

**Comment by s0urc3d3v3l0pm3nt** [comment] 2017-11-03 03:55
[hearthstone_2017_11_02_21_46_55.log](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1440054/hearthstone_2017_11_02_21_46_55.log)

**Comment by riQQ** [comment] 2017-11-03 07:23
You posted a Hearthstone log, but we need a HDT log. They are saved in `%appdata%\HearthstoneDeckTracker\Logs`.

**Comment by maxinfet** [comment] 2018-01-14 20:17
With the interest in Weasel Priest being a thing I am also running into this issue. Here is part of my log for when the tunneler is killed by a Carnivorous Cube but it is not limited to this minion killing it.

```
4:35:33 PM|Info|Player.Play >> [Player] id=54, cardId=LOOT_161, cardName=Carnivorous Cube, zonePos=0,Info={turn=5, originalZone=DECK, OriginalController=2}
4:35:33 PM|Info|Player.CreateInSetAside >> [Player] id=72, cardId=LOOT_161e, cardName=Carnivorous Cube, zonePos=0,Info={turn=5, mark=Created, created=true, hasOutstandingTagChanges=true}
4:35:33 PM|Info|Player.CreateInPlay >> [Player] id=72, cardId=LOOT_161e, cardName=Carnivorous Cube, zonePos=0,Info={turn=5, mark=Created, created=true, originalZone=PLAY, hasOutstandingTagChanges=true, OriginalController=2}
4:35:34 PM|Info|Player.PlayToGraveyard >> [Player] id=40, cardId=CFM_095, cardName=Weasel Tunneler, zonePos=0,Info={turn=5, originalZone=DECK, OriginalController=2}
4:35:34 PM|Info|Player.CreateInDeck >> [Opponent] id=40, cardId=CFM_095, cardName=Weasel Tunneler, zonePos=0,Info={turn=5, mark=Created, stolen=true, created=true, originalZone=DECK, OriginalController=2}
4:35:34 PM|Info|Player.RemoveFromDeck >> [Opponent] id=40, cardId=CFM_095, cardName=Weasel Tunneler, zonePos=0,Info={turn=5, mark=Created, discarded=true, stolen=true, created=true, originalZone=DECK, OriginalController=2}
4:35:34 PM|Info|Player.CreateInDeck >> [Opponent] id=73, cardId=, cardName=, zonePos=0,Info={turn=5, mark=Created, created=true, originalZone=DECK, hasOutstandingTagChanges=true}
```

**Comment by riQQ** [comment] 2018-02-07 21:33
Related to #3359

**Comment by riQQ** [comment] 2018-02-11 20:28
Duplicate of #3359

**Closed** 2018-02-11 20:28 UTC
Labels: duplicate
