### ISSUE TITLE
HDT is resetting in short intervals / Whizbang

### ISSUE THREAD

**Issue by riQQ** [HearthSim/Hearthstone-Deck-Tracker#3779] opened 2018-08-28 20:29 UTC
## Bug report
> were you playing a Whizbang deck?

> nope, i was spectating
don't know if the guy was playing a whizbangdeck tho
based on the cards I am seeing him play with I do argue that he was playing a whizbang deck
pretty dam certain it's "The Boomsday Project" deck recipe for warrior

> did it fix itself in that game?

> the overlay? nope
I stopped spectating and closed the game afterwards
since I wasn't going to be playing

### Actual Behavior
Deck tracker is resetting multiple times 

### Expected Behavior
Deck tracker not resetting

### Steps to reproduce behavior
Unknown

### Log/Screenshots
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2329745/hdt_log.txt)

![5ae87ea](https://user-images.githubusercontent.com/3404787/44748926-5abe1300-ab11-11e8-9f5b-489636240bc4.gif)

**Comment by ceceita** [comment] 2018-09-02 17:08
i posted on discord , the problem is caused by whizbang decks not imported in HDT.
I dont know workarounds to import them without having the card.

**Comment by riQQ** [comment] 2018-10-03 00:57
So this might be resolved with 1.7.6.

**Comment by MrPing1000** [comment] 2019-04-08 00:03
Hi, I'm having this issue with Whizbang now (using 1.8.4) I haven't actually used him in a year, maybe that has something to do with it?  The old decks are there but not the new ones?

**Comment by ceceita** [comment] 2019-04-08 13:39
as i know  to fix the problem you have to delete old whizbang decks manualy , enable the autoimport function and log in the account where you have a whizbang deck in the decks page ..
this will trigger the import of the decks , once you imported them in NA they work in EU .. 
example log
`1:31:39 PM|Info|DeckImporter.FromConstructed >> Found 1 decks, 18 new
1:31:39 PM|Info|DeckManager.ImportDecksTo >> Saving Trees Are Friends as new deck.
1:31:39 PM|Info|DeckManager.ImportDecksTo >> Saving Out of the Woods as new deck.
1:31:39 PM|Info|DeckManager.ImportDecksTo >> Saving The Storm Bringer as new deck.
1:31:39 PM|Info|DeckManager.ImportDecksTo >> Saving Witchwood Awoken as new deck.
1:31:39 PM|Info|DeckManager.ImportDecksTo >> Saving The Boomsday Project as new deck.
1:31:39 PM|Info|DeckManager.ImportDecksTo >> Saving The Gilneas Armory as new deck.
1:31:39 PM|Info|DeckManager.ImportDecksTo >> Saving The Necrium Trials as new deck.
1:31:39 PM|Info|DeckManager.ImportDecksTo >> Saving Stolen Research as new deck.`

whitout having them imported the problems is example log
`8:14:58 PM|Info|DeckManager.AutoSelectDeckById >> Trying to select deck for id=1832
8:15:02 PM|Warning|DeckManager.AutoSelectDeckById >> No deck with id=1832 found`


The problems are multiple
- if you dont have whizbang you cant import decks to use them on friend spectate
- if you dont have autoimport function active , decks are not imported.

**Comment by ceceita** [comment] 2019-04-09 20:43
i confirm with my method i updated new whizbang decks
```
10:39:34 PM|Info|DeckImporter.FromConstructed >> Found 1 decks, 18 new
10:39:34 PM|Info|DeckManager.ImportDecksTo >> Saving Nature's Restoration as new deck.
10:39:34 PM|Info|DeckManager.ImportDecksTo >> Saving Trees Are Friends as new deck.
10:39:34 PM|Info|DeckManager.ImportDecksTo >> Saving Underbelly Underlings as new deck.
10:39:34 PM|Info|DeckManager.ImportDecksTo >> Saving Swamp of Horror as new deck.
10:39:34 PM|Info|DeckManager.ImportDecksTo >> Saving Droppin' the Boom as new deck.
10:39:34 PM|Info|DeckManager.ImportDecksTo >> Saving Wings of War as new deck.
10:39:34 PM|Info|DeckManager.ImportDecksTo >> Saving The Heist as new deck.
10:39:34 PM|Info|DeckManager.ImportDecksTo >> Saving Cursed Crew as new deck.
10:39:34 PM|Info|DeckManager.ImportDecksTo >> Saving The Sunreavers' Secrets as new deck.
10:39:34 PM|Info|DeckManager.ImportDecksTo >> Saving Shirvallah's Chosen as new deck.
10:39:34 PM|Info|DeckManager.ImportDecksTo >> Saving The Scrap Heap as new deck.
10:39:34 PM|Info|DeckManager.ImportDecksTo >> Saving Animal Instincts as new deck.
10:39:34 PM|Info|DeckManager.ImportDecksTo >> Saving Ultimate Impfestation as new deck.
10:39:34 PM|Info|DeckManager.ImportDecksTo >> Saving Hand of Gul'dan as new deck.
10:39:34 PM|Info|DeckManager.ImportDecksTo >> Saving Archmages of Dalaran as new deck.
10:39:34 PM|Info|DeckManager.ImportDecksTo >> Saving Khadgar's Creations as new deck.
10:39:34 PM|Info|DeckManager.ImportDecksTo >> Saving Day of the Dead as new deck.
10:39:34 PM|Info|DeckManager.ImportDecksTo >> Saving Whispers from the Grave as new deck.
```

**Comment by ceceita** [comment] 2019-04-24 12:22
from discord

> I used a golden whizbang deck from duel with friend I borrowed his whiz and the deck tracker gone wild it kept flashing and not recording the cards in 1st game
> 2nd game I had to turn of auto detect deck so I can see what cards I've played

**Comment by x-ProgrammEd-x** [comment] 2021-08-31 08:39
Still the same for me, Reload Loop, Deck not showing/not recognized.

**Comment by x-ProgrammEd-x** [comment] 2021-08-31 16:01
[ Whizbang Decks Issue (NoShow/"Reload Loop") #4046 ](url)

This issue still persists for me. Any nows on that front?

**Comment by Dalarrus** [comment] 2023-11-17 08:26
Seems to be resolved, can play whizbang decks just fine now.

**Comment by Dalarrus** [comment] 2023-11-17 08:27
Still an issue :(

**Comment by beheh** [comment] 2023-12-20 01:56
I believe this should be fixed now with the new way we import Whizbang decks. Please let us know if it's still an issue!

**Closed by beheh** 2023-12-20 01:56 UTC
Labels: bug, workaround, decktracker
