### ISSUE TITLE
Syncing between computers

### ISSUE THREAD

**Issue by ABRHTTR** [HearthSim/Hearthstone-Deck-Tracker#2610] opened 2016-06-16 08:52 UTC
Okay I know this has been asked before but I cannot for the life of me get this to work. I currently own 2 computers and cannot get my Arena runs to sync between them. I am about to reformat my primary computer and don't want to lose all of my stats. 

I have tried some of the instructions from other posts and the FAQ to get my stats from my ASUS onto my Surface but it never works. It only syncs the constructed decks, and even then, it does not show my record with each deck.

I am not very tech savvy, but I tried the DropBox method and it still did not work. If anyone at all had the same problem and was able to resolve it, please let me know what you did so that I can hopefully fix it before I reformat my computer. A thorough step by step would do wonders for this technologically challenged guy over here. Thank you so much in advance. Sorry for my scrubness. 

-Daniel

**Comment by Epix37** [comment] 2016-06-17 10:12
Are you asking for continuous syncing or a one time transfer to another machine? It sounds a bit like the latter  and it that case all you need to do it copy the `%AppData%/HearthstoneDeckTracker` (`options > tracker > setting > open appdata folder`) folder to the new machine.

**Comment by ABRHTTR** [comment] 2016-06-17 10:55
That was one thing I was worried about, thank you. However what I'm primarily wondering is if there is a way to keep my hearthstone stats (including constructed decks and records, all previous arena runs, arena stats, etc) constantly synced between two computers, or at the very least, sync the statistics, runs, and decks from both computers manually every once in a while. If I could at least do the latter I'd be able to just manually add all of the arena runs I do and ranked wins and losses I get onto my primary computer since I use one more often then the other.

Btw thank you very much for the hasty response. Your help is much appreciated. 

-Daniel

**Comment by Epix37** [comment] 2016-06-17 14:00
We are working towards adding full syncing (decks, arena runs, stats, settings...) between multiple machines. I can't give you an eta yet, but it's definitely near the top of the list!

This should do the trick for getting Dropbox syncing working: 

> A even better way to accomplish this is to use symbolic link this is how I configured my Deck-Tracker:
1. Move the HearthstoneDeckTracker folder (with all the files) located in %APPDATA%\HearthstoneDeckTracker to your Dropbox folder. Make sure that the original folder does not exist.
2. Create a symbolic link that connects %APPDATA%\HearthstoneDeckTracker with the dropbox folder use the command : 
mklink /j %APPDATA%\HearthstoneDeckTracker d:\dropbox\HearthstoneDeckTracker
3. Do the same way on all computers you wish to use.
4. Enjoy your synced Hearthstone Deck Tracker

**Note: I have not tried this, so make sure you back up your `%APPDATA%\HearthstoneDeckTracker` folder before doing it.**

Source: https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/545#issuecomment-70380390

**Comment by 305jeff** [comment] 2016-08-23 22:59
Is the symbolic link still the best way to accomplish this? I just got a Surface Pro 4 and want to keep stats synced between it and my desktop. Hearthstats syncing is doing half the job, but it does not include decks/replays/etc., so it's not quite what I want.

Thanks!

**Comment by jleclanche** [comment] 2016-08-23 23:21
@305jeff We're working on adding some of that syncing to hsreplay.net, but it'll take some time. In the mean time, symlinks are the best way.

**Comment by 305jeff** [comment] 2016-08-23 23:43
@jleclanche Thank you for the response. The issue I see with the symlinks and Dropbox is that it appears to mirror the entire config file as well...so all my settings would have to be exactly the same on each computer. That seems problematic since the Surface Pro 4 has a different resolution/positioning of all the items. Is there any way to work around that?

Thanks!

**Comment by jleclanche** [comment] 2016-08-23 23:44
At the moment I don't think so, sorry.

**Comment by 305jeff** [comment] 2016-08-24 01:14
@jleclanche So I didn't give up and thought maybe the solution is to create a _second_ symlink...move the config.xml file to another location and create a symlink in Dropbox so that the config.xml is local and everything else is in Dropbox.

mklink d:\dropbox\HearthstoneDeckTracker\config.xml %APPDATA%\config.xml

Testing this now, but in theory it makes sense, no? This is my first time using mklink so I'm just trying stuff. I'm not sure if it's necessary to add a /h argument to make it a hard link...as I haven't read an explanation about symlink for /h hardlink that really makes sense to me!

Thanks again,

Jeff

**Comment by 305jeff** [comment] 2016-08-24 01:40
Ok there was a little complication...Dropbox sync'd the symlink as a normal file, which prevented me from creating a symlink on the Surface. I found a little track to get Dropbox to ignore the config.xml file, allowing me to create two separate symlinks on the different computers:
http://superuser.com/questions/469776/how-to-exclude-files-not-folders-from-dropbox-sync

_To exclude FILES, not folders, from Dropbox, there is a trick you can do:

Move the file somewhere else
Create a folder with the same name in place of the file
Go to Dropbox selective sync options and ignore the folder, this will also delete it
Move the file back in place_

So now the question is whether or not this will function properly where HSDT is fully sync'd via Dropbox EXCEPT for separate local symlink'd config.xml files.

Testing continues!

**Comment by Zesaric** [comment] 2016-08-24 20:28
Just to provide an additional idea: I applied the symlink method using **Microsoft OneDrive** instead of Dropbox - and on quick glance it does seem to work well (at least between my Laptop and my main PC).

However, I haven't tried this syncing to a Surface yet, but might try that as well as soon as I have the opportunity to do so.

**Comment by 305jeff** [comment] 2016-08-25 03:45
I'm happy to say that after playing games on both devices a few different times, everything appears to be syncing perfectly via Dropbox...AND the symlink for the separate config files is working as well!

**Comment by 305jeff** [comment] 2016-08-25 12:35
I made this into a little mini-guide:
https://www.reddit.com/r/hearthstone/comments/4zi860/how_to_sync_hearthstone_deck_tracker_on_multiple/

**Comment by TheOneGodKing** [comment] 2016-08-30 03:33
I tried setting this path to sync between multiple computers. I get the following error: "The system cannot find the path specified." Any help to get this working would be greatly appreciated. 

![untitled](https://cloud.githubusercontent.com/assets/21326969/18075232/ec246dcc-6e40-11e6-95fe-43e71eec3c45.png)

**Comment by riQQ** [comment] 2016-08-30 06:13
Do both folders exist?

**Comment by 305jeff** [comment] 2016-08-30 10:57
@TheOneGodKing You have three directories in your command for some reason. The first thing should be mklink /j - so... mklink /j [directory1] [directory2]

**Comment by TheOneGodKing** [comment] 2016-08-30 14:48
@riQQ Yes. I copied the files that were originally in the AppData folder. The HearthstoneDeckTracker in Appdata folder does not exist. I deleted it. 

@305jeff The "C:\Users\Suhas Rao>" at the beginning is already there when I open up command prompt. I set it back to "C:\>" and tried the link again and it didn't work. Should that initial directory be blank? Not sure how to remove it. 

![untitled-1](https://cloud.githubusercontent.com/assets/21326969/18093844/566797f0-6e9f-11e6-9b46-33962832c05a.png)

**Comment by riQQ** [comment] 2016-08-30 22:14
Is the path to your Dropbox folder really correct?

**Comment by TheOneGodKing** [comment] 2016-08-31 00:05
@riQQ The quotation marks seemed to do the trick. Thank you very much for your help. Just to make sure it is displaying correctly. After the link has been made, I should still see a copy in the AppData folder. This folder will just be updated from the Dropbox folder.

**Comment by riQQ** [comment] 2016-08-31 06:29
Yes, the folder in AppData should have a link icon on it and if you double click this folder link, you'll see the contents of your link target (your HDT Dropbox folder).

**Comment by YanTS** [comment] 2017-06-16 18:42
Is the solution with symlinks still considered the best?

**Comment by 305jeff** [comment] 2017-06-16 18:48
I haven't heard of a better solution that's implemented yet, so I think so. It's still working fine for me.

**Comment by YanTS** [comment] 2017-06-16 18:49
Does it actually work correctly with multiple Trackers launched on multiple computers?

**Comment by 305jeff** [comment] 2017-06-16 18:54
I'm only using it on two devices but it syncs them properly. I don't see why it would be different with more than 2. I think the main point of concern is not interrupting the backup process:

1) Set HSDT to close after your close HS, so you don't leave it open by mistake. Make sure to close HSDT/HS whenever you leave your computer so you don't open it in two places by mistake.
2) After turning on my Surface Pro, I wait a few seconds for Dropbox to finish syncing before I open HSDT.

Aside from keeping that in mind, I have no real issues that I can trace back to this. I am hoping for a supported/built-in solution, but there's no promise as to when/if that will come.

**Comment by YanTS** [comment] 2017-06-16 18:59
I use hdt on 2 desktops which are always on.
I don't like closing hdt because it opens too long. 
Question to devs. If both instances of HDT is up, and one of them updates the files, and files got synced by cloud, and then second instance of HDT wants to update - will it overwrite the changes from first?

**Comment by 305jeff** [comment] 2017-06-16 19:03
I haven't really tested that - seems problematic to me but either a dev can answer or give it a try and see how it works.

**Comment by judge2020** [comment] 2017-06-16 19:18
Hearthstats has been discontinued, please see #3235 for the new feature HSReplay is planned to have.

**Comment by judge2020** [comment] 2017-06-16 19:18
You can continue to chat here however it is better if we congregate the syncing requests to that issue.

**Closed by judge2020** 2017-06-16 19:18 UTC

**Comment by judge2020** [comment] 2017-07-19 20:49
duplicate of #3235

**Comment by riQQ** [comment] 2017-08-13 09:48
@YanTS HDT reads the config once at startup, so changes done by one instance won't be picked up by the other one, if they are both already running.

**Comment by karimsah** [comment] 2020-06-12 08:20
Having suffered an hdd failure, i'm very glad i did that.
Thanks azeier.
