### ISSUE TITLE
Strange interaction between Undercity Huckster and Flame Leviathan (?)

### ISSUE THREAD

**Issue by GreatSc0tt** [HearthSim/Hearthstone-Deck-Tracker#3578] opened 2018-03-07 18:34 UTC
### Expected Behavior
The card given to the opponent from an Undercity Huckster is not displayed in the tracker unless played or revealed.

### Actual Behavior
The opponent received a Flame Leviathan from an Undercity Huckster and the tracker showed me this information. The card was never played in the game and there was no damage dealt since it wasn't drawn, however the tracker still showed me the card he received (It's possible that this wasn't the card given to the opponent, since it was never played, but unsure).

### Steps to reproduce behavior
Since the issue was discovered as a result of a random Mage card being given to a Rogue, reproduction would be very difficult.

### Log/Screenshots
A link to the hsreplay:
https://hsreplay.net/replay/YGsXe5nDvLKgyYtcYeu5ed

**Comment by riQQ** [comment] 2018-03-07 18:41
It's an info leak in the Hearthstone logs. It can probably be worked around, but isn't really high priority.

**Comment by judge2020** [comment] 2018-03-07 18:42
Ref #2351 and https://github.com/HearthSim/hs-bugs/issues/19

**Comment by riQQ** [comment] 2018-03-07 18:43
Duplicate of #2351

**Closed** 2018-03-07 18:43 UTC
Labels: won't fix
