### ISSUE TITLE
HDT Stops tracking decks and deck changes

### ISSUE THREAD

**Issue by Hemagic1973** [HearthSim/Hearthstone-Deck-Tracker#3032] opened 2016-12-17 01:32 UTC
So ran into this today. I completely uninstalled. Lost ALL my stats for weeks of tracking. It goes into no deck mode. Doesn't record games or recognize I am even playing a game. Updates decks or anything. I reinstall works for 2 games then does it again. Very frustrating to lose weeks for statistics

**Comment by jleclanche** [comment] 2016-12-17 01:40
Not sure I understand. You say you uninstalled, then it stopped tracking? Or what happened to make it stop tracking?

By default HDT doesn't delete user data on uninstall. Did you look at whether the stats are still saved somewhere?

**Comment by Hemagic1973** [comment] 2016-12-17 01:43
I am not sure why it stopped tracking. I uninstalled it because it did and done everything I could think of to make it track. Nothing. Quit updating my deck changes, tracking my games nothing. So that is why I uninstalled it completely. Program and DATA. Reinstalled it and worked for 2 games and did it again. I am at a loss what is causing this

**Comment by jleclanche** [comment] 2016-12-17 01:45
- Is it possible you have an antivirus running that's quarantining the config files?
- Do you only lose your decks/stats or also the HDT configuration?
- Are you logged into HearthStats?
- Did you claim an HSReplay.net account?

**Comment by Hemagic1973** [comment] 2016-12-17 01:50
I only got Windows Defender which pretty sure is not blocking it. 
My settings are still all there. Just lose it ability to recognize games and stat tracking. Goes into No deck mode. I take it off no deck mode shows the deck but doesn't track anything
Not sure if logged into HearthStats.. Where is that?
yes I claimed my HSReplay.net account

**Comment by Hemagic1973** [comment] 2016-12-17 09:35
Guess I am SOL? :(

**Comment by azeier** [comment] 2016-12-17 09:39
- Please play a game with HDT running and upload the log - see here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues
- HDT keeps daily backups, depending on what data got lost you might be able to recover your decks/stats: Check `options (advanced) > tracker > backups`.

**Comment by Hemagic1973** [comment] 2016-12-17 15:48
Well of course start it up today and working fine. If it crashes again will post the log. I deleted all the appdata so no backups to recover. Cause kept installing it and all the same data which felt corrupt to me. Why it wouldn't update. Once I did the full clean install it worked again, but did stop after 2 games. Played a few this morning and so far it's recognizing me playing, updating any changes to my decks. So will see

**Comment by Hemagic1973** [comment] 2016-12-18 01:40
Ok just played a game. It did not recognize I even played a game. Did not create a log for this session nothing. Ugh

**Comment by azeier** [comment] 2016-12-18 09:36
If HDT doesn't generate logs you are very likely having permissions (HDT is not allowed to write to %AppData%) or anti virus (deletes files in %AppData%/HearthstoneDeckTracker for whatever reason?) issues. I think more likely the former.

**Comment by Hemagic1973** [comment] 2016-12-18 09:39
It has told me it does not have same permission as hearthsone I start it as Admin and still did it. But will make sure. Just weird how it will work and then stop out of the bkue. This ran for weeks with no problems not to mention

**Comment by Hemagic1973** [comment] 2016-12-23 21:39
It did it again. It told me it does not have same permission as hearthstone. It IS set to run as admin. Do not know why it is telling me. In turn it will not recognize that I am playing any decks. Here is the log from when it would not play. I had to lose all my stats for a second time. This is getting frustrating :( I appreciate any help @azeier 
[hdt_log_1482528678.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/671472/hdt_log_1482528678.txt)

**Comment by azeier** [comment] 2016-12-23 22:00
For some reason HDT is still not able to access the Hearthstone process. 
I could see this being an issue with your antivirus software. Try setting HDT and Hearthstone as exemptions or disabling it.

**Comment by Hemagic1973** [comment] 2016-12-23 23:58
I told Windows Defender to exclude appdata\Local\Hearthstonedecktracker and appdata\local\hearthstonetracker anything else I should exclude?

**Comment by Hemagic1973** [comment] 2016-12-24 00:14
Played another game. Did not track my deck, but was tracking his deck. Which I have turned off. It did not even create a log for the game play. Don't get why this works for a week or two then stops working. Never had track-o-bot but like this cause easier to track specific decks

**Comment by riQQ** [comment] 2018-10-02 23:35
Excerpt from the log:
> 4:30:55 PM|Error|LoadingScreenHandler.CheckMirrorStatus >> System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.OpenProcessHandle(Int32 access)
   at System.Diagnostics.Process.get_Handle()
   at HearthMirror.ProcessView..ctor(Process proc)
   at HearthMirror.Mirror.get_View()
   at HearthMirror.Status.GetStatus()

**Comment by riQQ** [comment] 2018-10-02 23:36
Duplicate of #2738

**Closed by riQQ** 2018-10-02 23:36 UTC
Labels: support
