### ISSUE TITLE
[Feature Request] Tracking the source of cards added to opponent's hand

### ISSUE THREAD

**Issue by royard** [HearthSim/Hearthstone-Deck-Tracker#3076] opened 2017-01-12 16:28 UTC
Right now, whenever a card is added to the opponent's hand through a card effect (e.g., a coin added by a dead tomb pillager, or a mage/priest/warlock card discovered by kabal informant), that card is marked with a gift box graphic, but no additional info is provided.  

It will be great if this feature can be enhanced to show the source of the card (tomb pillager/kabal informant).  

I'd imagine it could be implemented similar to the "return to hand" feature we already have.  Currently, a returned card in opponent's hand has a "returned" graphic, and when you hover your mouse over the graphic, it shows what card it is.  So I think a similar message added to the "gift box" graphic that says the source of the added card (something like "Added by Tomb Pillager") would be doable.  

As long as the gift box graphic shows the source of the added card, it will be easy to check your opponent's played card list and see the type of the added card (e.g., a coin, in the case of a tomb pillager).  

This feature is desirable because there are just so many "add card to hand" effects in the game now.  Dragon priest can discover dragons, cards in your deck, cards in your hand, etc.  Reno mages have a bunch of cards that add random mage spell or discover mage spells, fireballs added by antonidas, and of course kazakus.  Miracle can burgle your class card and have the coins from tomb pillager; other types of rogue have deathrattle discovers.  Sometimes many cards in your opponent's hand will be marked with a gift box and it's hard to remember which is which.  So it will be great to be able to keep track of them.

**Comment by riQQ** [comment] 2017-01-12 18:05
Duplicate of #2224.

**Comment by judge2020** [comment] 2017-06-10 03:47
closed in favor of the list at #2224

**Closed by judge2020** 2017-06-10 03:47 UTC
Labels: decktracker, feature request, UI
