### ISSUE TITLE
White overlay in HDT window stays if X is clicked on the "wrong deck detected" popup

### ISSUE THREAD

**Issue by Fyren** [HearthSim/Hearthstone-Deck-Tracker#2023] opened 2016-01-27 20:21 UTC
If you play with a deck not known to HDT, you get a popup window asking if you want to play with no deck or pick a deck or whatever.  If, instead of picking one of those options, you click the X in the corner of the window, the translucent white overlay stays on the main window afterwards.  Restarting HDT resolves it (and maybe getting it to prompt you again about the wrong deck would if you pick one of the options?).

**Comment by Epix37** [comment] 2016-01-28 11:24
Could be an issue with MahApps 1.1.2. There is a new release by now but updating breaks pretty much every single plugin - not sure when/if yet.

Does this happen (only) if HDT is minimized to tray at the time?

**Comment by Fyren** [comment] 2016-01-29 11:57
With HDT not minimized to the tray, the window displays "wrong deck detected" with an OK button.  Clicking the button clears the message and the white overlay.

**Comment by culinko** [comment] 2016-06-22 17:27
Couldn't reproduce this issue.

**Comment by culinko** [comment] 2016-06-22 17:31
Reproduced the issue in 0.15.6, only happens if HDT is minimized in tray and after it happens, the HDT window is not interactible.

![darkened](https://cloud.githubusercontent.com/assets/11700272/16276707/ce89e358-38af-11e6-8165-5f1761048d7e.png)

**Comment by Epix37** [comment] 2016-06-22 17:33
Probably fixed by updating to the latest MahApps version. I will do that at some point - hesitant because it will break every single plugin.

**Comment by riQQ** [comment] 2018-01-20 11:15
This is fixed now.

**Closed by riQQ** 2018-01-20 11:15 UTC
Labels: UI, bug
