### ISSUE TITLE
(Korean version HDT)When i choose Millhouse Manastorm in battleground than HDT doesn't work for that round

### ISSUE THREAD

**Issue by hero864** [HearthSim/Hearthstone-Deck-Tracker#4104] opened 2020-06-16 18:01 UTC
### Log/Screenshots
![버그1](https://user-images.githubusercontent.com/64659754/84810398-43ce1500-b046-11ea-8ba7-42261fc16979.png)

Just printed "Waiting for combat" and nothing more
This issue started since when Millhouse Manastorm added in Battleground for Korean version of HDT

**Comment by azeier** [comment] 2020-08-11 22:17
Duplicate of #4026

**Closed by azeier** 2020-08-11 22:17 UTC
Labels: battlegrounds, bug
