### ISSUE TITLE
HDT Overlay Will Cut Off At The Bottom Half Of The Screen

### ISSUE THREAD

**Issue by Baronmeister** [HearthSim/Hearthstone-Deck-Tracker#4077] opened 2020-05-17 06:40 UTC
## Bug report
HDT will only use the upper half of the screen to show elements such as my deck

### Expected Behaviour
The Deck Tracker Elements should be able to cover the whole screen

### Actual Behaviour
After I added a secondary monitor, HDT will only use the upper half of the screen to show elements such as my deck. I have tried moving down the elements but it essentially disappears completely when below the second half of the screen.

There is a temporary solution to this issue, as for some reason it works as expected only when it's on the secondary monitor AND if Google Chrome is closed. However as that monitor is used for other things and I like using chrome while playing, this isn't perfect.

### Log/Screenshots
![Cropped Issue 2](https://user-images.githubusercontent.com/65480247/82137236-9ce53600-9859-11ea-8edb-41ffd5fd8dfe.png)
![Cropped Issue](https://user-images.githubusercontent.com/65480247/82137241-a078bd00-9859-11ea-970c-4a1a2d9c7b3f.png)
![Temporary Solution](https://user-images.githubusercontent.com/65480247/82137245-a40c4400-9859-11ea-9f08-20194e676323.png)

**Comment by riQQ** [comment] 2020-05-17 10:14
Do you have different DPI settings for these monitors?

**Comment by Baronmeister** [comment] 2020-05-17 10:26
Yeah that was it! I was looking for ages I can't believe I didn't check that. Thanks a bunch :)

**Comment by riQQ** [comment] 2020-05-17 10:54
Keeping this open as this is still an issue despite having a workaround

**Comment by azeier** [comment] 2020-05-19 21:25
Duplicate of #4077? I think we can close this one.

**Closed by azeier** 2020-05-19 21:25 UTC
Labels: bug, overlay, workaround

**Comment by riQQ** [comment] 2020-05-20 08:36
Duplicate of #3445
