### ISSUE TITLE
Feature Request: Make HDT portable.

### ISSUE THREAD

**Issue by TemporalOnline** [HearthSim/Hearthstone-Deck-Tracker#2985] opened 2016-12-01 15:40 UTC
Hi, I have a user problem (again).

In the past, HDT used all its files in one folder, the folder I installed it in. It was useful for me as I could transport HDT through all my computers and didn't need to reinstall either HDT or Hearthstone in whatever machine I decided to play with, and all my settings would be restored (hence, why I used to install HDT inside Hearthstone's folder).

Then it started to put part of its settings inside AppData's folder, (yeah, I know, they "should" be there), but I still could set everything in a way that I could transport everything at once. Even the update worked (as long as I always reset HDT to have higher privileges every time an update occurred).

Well, today when updating from 1.1.1 to 1.1.2, it broke in a way that it reset and there is no way to put it back without setting everything by hand.

Having to manage all the folders (HDT's install folder, and HearthSim + HearthstoneDeckTracker settings folders) is becoming increasingly difficult. This last update broke everything, no matter what I try to do, it won't read my old settings.

If I had an option to keep everything in one folder, as it was in the past, it would be much appeciated.

I understand that you might want to try to keep everything "clean" or "proper" or "easy" for everyone that first uses it, but if I wanted "proper" or "clean" I would just play hearthstone and be done.

I wish I could transport HDT and all its settings in my HD case, alongside Hearthstone, just like I did in the past.

I can't do it anymore, I have to install it in each machine, and set it up in each machine, because I can't keep up with which files are what and which should I copy in order to preserve my settings.

**Comment by judge2020** [comment] 2016-12-01 16:21
You can still download the zip file from https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases and turn off 

**tracker > settings** save **data/config** in appdata

**Comment by speedytr** [comment] 2016-12-02 10:19
I think it will be great if hdt somekind of sync system between computers (like decks, stats, options)

**Comment by Spedwards** [comment] 2016-12-02 19:30
@speedytr They could theoretically doing that by creating a database on their existing website. Would require an account that you just log into. All storage is saved there.

**Comment by azeier** [comment] 2016-12-02 19:39
We plan on doing something like that soon ;).

**Comment by DerfelKadarn** [comment] 2016-12-13 10:24
I play in 3 different computers and manage it by setting the Data Path to my Dropbox folder. You should have your tracker > settings save data/config in appdata set to False and update by downloading the ZIP distribution rather than the automatic update. One thing you need to remember is to close HDT when you finish using it on one computer before moving to another.
If you see your progress missing on the other computer, go to your dropbox folder and right click the Deckstats.xml file and restore it to the previous version. This file always grows, so the file that contains the most updated data is the largest one (unless you have deleted a deck with its stats)

**Comment by judge2020** [comment] 2017-05-15 14:26
A feature to sync HDT between computers is in the works with hsreplay. A good issue to combine these requests in is #3235.

**Closed by judge2020** 2017-05-15 14:26 UTC

**Comment by judge2020** [comment] 2017-07-19 20:48
duplicate of #3235
