### ISSUE TITLE
Yogg-Saron Spell tracker!

### ISSUE THREAD

**Issue by xMoltrex** [HearthSim/Hearthstone-Deck-Tracker#2401] opened 2016-04-27 19:01 UTC
So apparently Yogg-Saron spell tracker is bugged. The bug is that the spell number does not reset after the game. What it does instead is that the starting number that should be 0 is actually the number left off from the last game and i doesn't fix itself by restarting a game or a deck tracker client. Tell If you need any more information like screenshot or a logs.

**Comment by jleclanche** [comment] 2016-04-27 19:03
Dupe of #2399

**Closed by jleclanche** 2016-04-27 19:03 UTC

**Comment by xMoltrex** [comment] 2016-04-27 19:06
Oh sorry didn't see it i guess :/
