### ISSUE TITLE
Why is HDT still broke?

### ISSUE THREAD

**Issue by Glitchex** [HearthSim/Hearthstone-Deck-Tracker#3932] opened 2019-06-22 11:25 UTC
The deck tracker is still broken after recruiting a minion from the inn and drawing it during a fight. It breaks so bad that it lags and I have to turn it off. Ive done everything your help page has said to do. Please fix this its been like this for over a month. Thank you.

**Comment by riQQ** [comment] 2019-06-24 06:45
Duplicate of #3917

**Closed by riQQ** 2019-06-24 06:45 UTC
