### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by samanking** [HearthSim/Hearthstone-Deck-Tracker#2584] opened 2016-06-06 17:17 UTC
Hello!

So my problem is when I'm playing with Hearthstone and using HDT after some game HDT starting use a lot of memory in my case I have 4GB and HDT use all of free memory left.

![hdtmemoryerror](https://cloud.githubusercontent.com/assets/19782599/15830925/2314bfc0-2c1b-11e6-97e1-354b5dfbecc0.jpg)

I attached the picture I hope you can help me understand what is the problem.

**Comment by Epix37** [comment] 2016-06-06 17:43
Hm I definitely can't reproduce this right off the bat. Please restart HS and HDT and try to monitor when the memory usage becomes that high (or even just reaches 300mb).

**Comment by goldenmane** [comment] 2016-06-07 03:00
I have the same problem, memory and CPU usage is quite high, it wasn't like this in earlier version in my case. Usually it's around 200 mb and CPU 20% even, sometimes it goes up to 2 GB when I start the game and I have to force close the tracker.

**Comment by goldenmane** [comment] 2016-06-07 03:09
and actually happened a minute ago, 1,5 gb memory usage caused my PC to freeze before I had to force close. I think I'm gonna roll back to previous version.

**Comment by Epix37** [comment] 2016-06-07 05:51
If you do, please let me know which previous version is not having this issue.

**Comment by goldenmane** [comment] 2016-06-07 07:07
I actually rolled to 0.14.9 as I didnt have any problems with that version. In my case, the problem with memory usage is only at the start of the game when I choose a game mode in HS. It doesn't happen while playing or while choosing an opponent, only while I click play and then HS and Deck Tracker just freeze (once every 15 games maybe but it's kinda annoying.)

**Comment by Epix37** [comment] 2016-06-07 09:36
do all the 0.15.X releases have this problem for you?

**Comment by Epix37** [comment] 2016-06-07 16:32
I just had an idea what might be causing this. Please try this version: https://github.com/Epix37/HDT-Test/releases/tag/v0.15.4.pre1

**Comment by samanking** [comment] 2016-06-07 17:34
okay, i will test it and inform you

**Comment by interro-bang** [comment] 2016-06-07 19:42
Getting the same issue here, which for me started only since updating to v0.15.3
![screenshot 2016-06-07 20 32 49](https://cloud.githubusercontent.com/assets/19805843/15872138/c6c19aba-2cef-11e6-8df0-cb98d7bd072f.png)

Was working normally until I tried to export a deck to HS, then it froze and memory spiked before it crashed. It's repeatable and happens every time. It'll type the deck name, clear the filters and sometimes enter the first card name before crashing. Even log errors are: http://pastebin.com/aGgTTQ68

Updated to v0.15.4.pre1, but still the same issue

**Comment by Epix37** [comment] 2016-06-07 20:25
Could you downgrade release by release and see with which version this was introduced? Was it ok with v0.15.2?

**Comment by interro-bang** [comment] 2016-06-07 21:08
So I downgraded to v0.15.2 and restarted the HS client, launched HDT and could export with no crash/hang. Then went back to v0.15.3 and exported the same deck, still worked fine. I played through a game with that deck, and it was still working fine by the end.

The only other thing I noticed right before it started happening was a "data cleanup" popup in HDT, which I did. But I didn't clear my AppData folder since then, so I guess it wasn't directly due to that. Maybe a restart of HS+HDT would have been enough to fix it, if someone else could test that?

**Comment by samanking** [comment] 2016-06-07 23:43
The issue cause when I making a deck in HS and the automatic deck import importing the deck when going to Play.

**Comment by Kurapika92** [comment] 2016-06-08 04:34
I've been having the same issue as well. I think it began for me after updating to version 0.15.2. The deck tracker stops responding and my entire laptop slows down to a crawl. I have to Ctrl Alt Del to end the task and even that ends up taking minutes. Just had it happen to me today and once I got the deck tracker to close, everything was back to normal and I could resume my Hearthstone arena draft just fine.

**Comment by goldenmane** [comment] 2016-06-08 05:54
last stable version for me is 0.15.1 I think. however I haven't played as long as to be sure of it, just didn't have any problems with 0.15.1 as of yet, 0.15.2 definitely has this issue and 0.14.9 I haven't had any problems with at all.

**Comment by Epix37** [comment] 2016-06-08 07:01
The next time you guys manage to reproduce it, please post the hdt log here ([see here](https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues)).

**Comment by Epix37** [comment] 2016-06-08 07:54
This could be some specific setting causing it. Someone please try this:
- `options > tracker > settings > open appdata folder`
- close hdt
- rename the `config.xml` (e.g. to `config1.xml`)
- start HDT again and, without changing any settings, see if the problem still occours
- if no: please upload the renamed config file
- afterwards: close hdt, delete new `config.xml`, rename old one back.

**Comment by tapcio** [comment] 2016-06-09 11:12
Same here, memory leaks somewhere, more info soon.

**Comment by Epix37** [comment] 2016-06-09 12:20
Still all working fine for me with those settings :/. 

Can I get some more config files from you guys? Hopefully there's a pattern. 
Also a log of when the leak happens could be very helpful (see above).

If anyone experiencing this is able to attach a debugger and have a look at the memory, that would be amazing.

**Comment by Nucleoprotein** [comment] 2016-06-09 12:22
I used settings/replays etc. inside HDT folder when hangs happened, then switched to %appdata%, maybe this is the problem ?

**Comment by Epix37** [comment] 2016-06-09 12:35
Could you email me your entire HDT folder (with which the leak occours) to epix@hsdecktracker.net?

I agree on CPU usage, it's on my radar. However, most likely unrelated to this.

**Comment by Nucleoprotein** [comment] 2016-06-09 13:49
I sent you the files.

**Comment by Epix37** [comment] 2016-06-09 14:38
Thank you. Tried anything I could think of for 20 minutes now, memory never exceeded 180MB :S.

I guess resetting the config will be the temp workaround for now.

**Comment by Nucleoprotein** [comment] 2016-06-09 18:12
Do you logged to hearthstats ? I removed my auth file for known reasons - do not want to share my pass/account, and maybe issue is with network code. Stats are uploaded on duel end ?

**Comment by Kurapika92** [comment] 2016-06-10 01:35
@Epix37 I haven't been able to reproduce the problem for a couple of days now so that's why I haven't sent you any of the things you've requested. I will if the issue pops up again, but for right now, it's smooth for me on version 0.15.3

**Comment by araknophobia** [comment] 2016-06-11 04:56
> This could be some specific setting causing it. Someone please try this:

    options > tracker > settings > open appdata folder
    close hdt
    rename the config.xml (e.g. to config1.xml)
    start HDT again and, without changing any settings, see if the problem still occours
    if no: please upload the renamed config file
    afterwards: close hdt, d

elete new config.xml, rename old one back.

I did this and haven't noticed any memory leaks since I did. My renamed config file is attached.

[config1.zip](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/310103/config1.zip)

**Comment by Kurapika92** [comment] 2016-06-13 23:50
@Epix37 Had the issue happen to me again right now. Here's the HDT log from when it happened. Also linked the Windows Log File + details.

[HS.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/312900/HS.txt)
![hearthstone decktracker error](https://cloud.githubusercontent.com/assets/7920262/16026899/9eb8375e-3186-11e6-89fa-92cb54301c3d.PNG)
[HS2.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/312903/HS2.txt)

**Comment by livejamie** [comment] 2016-06-18 10:56
Having this issue as well. Attaching my config file and the last few logs.

All the same problems the others are having with exporting and just leaking and freezing randomly in the middle of games.

![2016-06-18_03-47-56](https://cloud.githubusercontent.com/assets/49513/16170463/7f02720a-3508-11e6-8292-8eb6f1a4c34a.png)

[Logs.zip](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/321699/Logs.zip)
[config.xml.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/321700/config.xml.txt)

**Comment by Epix37** [comment] 2016-06-18 12:04
Since deleting the config seems to help: try logging out of hearthstats (from the menu item), see if you still get this problem.

**Comment by Kurapika92** [comment] 2016-06-21 04:22
> Since deleting the config seems to help: try logging out of hearthstats (from the menu item), see if you still get this problem.

I'll be trying this now and will see how it performs in the coming days. Will report back any issues.

**Comment by ZlatanHot** [comment] 2016-06-21 19:39
When I start Hearthstone and play the first game, the tracker freezes and its memory usage sky rockets. This forces me to terminate the process.
I've updated to v0.15.4, but had the same issue for the past 2 versions.
Renaming config.xml, restarting, and restoring it didn't work out.
I've since logged out from Hearthstats like @Epix37 recommended and experienced no issues. Tracker memory use stays at 150 MB.

I have around 80 games logged on my Hearthstats account. Perhaps the issue is with updating them after the game ends?

I really like the Hearthstats integration, so I'm thinking of rolling back to 0.15.1

**Comment by livejamie** [comment] 2016-06-21 19:56
I have a ton of games in my account as well.

**Comment by Epix37** [comment] 2016-06-21 22:45
I have another idea what might be causing this. I'll post a test release here tomorrow.

**Comment by Nucleoprotein** [comment] 2016-06-21 23:25
0.15.6 is causing memory leak on export deck to hearthstone, reproducible every time ...

**Comment by Epix37** [comment] 2016-06-22 06:51
@ZlatanHot Does the issue come back if you upgrade to 0.15.2 now?

**Comment by ZlatanHot** [comment] 2016-06-22 07:35
@Epix37 I upgraded to 0.15.2 and played one game. Memory use stayed below 150 MB, didn't freeze. I have to go to work now, will test more in the evening.

**Comment by Nucleoprotein** [comment] 2016-06-22 09:41
I deleted my comment, but I experience memory leak and crash when exporting deck to Hearthstone in 0.15.6, even downgrading to 0.15.3 did not help, but restarting **game** helped, dunno why.

**Comment by ZlatanHot** [comment] 2016-06-22 19:05
Still stable back on 0.15.2 for me. Played a ranked game on EU, switched to NA, then got this warning after exiting HS:
![uneven permissions](https://cloud.githubusercontent.com/assets/20073852/16279640/31f4958a-38bc-11e6-9616-3acbfd365975.png)
Then I remembered to unblock Hearthstone Deck Tracker.exe (which was treated as suspicious since I downloaded the .zip).
This is the second time I've seen that warning in the past month. I remember my issues starting shortly after seeing it for the first time.
So I shut the tracker down fearing it would freeze up again and played a brawl on NA.
Switched to EU, turned the tracker on and played another ranked with no problems so far.

I'll update if 0.15.2 becomes unstable. Not sure if others have their .exe unblocked in Windows or are switching regions and using the same deck names.

**Comment by Epix37** [comment] 2016-06-30 10:12
#2642: 
> After a minute or two the problem disappeared. HDT didn't crash.

That is interesting.. So the GC *is* kicking in at some point - please try if it just kicks in automatically or if there is something specific that fixies it, like closing hearthstone, starting a game, minimizing HDT, ...

**Comment by F43nd1r** [comment] 2016-06-30 17:36
GC seems to be tied to a certain amount of RAM used. I always see it running at about 3GB. My actions have no influence on it.

**Comment by pefp2008** [comment] 2016-07-05 19:52
My problem began when i imported multiple decks (thanks a lot for that "new" function).
Today, i signed out from hearthstats and signed in again, and so far i haven't got any problem.

123mb RAM has been the highest so far. I'll keep updates if necessary.

**Comment by BigBuddha95** [comment] 2016-07-08 17:44
I am using HDT v0.15.6 on a win10 laptop with intel graphics. From time to time, totally randomly,(10 minutes or 2hours of use) HDT uses all my RAM, so hard that my laptop almost completely freezes, and makes me lose some games, because it's too laggy to do anything (no crash reports created). After visiting this thread, I logged out of Hearthstats, and I had no problem since! This is my first issue with HDT, thanks for this awesome tool !

**Comment by livejamie** [comment] 2016-07-13 04:27
Logging out and logging back in again doesn't seem to help the issue to me. 

Also getting the export freeze bug still.

Using the version released today.

**Comment by Sayaya** [comment] 2016-07-14 15:27
I had this problem for the first time today, right at the mulligan stage of a 5-2 arena match. HDT climbed from ~8% of RAM to ~62%, making the computer lag so hard just ending HDT took almost 15 minutes (lost the game, of course).

**Comment by azeier** [comment] 2016-08-28 16:37
This should be fixed with https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/507f823554df8d968086622841d25bc7b7cf5a7c and https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/fe6066d32d1259faca484ba3c625679af7b3cae0. 

The changes should be released in the hsreplay build within the next few days. I will post a download link here as well.

**Comment by azeier** [comment] 2016-08-30 09:20
Everyone having this issue: Please give the latest hsreplay build a shot. 

If you are not in the beta, you can get the installer here: https://hsdecktracker.net/download-hsreplay/

**Comment by riQQ** [comment] 2017-09-05 21:38
This is fixed and can be closed.

**Closed** 2017-09-05 22:30 UTC
Labels: bug, performance
