### ISSUE TITLE
How to sync HDT between two different PCs

### ISSUE THREAD

**Issue by speedytr** [HearthSim/Hearthstone-Deck-Tracker#2942] opened 2016-11-11 14:19 UTC
I just bought a new laptop. All my decks and stats are saved on my old laptop. Now I want to sync my new laptops' HDT with my old Laptops' cause I will use them both and different places. Is there any way?
(laptops have very different specs for example one is 1366*768 other one is 3200*1800 resolution)

**Comment by judge2020** [comment] 2016-11-11 16:45
I'm pretty sure this is accomplish-able with hearthstats, here's how to enable and sync:

On old device, go into settings - enable advanced options (at the bottom) - settings - enable hearthstats menu

![img](http://i.imgur.com/OetdUzr.png)

In the new hearthstats menu, click login, Once HDT restarts, either login or create a new account.

Now in the hearthstats menu do "force full sync", choose to upload the decks. 

Now on the new laptop, install HDT, do the same thing with enabling hearthstats and log into it.

Do a full sync, it will prompt you to download your decks.


Now if you'd rather not do that, you can also simply copy the decks and information. you can install HDT on the new device and copy `%appdata%\HearthstoneDeckTracker` from old one to the new one at the same location. Make sure HDT isn't open in the process.

**Comment by speedytr** [comment] 2016-11-12 03:56
Thx for your reply. I tried using hearthstats (I'm already a member) and decks synced but stats wouldn't come. Can I use somekind of cloud backup system maybe? Will different configurations effect cloud synced HDT folder?

**Comment by NikolaiAlexanderHimlan** [comment] 2016-11-25 17:59
I don't know why it's missing from the previous response, but there should be an option for "Save config/data in AppData".  If you uncheck those options (then restart HDT for safety) you can just copy the HDT directory to your new computer, everything will be as it was on your old computer. (Assuming Hearthstone is installed in the same location.  HDT will also have to re-enable logging for Hearthstone so don't worry if it doesn't start tracking immediately, just restart Hearthstone.)

![image](https://cloud.githubusercontent.com/assets/5479232/20632886/c3a43766-b30e-11e6-8859-655612c57cac.png)

**Comment by speedytr** [comment] 2016-11-27 06:36
Thx for your answer but If I do this it will also copy window settings (resolution position etc.) right?

**Comment by azeier** [comment] 2016-11-27 12:04
Those are stored in the config, leaving `save config in appdata` checked should get you what you are looking for.

**Comment by sakdarkside** [comment] 2017-03-17 02:30
This doesn't work anymore, since the AppData configs don't exist now. Any alternative?

![image](https://cloud.githubusercontent.com/assets/24964745/24026529/826f5c28-0aa0-11e7-890a-77b79773d3b0.png)

**Comment by azeier** [comment] 2017-03-17 12:05
You can use the HDT portable build ([download here](https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases/latest)) to do this still.

**Comment by NikolaiAlexanderHimlan** [comment] 2017-04-03 14:36
What portable build, there is only the core build and the source downloads.  I would love to have a portable build again.

You can still move it by moving the appdata folder, you just have to remember to put the appdata folder back on the new computer, you can't just conveniently have it all in one place anymore.  I've been really annoyed with this change and have used junctions to keep the appdata in the HDT folder using this command (which can be saved as a .bat file):
`mklink /J "%AppData%\HearthstoneDeckTracker" "%cd%\HDT_AppData"`
to link the HDT_AppData folder with the actual AppData so HDT works again.  (Just make sure there isn't an appdata folder already and delete it if there is.)

**Comment by judge2020** [comment] 2017-04-03 16:09
The core build is portable, the installer is hosted only on the website. You should be able to use the portable build and turn off appdata saves

**Comment by judge2020** [comment] 2017-06-10 04:10
closed in favor of #3235

**Closed by judge2020** 2017-06-10 04:10 UTC

**Comment by judge2020** [comment] 2017-07-19 20:49
duplicate of #3235
