### ISSUE TITLE
How to save my decks and history when i reinsall windows.Where all informaation located?

### ISSUE THREAD

**Issue by ZergShadow** [HearthSim/Hearthstone-Deck-Tracker#2938] opened 2016-11-10 01:48 UTC
How to save my decks and history when i reinsall windows.Where all informaation located?

**Comment by riQQ** [comment] 2016-11-10 07:16
Your data is stored in `%AppData%/HearthstoneDeckTracker`.

**Comment by judge2020** [comment] 2017-06-10 04:12
closed in favor of #3235

**Closed by judge2020** 2017-06-10 04:12 UTC

**Comment by judge2020** [comment] 2017-07-19 20:49
duplicate of #3235
