### ISSUE TITLE
HDT Constant Crashes

### ISSUE THREAD

**Issue by 305jeff** [HearthSim/Hearthstone-Deck-Tracker#3289] opened 2017-06-10 02:36 UTC
Hey guys - just had some repeated crashing and figured the logs files might help find a bug. I played 3 games and HSDT crashed when I entered each match. I would then close it and reload and play the game. For some reason after the 3rd match it crashed when I won the game.

Attached are the 4 different HSDT logs. It wouldn't let me attach the event viewer log file so here's the copy paste of the .net runtime and application error filtered items. Each of these are repeated a few times but it's very similar each time so I'm only pasting one of each type.

Faulting application name: HearthstoneDeckTracker.exe, version: 1.3.5.3102, time stamp: 0x59328f01
Faulting module name: KERNELBASE.dll, version: 10.0.15063.296, time stamp: 0x28e9cf15
Exception code: 0xe0434352
Fault offset: 0x000eb802
Faulting process id: 0x2d94
Faulting application start time: 0x01d2e189c444a33e
Faulting application path: C:\Users\Jeff\AppData\Local\HearthstoneDeckTracker\app-1.3.5\HearthstoneDeckTracker.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 0189e4fa-8c30-4b8b-b6e4-34dec66aa4b4
Faulting package full name: 
Faulting package-relative application ID: 

Application: HearthstoneDeckTracker.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OutOfMemoryException

Thanks!
[hdt_log_1497059548.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1065549/hdt_log_1497059548.txt)
[hdt_log_1497058603.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1065550/hdt_log_1497058603.txt)
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1065552/hdt_log.txt)
[hdt_log_1497061481.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1065551/hdt_log_1497061481.txt)

**Comment by riQQ** [comment] 2017-07-26 06:37
Looks similar to #3054.

**Comment by riQQ** [comment] 2017-09-09 09:26
Duplicate of #3054.

**Closed by riQQ** 2017-09-09 09:26 UTC
Labels: crash
