### ISSUE TITLE
Holy Wrath not listed as a card for arena awards

### ISSUE THREAD

**Issue by AndySweet** [HearthSim/Hearthstone-Deck-Tracker#3408] opened 2017-09-04 04:52 UTC
### Expected Behavior
In Arena Rewards screen, type in Holy Wrath as the name of card in the reward.  Expected to auto-complete and accept that card.

### Actual Behavior
No Auto-complete, and after typing card and trying to save, got error, in valid card name.

**Comment by jleclanche** [comment] 2017-09-04 05:06
Duplicate of #3394.

**Closed by jleclanche** 2017-09-04 05:06 UTC
Labels: duplicate
