### ISSUE TITLE
Records practice with option unselected

### ISSUE THREAD

**Issue by ViezeVingertjes** [HearthSim/Hearthstone-Deck-Tracker#3102] opened 2017-02-06 07:20 UTC
## Bug report
The main screen shows a percentage and w/l with included practice sessions if you play them with a known deck. Also shows in the stats matches (as practice), but should not be there, as i have both record / replay recording off in the settings.

### Expected Behavior
No logging of practice sessions.

### Actual Behavior
Logs practice sessions anyway.

### Steps to reproduce behavior
- Tick off practice sessions in the settings.
- Play practice match, i played solo against Lady Na'jar with my normal deck, but this should not be relevant.

**Comment by riQQ** [comment] 2017-09-30 00:30
Duplicate of #3271

**Closed by riQQ** 2017-09-30 00:30 UTC
Labels: bug, stats
