### ISSUE TITLE
deck tracker not recording wins and losses

### ISSUE THREAD

**Issue by indieguy** [HearthSim/Hearthstone-Deck-Tracker#3588] opened 2018-03-13 19:37 UTC
Deck tracker did not record my wins and losses yesterday. I've only tried reinstalling and changing HS path

![6uk](https://user-images.githubusercontent.com/37325099/37365621-68856d7e-26d4-11e8-9872-8b7d28618684.PNG)

**Comment by Zawodowiec1532** [comment] 2018-03-13 19:53
Hmm, duplicate of #3585 ?

> Make sure you're on hearthstone 10.4.0 and try restarting both.

**Closed** 2018-03-13 19:54 UTC
Labels: duplicate
