### ISSUE TITLE
Hidden Cache not clearing when minion played

### ISSUE THREAD

**Issue by pdman13** [HearthSim/Hearthstone-Deck-Tracker#3374] opened 2017-08-16 19:22 UTC
## Bug report
Playing a game as priest against hunter, he played secrets, I played a minion and in the overlay Hidden Cache was not marked as tested for like Snipe was.

### Expected Behavior
Hidden Cache is darkened to mark that the secret is not Hidden Cache.

### Actual Behavior
Hidden Cache did not get darkened.

### Steps to reproduce behavior
Should be reproducable by playing against a hunter, having them play a secret, then playing a minion.

**Comment by judge2020** [comment] 2017-08-16 20:03
Duplicate of #2987

The synopsis is that HDT can't absolutely know if the opponent has a minion in their hand, which is required for Hidden Cache to trigger.

**Closed by judge2020** 2017-08-16 20:03 UTC
