### ISSUE TITLE
Activating The Mistcaller's battlecry does not properly increment HDT's C'thun counter

### ISSUE THREAD

**Issue by mkolas** [HearthSim/Hearthstone-Deck-Tracker#2441] opened 2016-04-30 14:56 UTC
Managed to Burgle The Mistcaller just now, and although it does +1/+1 C'Thun as the card says the tracker doesn't count it.

**Comment by astradamus** [comment] 2016-05-22 03:35
Do C'Thun conditionals account for Mistcaller's buff if C'Thun is in your deck? I.E. If you play Dark Arrakoa -> Mistcaller -> Ancient Shieldbearer, do you gain 10 armor? My guess is no, and if that's the case, it stands to reason that the counter shouldn't respect Mistcaller's buff unless C'Thun is in hand or in play (at which point we know that the buff is respected, see: https://www.youtube.com/watch?v=cSVvBFHsoLs).

**Comment by mkolas** [comment] 2016-05-23 15:40
Yet, it looks like you're right- I wasn't aware how tricky The Mistcaller's implementation was. Especially with the new _Wherever It Is_ mechanic with C'Thun, it feels super lazy to continue to let the card text and the in-game function be so drastically different.

I do think that the counter should trigger a +1 once you draw C'Thun, however. It's a bit strange to see the number in your hand and the number on the counter to be misaligned.

**Comment by astradamus** [comment] 2016-05-23 15:56
Yeah, culinko tested and confirmed that C'Thun conditionals don't respect the MC buff unless C'Thun is in hand or play  (since the buff is not placed on cards in the deck but rather placed on them as they are drawn from it). The "proxy C'Thun" in setaside doesn't the buff, which is what gets checked when CThun isn't in hand/play. I would consider that a bug. That said I think you're definitely right, as long as C'Thun IS affected by the buff the counter should be updated accordingly because in that case it does affect his behavior and that of his buddies.

**Comment by astradamus** [comment] 2016-05-23 16:03
Uh I wanted to edit my comment but now I can't see the two latest posts, so I'll just shoehorn this in here presuming they'll reappear: not only does MC not update cards in the deck directly, but it appears extremely unlikely that CThun conditionals even examine the cards in the deck even if it did. After all that's the entire purpose of proxy-cthun.

**Comment by mkolas** [comment] 2016-05-23 16:10
Yeah, that all makes sense now that I've got the technical details on C'Thun and MC. Although there's absolutely precent on knowing technical mechanics in other genres, it seems so weird that players need to understand the precise details of Blizzard's implementation to figure out card interactions- see Entomb on a full board for example.

**Comment by culinko** [comment] 2016-05-23 17:53
Entomb on a full board was a bug and it has been fixed since.

**Comment by riQQ** [comment] 2019-03-05 07:55
Closing as this is not a bug

**Closed by riQQ** 2019-03-05 07:55 UTC
Labels: invalid
