### ISSUE TITLE
tracking turn

### ISSUE THREAD

**Issue by Bloodtooth** [HearthSim/Hearthstone-Deck-Tracker#3804] opened 2018-10-20 00:34 UTC
It could be wonderful if there were an actual counter for which turn we were on. Then I more specifically can see i perspective, when my opponent drew his cards. This can be hard to tell when my opponent drew his cards after his/hers manatotal goes above 10 mana or even boost his max mana crystals.

**Comment by riQQ** [comment] 2018-10-20 00:55
Duplicate of #1506

**Closed by riQQ** 2018-10-20 00:55 UTC
