### ISSUE TITLE
Randomly stops working

### ISSUE THREAD

**Issue by bluesh34** [HearthSim/Hearthstone-Deck-Tracker#3712] opened 2018-06-28 12:03 UTC
It just randomly stops working.  No idea why.  I see my deck list and that's it.  No record of which cards I've played and which are left or of cards opponent has played.  No times.  This issue only started recently.  This app is bugged as hell for me as of like 1 or 2 days ago.  You guys just made some changes or something?  If so, it's even worse than before (unless the problem is with my pc) and it wasn't even performing that well before.  Nice app when it decides to work though.

**Comment by riQQ** [comment] 2018-08-08 18:56
Please provide the HDT log corresponding to this problem. See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues#hdt-log-files.

**Comment by ElektroStudios** [comment] 2018-08-09 13:16
Yes I have the exact problem, then now I can confirm it happens to all users and not only me...

https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/3758

**Comment by riQQ** [comment] 2018-11-29 23:48
Duplicate of #374

**Closed by riQQ** 2018-11-29 23:48 UTC
