### ISSUE TITLE
Cards occasionally appear in non-mana order on deck overlay

### ISSUE THREAD

**Issue by sdlorimor** [HearthSim/Hearthstone-Deck-Tracker#3397] opened 2017-08-28 21:08 UTC
### Expected Behavior
Cards normally appear in order by the amount of mana .

### Actual Behavior
On rare occasion cards appear in incorrect order.  The mis-order is always one card (or at least one mana) one off from the correct location for the card.  This does not affect any other functionality of the deck tracker.  See screenshot.

### Steps to reproduce behavior
Not intentionally, but if I play enough games I'll notice it happening.  It does not appear to be limited to a certain card or cards.

### Update
Update: Turns out I had mulligan'ed Eater of Secrets.

Game: https://hsreplay.net/replay/TQ7QxvvbQrGZ9tZ94usRWM

### Log/Screenshots
![order](https://user-images.githubusercontent.com/22522645/29793794-4b1ccef0-8c13-11e7-937d-f5d1d449c643.jpg)

**Comment by riQQ** [comment] 2017-08-28 21:41
Does this only happen when playing in no deck mode?

**Comment by sdlorimor** [comment] 2017-08-28 22:22
If it occurs in no-deck mode I haven't noticed it -- I rarely use no-deck mode.  I have my interface set to remove cards from the deck overlay as I draw them.

**Comment by sdlorimor** [comment] 2017-08-28 22:22
It's worth noting I've been noticing this behavior for months now, so this isn't a new bug.  It doesn't occur often.  I notice it every few days or so.

**Comment by sdlorimor** [comment] 2017-08-30 21:32
It happened again.  It occurred immediately after I cast Entomb upon my opponent's Raza the Chained.  In the first screenshot I linked I hadn't yet cast Entomb (and hadn't yet used Shadow Visions to get a copy of it), so I dunno how related Entomb is.  Either way, there's clearly a rare bug occurring somewhere.

![order2](https://user-images.githubusercontent.com/22522645/29895926-f81f0c30-8da8-11e7-9ded-862999e31453.jpg)

**Comment by sdlorimor** [comment] 2017-09-01 16:57
Now that I'm looking for it I've been seeing it a lot lately.  At least 7-8 times in the past 24 hours.  I could inundate you with screenshots, but you'd rather useful data.  So here's something of note: it occurred immediately after the mulligan.  The four cards I handed back in the mulligan were: Azure Drake, The Lich King, Shadow Word: Death, and Northshire Cleric.  You can see the mulligan/game here:

https://hsreplay.net/replay/SaYVbmaE2tLHuYJTHjJxdV

I'll keep testing and see if I can decipher any rhyme or reason for the misordering.  I'm starting to notice certain patterns.  I've never seen it happen at 1-3 value, for example.

![order3](https://user-images.githubusercontent.com/22522645/29979736-b32df718-8f14-11e7-8ed5-c0bb6f68e738.jpg)

**Comment by sdlorimor** [comment] 2017-09-07 12:12
It happened again yesterday. I noticed it on turn 2.  It's worth noting I had just Mulligan'ed Velen, although whether or not that's a coincidence is unclear.

![order4](https://user-images.githubusercontent.com/22522645/30162494-008746d0-93a3-11e7-9a8e-385062f20c7d.jpg)

**Comment by riQQ** [comment] 2017-09-07 17:08
It would explain that this doesn't happen often for cards with Mana costs of 0-3, if it is caused by mulliganed cards.

**Comment by sdlorimor** [comment] 2017-09-07 19:21
The fact that the bug occurred immediately after a mulligan (see one of my examples above) suggests the mulligan is involved.  I"ll start providing links to the games themselves, so we can investigate this a bit more.

**Comment by sdlorimor** [comment] 2017-09-08 07:34
Another screenshot.  Here's the game from which it occurred:

https://hsreplay.net/replay/jpW4zgBcLaqiD3DQjUjXN8

I grabbed the screenshot immediately as the mulligan ended -- the screen is still dark and you can see the coin appearing.  Sure enough, I returned Dragonfire Potion to my deck during the mulligan.

It's worth noting that now that I'm checking my order I'm noticing this occur a lot more often.  It's occurring in more games than the few from which I'm grabbing screenshots.

Since the bug can occur immediately after the mulligan phase or casting Entomb, I'm guessing it occurs when cards are shuffled into your deck.  I can't explain why it doesn't appear to happen with low-cost cards.  I do mulligan them back fairly often.  Probably a side effect of the bug itself.

![order5](https://user-images.githubusercontent.com/22522645/30200733-23f684d4-9446-11e7-80fd-d50f39e64522.jpg)

**Comment by sdlorimor** [comment] 2017-09-09 19:01
It happened again.  And sure enough, it involved a card I mulligan'ed (Velen).  Clearly it has to do with mulliganing cards, although I suspect Entomb (or other shuffle into your deck functions) may trigger it as well.)

Is there anything in particular about this bug you want me to look for / report?

Game here: https://hsreplay.net/replay/n7np6cVLayFTasbNgkjpri

![order6](https://user-images.githubusercontent.com/22522645/30243011-a3f52bf2-956f-11e7-8da8-f77dacaa4657.jpg)

**Comment by sdlorimor** [comment] 2017-09-10 08:04
Was looking back at the original images from which my screenshots were based and comparing them to the games in question.  Sure enough, in the story for the second screenshot in which Lightbomb was out of order, I had mulligan'ed it.

At this point I'll stop providing commentary on the issue unless I discover something new to report.  It's clearly happens from both mulligans and from casting Entomb, so it's likely a bug resulting from anything that involves cards being reshuffled into a deck.  Not sure why it doesn't affect low value cards; it's likely a quirk resulting from the bug.

**Comment by riQQ** [comment] 2017-09-15 17:29
Duplicate of #2649.

**Comment by riQQ** [comment] 2017-09-20 18:20
![20170919_171208](https://user-images.githubusercontent.com/3404787/30660464-25a0d64a-9e41-11e7-82b7-ff8badfc9119.jpg)

**Comment by sdlorimor** [comment] 2017-11-23 20:58
Just an FYI this bug can affect two cards returned during the mulligan.

![bug](https://user-images.githubusercontent.com/22522645/33188334-170ecb16-d067-11e7-8335-46b2f007a9ac.jpg)

**Comment by Zawodowiec1532** [comment] 2017-11-24 02:00
Can you check/confirm that only occurs with selected option?
`Options -> Player -> Remove cards if none remaining`

**Comment by sdlorimor** [comment] 2017-12-04 07:44
I unchecked the box a week ago and haven't noticed the ordering bug since.  

I'll continue playing with the box unchecked and let you know if I spot the error.

**Comment by riQQ** [comment] 2018-02-10 14:11
@sdlorimor Could you post a screenshot of your player overlay settings that cause this bug?

**Closed** 2018-02-10 19:58 UTC
Labels: UI, bug, overlay
