### ISSUE TITLE
[REQUEST] Sync local games with hsreply

### ISSUE THREAD

**Issue by barat** [HearthSim/Hearthstone-Deck-Tracker#3380] opened 2017-08-18 23:29 UTC
Hi,
I want to suggest one feature. 
HSReplays has an API so there are other apps, which can upload replay. Such specific app is Arcane Tracker (Android deck tracker). This makes our local stats out of sync with web.
Can you implement some kind of sync, which will import deck results missing locally?
Now we can add them manually (FAQ states how), but there are like 10 fields to fill, and if we have larger number of games to import then it's PITA ... moreover - we can't insert how many hours ago this game was  ...

**Comment by judge2020** [comment] 2017-08-18 23:43
Stats/past replay start sync is already a highly requested feature. See the thread below for more details.

Duplicate of #3235

**Closed by judge2020** 2017-08-18 23:43 UTC
