### ISSUE TITLE
Stuck on version 1.5.12

### ISSUE THREAD

**Issue by SjoerdKingma** [HearthSim/Hearthstone-Deck-Tracker#3724] opened 2018-07-10 12:55 UTC
## Bug report
I'm stuck on version 1.5.12. Updating through client fails and gives an error (see screenshot) and a message saying: "Update failed, please try to download manually".
I follow the instructions and after downloading, the installer installs Deck Tracker v1.5.12 instead of the most recent v1.6.8. 

So when I open this fresh installed V1.5.12,  it will give me another message saying a new version is available which it fails to download again and I get the same error again.

I'm stuck in this endless loop, help me please.

### Log/Screenshots
![1e66941c87](https://user-images.githubusercontent.com/3404787/42527515-2946d7d0-8479-11e8-9832-4306cc0c3a56.png)

**Comment by Zawodowiec1532** [comment] 2018-07-10 13:54
Can you check if you open manually HDT from: `C:\Users\UserName\AppData\Local\HearthstoneDeckTracker` its updated? Updating HDT before 1.5.14 will fail, because security protocol changed. It's possible that you have 2 versions of HDT atm.
Check this comment: https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/3660#issuecomment-399039612

**Comment by beheh** [comment] 2018-07-11 10:02
Duplicate of #3587.

**Closed** 2018-08-08 18:50 UTC
Labels: installation, support
