### ISSUE TITLE
Haven't been able to update HS Deck Tracker for a year

### ISSUE THREAD

**Issue by Yupppi** [HearthSim/Hearthstone-Deck-Tracker#3707] opened 2018-06-21 13:58 UTC
My problem is, when I start the deck tracker, the prompt to update to the new version pops up, but when I try to install it, I'll face an error message. Anyhow, the manual updating does work. The command prompt gives a following message (sorry for the command prompt being on finnish OS):

![deck tracker 1](https://user-images.githubusercontent.com/24705202/41723608-2f5cb1da-7574-11e8-9680-717c2b9fd8d0.PNG)

![deck tracker 2](https://user-images.githubusercontent.com/24705202/41723617-3302fa88-7574-11e8-87dd-e86bdd37a3c7.PNG)

It's a problem with downloading the update? If I try to launch the HDTUpdate.exe manually, it just flashes the command prompt and closes. Maybe firewall? But I don't know how to allow the updater from the firewall because it's the software's prompt opening a new thing. I tried to allow the updater in multiple ways but it didn't change the outcome.

**Comment by jleclanche** [comment] 2018-06-21 15:55
I'm seeing TLS issues. That indeed sounds like it could be firewall/antivirus interfering. Have you tried temporarily disabling the firewall and seeing if it's still happening? If it does then it's something else.

You could also have the firewall whitelist hsdecktracker.net, githubusercontent.com and amazonaws.com. That might help.

**Comment by Yupppi** [comment] 2018-06-21 16:30
Got the same result with firewall disaled and after allowing the three domains (even though I don't think they were blocked by the firewall).

**Comment by riQQ** [comment] 2018-06-21 16:45
Duplicate of #3587

**Comment by Yupppi** [comment] 2018-06-21 17:21
Thanks, it did work. Will it keep working in the future or will I have to do this every time since installing the new version never worked automatically?

**Comment by riQQ** [comment] 2018-06-21 18:35
The new version is fixed and should update correctly.

**Closed by riQQ** 2018-06-21 18:35 UTC
