### ISSUE TITLE
Add a button to show opponent's deck in the replay viewer

### ISSUE THREAD

**Issue by GaryKing** [HearthSim/Hearthstone-Deck-Tracker#2522] opened 2016-05-21 20:58 UTC
Please add a button to show the opponent's deck in the replay viewer. Because if I go to Latest Replay, then there's no way to view the opponent's deck from there.

**Comment by culinko** [comment] 2016-06-22 01:49
Duplicate of #1990.

**Closed** 2016-06-22 02:14 UTC
