### ISSUE TITLE
Add HTTP proxy support

### ISSUE THREAD

**Issue by Binori** [HearthSim/Hearthstone-Deck-Tracker#895] opened 2015-04-14 14:02 UTC
Hi, 

Please add HTTP proxy support to application to be able fetch decks from the web and updates while behind the web proxy.

It would be nice feature for all who are in work ;) behind www proxy.
Thank you for your work and great app!

Greetings!

**Comment by Epix37** [comment] 2015-04-14 19:20
For the time being, may I suggest [NetDeck](http://netdeck.n4ru.it/) ? :)

**Comment by Binori** [comment] 2015-06-10 09:43
I don't like Chrome, love FF.

I spotted today "weird" behaviour. HDT updated through proxy without problem. So why the problem is to import deck from internet? Weird ;)

**Comment by riQQ** [comment] 2019-05-24 22:16
Duplicate of #3825

**Closed by riQQ** 2019-05-24 22:16 UTC
Labels: feature request
