### ISSUE TITLE
Tracker can't write results of games

### ISSUE THREAD

**Issue by Ph0en1xx** [HearthSim/Hearthstone-Deck-Tracker#3591] opened 2018-03-14 06:24 UTC
Since 12 of march, my tracker has problem with stats of my games. [None] at all games which i play.
What's problem with?
![image](https://user-images.githubusercontent.com/37360645/37386393-6d4e9034-2782-11e8-8bea-67eccf7aeeef.png)
**

**Comment by riQQ** [comment] 2018-03-14 07:16
Duplicate of #3585

**Closed by riQQ** 2018-03-14 07:16 UTC
