### ISSUE TITLE
Detecting/selecting wrong version of deck

### ISSUE THREAD

**Issue by TemporalOnline** [HearthSim/Hearthstone-Deck-Tracker#2326] opened 2016-04-08 21:25 UTC
This has happened 2 or three times, since 0.14 it is auto-selecting the correct deck, or should I say, the correct set which contains the deck version I am playing with, but it selects the wrong version of the deck (usually the v1.0 of that set).

If I select the correct version of the deck (usually it is the last one, but sometimes it is not) it stays correctly selected until it forgets again.

**Comment by wodorost** [comment] 2016-04-10 18:43
Got for the last week every day a wrong deck version, which ended to be so distrackting, because of the Tracker trying to rebuild the oponents played cards constantly and flashing errors. I mean it is ok when things break, but they shouldn't do it in such egotic manner.

Why is there no security switch 
<if deck does not fit, 
switch off the overlay 
and let me just play old school>

**Comment by Epix37** [comment] 2016-04-10 18:49
You can turn off auto deck detection at the bottom of the deck picker.

**Comment by wodorost** [comment] 2016-04-10 18:51
but the auto mode is the whole point of the tracker! Of course I can turn it off - or just go back to Excel sheets... :D

**Comment by Epix37** [comment] 2016-04-10 18:52
Auto deck detection means it automatically tries to switch to the correct deck.

**Comment by Epix37** [comment] 2016-04-10 18:53
Could you post a log of this happening? See here: https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by wodorost** [comment] 2016-04-10 18:53
The problem is not that he chooses the wrong deck.

HDT chooses the wrong version of a deck, so switching the auto mode does not help (besides of the reasoning above)

**Comment by wodorost** [comment] 2016-04-10 18:55
log - can not do. As I described I switched to the competition (not so good but robust) and deleted HDT (my bad, sorry)

**Comment by Epix37** [comment] 2016-04-10 19:26
@TemporalOnline (and @wodorost, if you want ;)) Try [this release](https://github.com/Epix37/HDT-Test/releases/tag/v0.14.1.2) and let me know if that fixes it. 

I fixed the only issue related to auto deck switching and versions I could find. Lets hope that's the one.

**Comment by Epix37** [comment] 2016-05-05 09:43
Should be fixed with v0.14.4

**Closed by Epix37** 2016-05-05 09:43 UTC
Labels: bug, decktracker
