### ISSUE TITLE
Deck tracker crash on match start/opponent found

### ISSUE THREAD

**Issue by darius07** [HearthSim/Hearthstone-Deck-Tracker#3576] opened 2018-03-04 15:25 UTC
[hdt_log_1520177223.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1778639/hdt_log_1520177223.txt)
[hdt_log_1520175986.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1778640/hdt_log_1520175986.txt)

## Bug report
Crash on match start/opponent found

### Expected Behavior
Not to crash

### Actual Behavior
Crash on match start/mulligan phase

### Steps to reproduce behavior
Play a wild ranked game

### Log/Screenshots
[Application Error]
Faulting application name: HearthstoneDeckTracker.exe, version: 1.5.12.3484, time stamp: 0x5a7a1c64
Faulting module name: KERNELBASE.dll, version: 10.0.16299.248, time stamp: 0x13ae3814
Exception code: 0xe0434352
Fault offset: 0x001008c2
Faulting process id: 0x24c0
Faulting application start time: 0x01d3b3ca5b3936fe
Faulting application path: C:\Users\InsignisPro\AppData\Local\HearthstoneDeckTracker\app-1.5.12\HearthstoneDeckTracker.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 675a1677-64c0-4425-9e39-07f7bb10912a
Faulting package full name: 
Faulting package-relative application ID: 

[.NET Runtime]
Application: HearthstoneDeckTracker.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OutOfMemoryException
   at MS.Internal.PresentationCore.SafeSecurityHelper.CleanupCollectedAssemblies(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by riQQ** [comment] 2018-03-04 16:31
Duplicate of #3054

**Closed by riQQ** 2018-03-04 16:31 UTC
