### ISSUE TITLE
Daily win tracker

### ISSUE THREAD

**Issue by rakudeb** [HearthSim/Hearthstone-Deck-Tracker#3819] opened 2018-11-10 10:11 UTC
The daily win tracker on the main menu is not working anymore since the last update earlier this week.

**Comment by riQQ** [comment] 2018-11-10 10:39
Duplicate of #3816

**Closed by riQQ** 2018-11-10 10:39 UTC

**Comment by rakudeb** [comment] 2018-11-10 10:45
Aah I suck so much at searching, I swear I spent like 10 minutes wondering if it was just me because I couldn't find any recent post of this problem. Thanks for the help, keep going ! Cheers.

**Comment by riQQ** [comment] 2018-11-10 10:52
No worries, for the next time: usually opening the closed issues and checking the last 10 should be enough to find a recent issue.
