### ISSUE TITLE
[dev][BG] API for BattleTags or Names of opponents

### ISSUE THREAD

**Issue by CeH9** [HearthSim/Hearthstone-Deck-Tracker#4322] opened 2021-07-11 17:55 UTC
Would be nice to have API to get Opponents' names or battletag (if possible) for Battlegrounds.

![image](https://user-images.githubusercontent.com/7687412/125205163-97328700-e289-11eb-9822-04c9de1a5f0d.png)

Currently, **GameV2** has only field "Opponent" that returns "Bob's Tavern" or null as Name.

**Comment by beheh** [comment] 2024-02-18 13:41
Duplicate of #4264.

**Closed by beheh** 2024-02-18 13:41 UTC
