### ISSUE TITLE
Friendly Encounters are breaking HDT

### ISSUE THREAD

**Issue by abrownhearth** [HearthSim/Hearthstone-Deck-Tracker#3925] opened 2019-06-06 22:49 UTC
In Dalaran Heist when going to a friendly encounter (Bob the Bartender), customer reported that when a card is modified the deck tracker no longer detects it and fails.

**Comment by riQQ** [comment] 2019-06-10 16:17
Duplicate of #3917

**Closed by riQQ** 2019-06-10 16:17 UTC
