### ISSUE TITLE
HDT thinks the seson resets at 12am local time.

### ISSUE THREAD

**Issue by stevenll** [HearthSim/Hearthstone-Deck-Tracker#3873] opened 2019-03-01 08:46 UTC
### Expected Behavior
I live in the eastern timezone of the united states. I expected HDT to start the new season at 3:00 am local time on 3/1 because the Americas Hearthstone server resets at 12 PDT, which is 3:00 am eastern
### Actual Behavior
In fact it reset the season at 12:00, and started registering my games against the new season before it had really started. It seems to reset at 12:00 _local time_ no matter where you are. This is wrong.

### Steps to reproduce behavior
Play a game after 12 in any timezone ahead of PDT.

**Comment by riQQ** [comment] 2019-03-02 01:08
Duplicate of #2786

**Closed** 2019-06-18 19:01 UTC
Labels: duplicate
