### ISSUE TITLE
overlay issue with mixed screen

### ISSUE THREAD

**Issue by psohm** [HearthSim/Hearthstone-Deck-Tracker#3471] opened 2017-11-05 10:28 UTC
When I have different resolution on my screen, the overlay appears on the 2/3 left of the screen. A screenshot will better explain it.

![image](https://user-images.githubusercontent.com/5886652/32413898-1d2a57e0-c21b-11e7-9a64-233e85aa7f7d.png)

This occurs only when I have a screen in 4K resolution and 1080p.
When I disable the first screen, the problem doesn't appear.

**Comment by riQQ** [comment] 2017-11-14 22:11
Is this the same as #3445?

**Comment by psohm** [comment] 2017-11-14 22:33
Hello
I'm not sure but it is possible that the cause is the same

In my case I use hs on a 4k screen and the right overlay appear on the main
screen but in the 2/3 left (about 2500 pixel from the left)

**Comment by riQQ** [comment] 2017-11-14 22:42
Does this happen too, if you disable your second screen in windows?

**Comment by psohm** [comment] 2017-11-15 08:07
No at the start of hs
The problem may disappear if I change two times the résolution

**Comment by SOLiNARY** [comment] 2017-11-23 16:41
Problem is when 2 screens have different resolutions & it takes the resolution of 2nd screen into account instead of 1st.
In my case overlay extends to 2nd screen as it has more reso than 1st.

**Comment by dominics** [comment] 2017-12-02 13:58
You might like to try [this workaround](https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/3445#issuecomment-348691225) in the meantime.

**Comment by beheh** [comment] 2024-04-11 20:08
Duplicate of #3445

**Closed by beheh** 2024-04-11 20:08 UTC
Labels: bug, overlay
