### ISSUE TITLE
HDT not displaying card on my side

### ISSUE THREAD

**Issue by ZA0068** [HearthSim/Hearthstone-Deck-Tracker#4539] opened 2024-04-10 17:09 UTC
### Expected Behavior

HDT should show cards on my side in both hands and deck.

HDT only shows what has my opponent shown in their play.

### Actual Behavior

It only shows my opponents card that had been played, but not mine, after i updated it.,

### Steps to reproduce behavior

Just update and run HDT, it wont show my deck at all

### Log/Screenshots

![image](https://github.com/HearthSim/Hearthstone-Deck-Tracker/assets/63291661/256389f2-077b-4e48-abae-8526b7a27efc)

**Comment by beheh** [comment] 2024-04-11 12:48
Duplicate of #3445

**Closed by beheh** 2024-04-11 12:48 UTC
Labels: bug
