### ISSUE TITLE
Tooltips are always shown and cant be disabled

### ISSUE THREAD

**Issue by HappyFolk** [HearthSim/Hearthstone-Deck-Tracker#4187] opened 2020-12-03 20:59 UTC
## Bug report

Tooltips are always shown in the bottom right corner when i hover a card and i'm not able to disable it. It doesn't seems to be an overlay tooltip, rather a heartstone ingame tootip, showing the artwork description from the collections view. That is a totally irrelevant information while being in a battle and consumes the already little amout of available free space on the screen.

I didn't find any related in open tickets. 
Thanks.

### Expected Behavior

If i disable either
Options > Overlay > General > Card Tooltips or
Options > Tracker > General > Card Tooltips
i want no tooltips in my application. 

### Actual Behavior

Artwork tooltip only dissapears if i uninstall deck tracker.

### Log/Screenshots

![hstooltip](https://user-images.githubusercontent.com/17132190/101087478-8fec2200-35b2-11eb-97da-d8df07b8bd6f.jpg)

**Comment by riQQ** [comment] 2020-12-03 22:14
Duplicate of #4186

**Closed by riQQ** 2020-12-03 22:14 UTC
