### ISSUE TITLE
Opponent card-age isn't lining up with their cards properly

### ISSUE THREAD

**Issue by Metalfear4** [HearthSim/Hearthstone-Deck-Tracker#3895] opened 2019-04-15 11:44 UTC
The card-age for my opponent is over to the right for each card and I have spent ages trying to fix it.  There is no way to drag it when unlocking the overlay (it doesn't move) and tried lots of resizing, zooming, changing resolution, etc.

Any advice? It is just happening to me for some reason...

![hs](https://user-images.githubusercontent.com/49643549/56130148-79511b80-5fc7-11e9-838d-1a9687e5c2a3.jpg)

**Comment by riQQ** [comment] 2019-04-21 22:52
Duplicate of #3445

**Closed by riQQ** 2019-04-21 22:52 UTC
