### ISSUE TITLE
Not saving decks

### ISSUE THREAD

**Issue by vhmbr** [HearthSim/Hearthstone-Deck-Tracker#2618] opened 2016-06-19 17:33 UTC
Hi there, i've been using HDT for a while, but last week this kinda bug started and i don't know what to do. Basically, when i make a new deck or edit one and then i restart the program, everything gets reset to this: http://i.imgur.com/jX8agOy.png
I know this is probably a stupid issue for some of you guys, but i'm not an expert at this things, and if anyone could help me, i'd appreciate a lot!

One more thing, i'm a brazilian and i don't know how to speak english very well, but i try!

**Comment by riQQ** [comment] 2016-06-19 19:39
What is reset? The layout?

**Comment by vhmbr** [comment] 2016-06-19 19:44
If i had created a deck, and then restarted the program, the deck would be deleted, and the stats would be reset to those in the printscreen.

**Comment by vhmbr** [comment] 2016-06-19 19:59
The window size, layout and position reset too!

**Comment by Epix37** [comment] 2016-06-20 07:44
This sounds like there's some permission problem. Try running HDT as admin.

**Comment by vhmbr** [comment] 2016-06-20 17:33
It didn't work, but thank you for helping. If you have any other advice, i'd be grateful!

**Comment by riQQ** [comment] 2017-11-14 22:58
Duplicate of #2552

**Closed by riQQ** 2017-11-14 22:58 UTC
