### ISSUE TITLE
showing all secrets instead of the available ones

### ISSUE THREAD

**Issue by zzddtt** [HearthSim/Hearthstone-Deck-Tracker#4511] opened 2023-11-10 04:39 UTC
### Expected Behavior

its supposed to show the secrets available in the current game mode

### Actual Behavior

its showing all secrets of the class in the standard mode

### Steps to reproduce behavior

opponent plays a secret

### Log/Screenshots

![image](https://github.com/HearthSim/Hearthstone-Deck-Tracker/assets/150413224/b5f3b25a-649a-436f-82a1-1afd8b5c24d4)

**Comment by beheh** [comment] 2023-11-15 23:13
Thanks for the report! This will be fixed shortly in HDT v1.23.1. It was caused by a switch to a new system to more accurately show the available secrets in all game modes and a bug that caused us to detect the wrong game format.

**Closed** 2023-11-15 23:13 UTC
Labels: bug
