### ISSUE TITLE
HS Deck Tracker crashes frequently and randomly while HS is running

### ISSUE THREAD

**Issue by eebster** [HearthSim/Hearthstone-Deck-Tracker#3104] opened 2017-02-12 08:48 UTC
I have been using this deck tracker for a few months, but suddenly in the last couple of days it has started crashing at random intervals. Specifically, it has crashed three times in the last hour, or perhaps even less time than that (after the third crash, I left it closed, so I didn't track the exact duration). Each time it was up for at least five minutes, but not more than twenty minutes. It only crashes while HS is running, and it just started recently, but otherwise I can't give many details. I am running Windows 10 on an old but up-to-date laptop with the most recent build and no other relevant applications running besides Hearthstone. When it crashes, Windows gives the standard error message and no further information. This has never happened before until late last night.

Let me know if any other info would be helpful.

**Comment by riQQ** [comment] 2017-02-12 09:11
https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues (HDT crash logs and Windows log files)

**Comment by eebster** [comment] 2017-02-12 14:24
This is the past week of logs.
[hdt_log_1486607953.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/769339/hdt_log_1486607953.txt)
[hdt_log_1486617464.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/769340/hdt_log_1486617464.txt)
[hdt_log_1486736637.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/769335/hdt_log_1486736637.txt)
[hdt_log_1486777323.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/769338/hdt_log_1486777323.txt)
[hdt_log_1486883050.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/769337/hdt_log_1486883050.txt)
[hdt_log_1486885100.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/769336/hdt_log_1486885100.txt)
[hdt_log_1486885668.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/769345/hdt_log_1486885668.txt)
[hdt_log_1486886940.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/769342/hdt_log_1486886940.txt)
[hdt_log_1486909134.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/769341/hdt_log_1486909134.txt)
[hdt_log_1486310771.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/769344/hdt_log_1486310771.txt)
[hdt_log_1486401689.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/769343/hdt_log_1486401689.txt)

**Comment by riQQ** [comment] 2017-02-12 14:32
Please reread my first post and provide the logs i asked for (HDT **crash** logs and **Windows log files**)

**Comment by eebster** [comment] 2017-02-12 14:47
The only folders in the HSDT directory are Backups, Logs, Plugins, and Replays, no Crash Reports. There are four Windows logs from Hearthstone, all from yesterday. I've uploaded them together in a single text file.

[Hearthstone Deck Tracker Windows Event Logs 2-12-17.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/769360/Hearthstone.Deck.Tracker.Windows.Event.Logs.2-12-17.txt)

**Comment by riQQ** [comment] 2017-02-12 15:08
Anything with source `.NET runtime`  in the windows event log?

**Comment by eebster** [comment] 2017-02-12 15:13
Yes, sorry about that.

[Hearthstone Deck Tracker WIndows NET Runtime Event Logs.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/769377/Hearthstone.Deck.Tracker.WIndows.NET.Runtime.Event.Logs.txt)

**Comment by riQQ** [comment] 2017-02-12 15:39
Okay, duplicate of #3054.

**Closed** 2017-02-14 14:53 UTC
Labels: duplicate
