### ISSUE TITLE
bug with Genn Greymane & Baku the Mooneater

### ISSUE THREAD

**Issue by zuoju2234** [HearthSim/Hearthstone-Deck-Tracker#3877] opened 2019-03-11 15:57 UTC
### Expected Behavior

not showing Baku the Mooneater in my opponent's hand
### Actual Behavior

Baku the Mooneater was shown in my opponent's hand
### Steps to reproduce behavior

your opponent mulligan his/her starting hand, and get a Baku; then you will see it from HDT
### Log/Screenshots

![image](https://user-images.githubusercontent.com/48447682/54137899-6e9be780-4459-11e9-95f1-6ab73877a9c5.png)

**Comment by zuoju2234** [comment] 2019-03-11 15:58
![image](https://user-images.githubusercontent.com/48447682/54137938-85dad500-4459-11e9-9d8a-051c6f3aa807.png)

**Comment by riQQ** [comment] 2019-03-11 21:22
Duplicate of #3627

**Closed by riQQ** 2019-03-11 21:22 UTC
