### ISSUE TITLE
Player Overlay option to continue to display created cards

### ISSUE THREAD

**Issue by Sheepherder226** [HearthSim/Hearthstone-Deck-Tracker#3791] opened 2018-09-12 14:14 UTC
## Bug report
Is there an option to continue to display created cards that did not start in the player's deck?  It would be very useful for decks that utilize Tess Greymane or other similar mechanics like Lynessa Sunsorrow, Shudderwock, Yogg-Saron, Hope's End, etc.  I believe this feature already exists as an option for the opponent's decklist.

### Expected Behavior

Create an option "Do not remove created cards once played" in the player's overlay options.  When this option is toggled on, a created card that is played continues to be visible in the player's decklist and is not removed.

### Actual Behavior

Currently there is only an option to "Include cards created in hand (e.g. The Coin)".  When this option is toggled on, created cards show up in the decklist but once played they are removed from the player's decklist.

### Steps to reproduce behavior

1. Make sure this option is toggled on: Options > Overlay > Player > Include cards created in hand (e.g. The Coin).
2. Play any card that adds a card to your hand (e.g. Hallucination). The card added to your hand shows up in the decklist.
3. Play the card that was added to your hand.  The card that was added to your hand gets removed from the decklist.

**Comment by riQQ** [comment] 2018-09-12 18:20
Duplicate of  #2499

**Closed by riQQ** 2018-09-12 18:20 UTC
