### ISSUE TITLE
Augmented Elekk reveals cards created by Academic Espionage

### ISSUE THREAD

**Issue by aalear** [HearthSim/Hearthstone-Deck-Tracker#3751] opened 2018-08-07 21:49 UTC
I believe cards added to my deck by [Academic Espionage](https://www.hearthpwn.com/cards/89859-academic-espionage) should be hidden. Otherwise I get an unfair advantage as someone using a tracker over someone who's not. Right now they're immediately shown in my deck. Screenshot of my rogue deck list after the card's been played vs a mage: 

![image](https://user-images.githubusercontent.com/361657/43804266-738a7eb8-9a69-11e8-9410-3bb36817dbd4.png)

**Comment by azeier** [comment] 2018-08-07 22:01
Well this is unexpected. Yes this should definitely not happen and will be fixed.

**Comment by azeier** [comment] 2018-08-07 22:15
![espionage](https://user-images.githubusercontent.com/7737910/43805445-94e4d0aa-9a54-11e8-92e6-7ef6730413ff.PNG)

I am not able to reproduce this. Can you provide a log for this? (See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues)

**Comment by azeier** [comment] 2018-08-07 22:18
Corresponding power.log:
```
D 15:13:22.0644579 PowerTaskList.DebugDump() - ID=145 ParentID=0 PreviousID=0 TaskCount=11
D 15:13:22.0649471 PowerTaskList.DebugPrintPower() - BLOCK_START BlockType=PLAY Entity=[entityName=Academic Espionage id=28 zone=HAND zonePos=1 cardId=BOT_087 player=1] EffectCardId= EffectIndex=0 Target=0 SubOption=-1 
D 15:13:22.0649471 PowerTaskList.DebugPrintPower() -     TAG_CHANGE Entity=Epix#2966 tag=RESOURCES_USED value=4 
D 15:13:22.0649471 PowerTaskList.DebugPrintPower() -     TAG_CHANGE Entity=Epix#2966 tag=NUM_RESOURCES_SPENT_THIS_GAME value=8 
D 15:13:22.0649471 PowerTaskList.DebugPrintPower() -     TAG_CHANGE Entity=Epix#2966 tag=NUM_CARDS_PLAYED_THIS_TURN value=1 
D 15:13:22.0649471 PowerTaskList.DebugPrintPower() -     TAG_CHANGE Entity=Epix#2966 tag=430 value=1 
D 15:13:22.0649471 PowerTaskList.DebugPrintPower() -     TAG_CHANGE Entity=[entityName=Knife Juggler id=20 zone=HAND zonePos=4 cardId=NEW1_019 player=1] tag=ZONE_POSITION value=3 
D 15:13:22.0649471 PowerTaskList.DebugPrintPower() -     TAG_CHANGE Entity=[entityName=Elven Minstrel id=18 zone=HAND zonePos=3 cardId=LOOT_211 player=1] tag=ZONE_POSITION value=2 
D 15:13:22.0649471 PowerTaskList.DebugPrintPower() -     TAG_CHANGE Entity=[entityName=Sap id=27 zone=HAND zonePos=2 cardId=EX1_581 player=1] tag=ZONE_POSITION value=1 
D 15:13:22.0649471 PowerTaskList.DebugPrintPower() -     TAG_CHANGE Entity=[entityName=Academic Espionage id=28 zone=HAND zonePos=1 cardId=BOT_087 player=1] tag=ZONE_POSITION value=0 
D 15:13:22.0649471 PowerTaskList.DebugPrintPower() -     TAG_CHANGE Entity=[entityName=Academic Espionage id=28 zone=HAND zonePos=1 cardId=BOT_087 player=1] tag=ZONE value=PLAY 
D 15:13:22.0649471 PowerTaskList.DebugPrintPower() -     TAG_CHANGE Entity=[entityName=Academic Espionage id=28 zone=HAND zonePos=1 cardId=BOT_087 player=1] tag=JUST_PLAYED value=1 
D 15:13:22.0649471 PowerTaskList.DebugPrintPower() -     TAG_CHANGE Entity=Epix#2966 tag=LAST_CARD_PLAYED value=28 
D 15:13:22.0649471 PowerTaskList.DebugDump() - Block End=(null)
D 15:13:22.0649471 PowerProcessor.PrepareHistoryForCurrentTaskList() - m_currentTaskList=145
D 15:13:22.0654523 PowerProcessor.DoTaskListForCard() - unhandled BlockType PLAY for sourceEntity [entityName=Academic Espionage id=28 zone=HAND zonePos=1 cardId=BOT_087 player=1]
D 15:13:22.0724691 PowerProcessor.EndCurrentTaskList() - m_currentTaskList=145
D 15:13:22.0860055 PowerTaskList.DebugDump() - ID=146 ParentID=145 PreviousID=0 TaskCount=50
D 15:13:22.0860055 PowerTaskList.DebugPrintPower() - BLOCK_START BlockType=POWER Entity=[entityName=Academic Espionage id=28 zone=PLAY zonePos=0 cardId=BOT_087 player=1] EffectCardId= EffectIndex=0 Target=0 SubOption=-1 
D 15:13:22.0860055 PowerTaskList.DebugPrintPower() -     FULL_ENTITY - Updating [entityName=UNKNOWN ENTITY [cardType=INVALID] id=78 zone=DECK zonePos=0 cardId= player=1] CardID=
D 15:13:22.0860055 PowerTaskList.DebugPrintPower() -         tag=ZONE value=DECK
D 15:13:22.0860055 PowerTaskList.DebugPrintPower() -         tag=CONTROLLER value=1
D 15:13:22.0860055 PowerTaskList.DebugPrintPower() -         tag=ENTITY_ID value=78
D 15:13:22.0860055 PowerTaskList.DebugPrintPower() -     FULL_ENTITY - Updating [entityName=UNKNOWN ENTITY [cardType=INVALID] id=79 zone=SETASIDE zonePos=0 cardId= player=1] CardID=
D 15:13:22.0860055 PowerTaskList.DebugPrintPower() -         tag=ZONE value=SETASIDE
D 15:13:22.0860055 PowerTaskList.DebugPrintPower() -         tag=CONTROLLER value=1
D 15:13:22.0860055 PowerTaskList.DebugPrintPower() -         tag=ENTITY_ID value=79
D 15:13:22.0865054 PowerTaskList.DebugPrintPower() -     TAG_CHANGE Entity=[entityName=UNKNOWN ENTITY [cardType=INVALID] id=79 zone=SETASIDE zonePos=0 cardId= player=1] tag=ZONE value=PLAY 
D 15:13:22.0865054 PowerTaskList.DebugPrintPower() -     TAG_CHANGE Entity=[entityName=UNKNOWN ENTITY [cardType=INVALID] id=78 zone=DECK zonePos=0 cardId= player=1] tag=DISPLAYED_CREATOR value=28 
D 15:13:22.0865054 PowerTaskList.DebugPrintPower() -     META_DATA - Meta=TARGET Data=0 Info=1
D 15:13:22.0865054 PowerTaskList.DebugPrintPower() -         Info[0] = [entityName=UNKNOWN ENTITY [cardType=INVALID] id=78 zone=DECK zonePos=0 cardId= player=1]
D 15:13:22.0865054 PowerTaskList.DebugPrintPower() -     FULL_ENTITY - Updating [entityName=UNKNOWN ENTITY [cardType=INVALID] id=80 zone=DECK zonePos=0 cardId= player=1] CardID=
D 15:13:22.0865054 PowerTaskList.DebugPrintPower() -         tag=ZONE value=DECK
D 15:13:22.0865054 PowerTaskList.DebugPrintPower() -         tag=CONTROLLER value=1
D 15:13:22.0865054 PowerTaskList.DebugPrintPower() -         tag=ENTITY_ID value=80
D 15:13:22.0865054 PowerTaskList.DebugPrintPower() -     FULL_ENTITY - Updating [entityName=UNKNOWN ENTITY [cardType=INVALID] id=81 zone=SETASIDE zonePos=0 cardId= player=1] CardID=
D 15:13:22.0865054 PowerTaskList.DebugPrintPower() -         tag=ZONE value=SETASIDE
D 15:13:22.0865054 PowerTaskList.DebugPrintPower() -         tag=CONTROLLER value=1
D 15:13:22.0865054 PowerTaskList.DebugPrintPower() -         tag=ENTITY_ID value=81
D 15:13:22.0865054 PowerTaskList.DebugPrintPower() -     TAG_CHANGE Entity=[entityName=UNKNOWN ENTITY [cardType=INVALID] id=81 zone=SETASIDE zonePos=0 cardId= player=1] tag=ZONE value=PLAY 
D 15:13:22.0865054 PowerTaskList.DebugPrintPower() -     TAG_CHANGE Entity=[entityName=UNKNOWN ENTITY [cardType=INVALID] id=80 zone=DECK zonePos=0 cardId= player=1] tag=DISPLAYED_CREATOR value=28 
D 15:13:22.0865054 PowerTaskList.DebugPrintPower() -     META_DATA - Meta=TARGET Data=0 Info=1
D 15:13:22.0865054 PowerTaskList.DebugPrintPower() -         Info[0] = [entityName=UNKNOWN ENTITY [cardType=INVALID] id=80 zone=DECK zonePos=0 cardId= player=1]
D 15:13:22.0865054 PowerTaskList.DebugPrintPower() -     FULL_ENTITY - Updating [entityName=UNKNOWN ENTITY [cardType=INVALID] id=82 zone=DECK zonePos=0 cardId= player=1] CardID=
D 15:13:22.0865054 PowerTaskList.DebugPrintPower() -         tag=ZONE value=DECK
D 15:13:22.0865054 PowerTaskList.DebugPrintPower() -         tag=CONTROLLER value=1
D 15:13:22.0865054 PowerTaskList.DebugPrintPower() -         tag=ENTITY_ID value=82
D 15:13:22.0865054 PowerTaskList.DebugPrintPower() -     FULL_ENTITY - Updating [entityName=UNKNOWN ENTITY [cardType=INVALID] id=83 zone=SETASIDE zonePos=0 cardId= player=1] CardID=
D 15:13:22.0865054 PowerTaskList.DebugPrintPower() -         tag=ZONE value=SETASIDE
D 15:13:22.0865054 PowerTaskList.DebugPrintPower() -         tag=CONTROLLER value=1
D 15:13:22.0865054 PowerTaskList.DebugPrintPower() -         tag=ENTITY_ID value=83
D 15:13:22.0865054 PowerTaskList.DebugPrintPower() -     TAG_CHANGE Entity=[entityName=UNKNOWN ENTITY [cardType=INVALID] id=83 zone=SETASIDE zonePos=0 cardId= player=1] tag=ZONE value=PLAY 
D 15:13:22.0865054 PowerTaskList.DebugPrintPower() -     TAG_CHANGE Entity=[entityName=UNKNOWN ENTITY [cardType=INVALID] id=82 zone=DECK zonePos=0 cardId= player=1] tag=DISPLAYED_CREATOR value=28 
D 15:13:22.0870388 PowerTaskList.DebugPrintPower() -     META_DATA - Meta=TARGET Data=0 Info=1
D 15:13:22.0870388 PowerTaskList.DebugPrintPower() -         Info[0] = [entityName=UNKNOWN ENTITY [cardType=INVALID] id=82 zone=DECK zonePos=0 cardId= player=1]
D 15:13:22.0870388 PowerTaskList.DebugPrintPower() -     FULL_ENTITY - Updating [entityName=UNKNOWN ENTITY [cardType=INVALID] id=84 zone=DECK zonePos=0 cardId= player=1] CardID=
D 15:13:22.0870388 PowerTaskList.DebugPrintPower() -         tag=ZONE value=DECK
D 15:13:22.0870388 PowerTaskList.DebugPrintPower() -         tag=CONTROLLER value=1
D 15:13:22.0870388 PowerTaskList.DebugPrintPower() -         tag=ENTITY_ID value=84
D 15:13:22.0870388 PowerTaskList.DebugPrintPower() -     FULL_ENTITY - Updating [entityName=UNKNOWN ENTITY [cardType=INVALID] id=85 zone=SETASIDE zonePos=0 cardId= player=1] CardID=
D 15:13:22.0870388 PowerTaskList.DebugPrintPower() -         tag=ZONE value=SETASIDE
D 15:13:22.0870388 PowerTaskList.DebugPrintPower() -         tag=CONTROLLER value=1
D 15:13:22.0870388 PowerTaskList.DebugPrintPower() -         tag=ENTITY_ID value=85
D 15:13:22.0870388 PowerTaskList.DebugPrintPower() -     TAG_CHANGE Entity=[entityName=UNKNOWN ENTITY [cardType=INVALID] id=85 zone=SETASIDE zonePos=0 cardId= player=1] tag=ZONE value=PLAY 
D 15:13:22.0870388 PowerTaskList.DebugPrintPower() -     TAG_CHANGE Entity=[entityName=UNKNOWN ENTITY [cardType=INVALID] id=84 zone=DECK zonePos=0 cardId= player=1] tag=DISPLAYED_CREATOR value=28 
D 15:13:22.0870388 PowerTaskList.DebugPrintPower() -     META_DATA - Meta=TARGET Data=0 Info=1
D 15:13:22.0870388 PowerTaskList.DebugPrintPower() -         Info[0] = [entityName=UNKNOWN ENTITY [cardType=INVALID] id=84 zone=DECK zonePos=0 cardId= player=1]
D 15:13:22.0870388 PowerTaskList.DebugPrintPower() -     FULL_ENTITY - Updating [entityName=UNKNOWN ENTITY [cardType=INVALID] id=86 zone=DECK zonePos=0 cardId= player=1] CardID=
D 15:13:22.0870388 PowerTaskList.DebugPrintPower() -         tag=ZONE value=DECK
D 15:13:22.0870388 PowerTaskList.DebugPrintPower() -         tag=CONTROLLER value=1
D 15:13:22.0870388 PowerTaskList.DebugPrintPower() -         tag=ENTITY_ID value=86
D 15:13:22.0870388 PowerTaskList.DebugPrintPower() -     FULL_ENTITY - Updating [entityName=UNKNOWN ENTITY [cardType=INVALID] id=87 zone=SETASIDE zonePos=0 cardId= player=1] CardID=
D 15:13:22.0870388 PowerTaskList.DebugPrintPower() -         tag=ZONE value=SETASIDE
D 15:13:22.0870388 PowerTaskList.DebugPrintPower() -         tag=CONTROLLER value=1
D 15:13:22.0870388 PowerTaskList.DebugPrintPower() -         tag=ENTITY_ID value=87
D 15:13:22.0875614 PowerTaskList.DebugPrintPower() -     TAG_CHANGE Entity=[entityName=UNKNOWN ENTITY [cardType=INVALID] id=87 zone=SETASIDE zonePos=0 cardId= player=1] tag=ZONE value=PLAY 
D 15:13:22.0875614 PowerTaskList.DebugPrintPower() -     TAG_CHANGE Entity=[entityName=UNKNOWN ENTITY [cardType=INVALID] id=86 zone=DECK zonePos=0 cardId= player=1] tag=DISPLAYED_CREATOR value=28 
D 15:13:22.0875614 PowerTaskList.DebugPrintPower() -     META_DATA - Meta=TARGET Data=0 Info=1
D 15:13:22.0875614 PowerTaskList.DebugPrintPower() -         Info[0] = [entityName=UNKNOWN ENTITY [cardType=INVALID] id=86 zone=DECK zonePos=0 cardId= player=1]
D 15:13:22.0875614 PowerTaskList.DebugPrintPower() -     FULL_ENTITY - Updating [entityName=UNKNOWN ENTITY [cardType=INVALID] id=88 zone=DECK zonePos=0 cardId= player=1] CardID=
D 15:13:22.0875614 PowerTaskList.DebugPrintPower() -         tag=ZONE value=DECK
D 15:13:22.0875614 PowerTaskList.DebugPrintPower() -         tag=CONTROLLER value=1
D 15:13:22.0875614 PowerTaskList.DebugPrintPower() -         tag=ENTITY_ID value=88
D 15:13:22.0875614 PowerTaskList.DebugPrintPower() -     FULL_ENTITY - Updating [entityName=UNKNOWN ENTITY [cardType=INVALID] id=89 zone=SETASIDE zonePos=0 cardId= player=1] CardID=
D 15:13:22.0875614 PowerTaskList.DebugPrintPower() -         tag=ZONE value=SETASIDE
D 15:13:22.0875614 PowerTaskList.DebugPrintPower() -         tag=CONTROLLER value=1
D 15:13:22.0875614 PowerTaskList.DebugPrintPower() -         tag=ENTITY_ID value=89
D 15:13:22.0875614 PowerTaskList.DebugPrintPower() -     TAG_CHANGE Entity=[entityName=UNKNOWN ENTITY [cardType=INVALID] id=89 zone=SETASIDE zonePos=0 cardId= player=1] tag=ZONE value=PLAY 
D 15:13:22.0875614 PowerTaskList.DebugPrintPower() -     TAG_CHANGE Entity=[entityName=UNKNOWN ENTITY [cardType=INVALID] id=88 zone=DECK zonePos=0 cardId= player=1] tag=DISPLAYED_CREATOR value=28 
D 15:13:22.0875614 PowerTaskList.DebugPrintPower() -     META_DATA - Meta=TARGET Data=0 Info=1
D 15:13:22.0875614 PowerTaskList.DebugPrintPower() -         Info[0] = [entityName=UNKNOWN ENTITY [cardType=INVALID] id=88 zone=DECK zonePos=0 cardId= player=1]
D 15:13:22.0875614 PowerTaskList.DebugPrintPower() -     FULL_ENTITY - Updating [entityName=UNKNOWN ENTITY [cardType=INVALID] id=90 zone=DECK zonePos=0 cardId= player=1] CardID=
D 15:13:22.0875614 PowerTaskList.DebugPrintPower() -         tag=ZONE value=DECK
D 15:13:22.0875614 PowerTaskList.DebugPrintPower() -         tag=CONTROLLER value=1
D 15:13:22.0875614 PowerTaskList.DebugPrintPower() -         tag=ENTITY_ID value=90
D 15:13:22.0875614 PowerTaskList.DebugPrintPower() -     FULL_ENTITY - Updating [entityName=UNKNOWN ENTITY [cardType=INVALID] id=91 zone=SETASIDE zonePos=0 cardId= player=1] CardID=
D 15:13:22.0875614 PowerTaskList.DebugPrintPower() -         tag=ZONE value=SETASIDE
D 15:13:22.0875614 PowerTaskList.DebugPrintPower() -         tag=CONTROLLER value=1
D 15:13:22.0875614 PowerTaskList.DebugPrintPower() -         tag=ENTITY_ID value=91
D 15:13:22.0875614 PowerTaskList.DebugPrintPower() -     TAG_CHANGE Entity=[entityName=UNKNOWN ENTITY [cardType=INVALID] id=91 zone=SETASIDE zonePos=0 cardId= player=1] tag=ZONE value=PLAY 
D 15:13:22.0875614 PowerTaskList.DebugPrintPower() -     TAG_CHANGE Entity=[entityName=UNKNOWN ENTITY [cardType=INVALID] id=90 zone=DECK zonePos=0 cardId= player=1] tag=DISPLAYED_CREATOR value=28 
D 15:13:22.0875614 PowerTaskList.DebugPrintPower() -     META_DATA - Meta=TARGET Data=0 Info=1
D 15:13:22.0875614 PowerTaskList.DebugPrintPower() -         Info[0] = [entityName=UNKNOWN ENTITY [cardType=INVALID] id=90 zone=DECK zonePos=0 cardId= player=1]
D 15:13:22.0875614 PowerTaskList.DebugPrintPower() -     FULL_ENTITY - Updating [entityName=UNKNOWN ENTITY [cardType=INVALID] id=92 zone=DECK zonePos=0 cardId= player=1] CardID=
D 15:13:22.0880429 PowerTaskList.DebugPrintPower() -         tag=ZONE value=DECK
D 15:13:22.0880429 PowerTaskList.DebugPrintPower() -         tag=CONTROLLER value=1
D 15:13:22.0880429 PowerTaskList.DebugPrintPower() -         tag=ENTITY_ID value=92
D 15:13:22.0880429 PowerTaskList.DebugPrintPower() -     FULL_ENTITY - Updating [entityName=UNKNOWN ENTITY [cardType=INVALID] id=93 zone=SETASIDE zonePos=0 cardId= player=1] CardID=
D 15:13:22.0880429 PowerTaskList.DebugPrintPower() -         tag=ZONE value=SETASIDE
D 15:13:22.0880429 PowerTaskList.DebugPrintPower() -         tag=CONTROLLER value=1
D 15:13:22.0880429 PowerTaskList.DebugPrintPower() -         tag=ENTITY_ID value=93
D 15:13:22.0880429 PowerTaskList.DebugPrintPower() -     TAG_CHANGE Entity=[entityName=UNKNOWN ENTITY [cardType=INVALID] id=93 zone=SETASIDE zonePos=0 cardId= player=1] tag=ZONE value=PLAY 
D 15:13:22.0880429 PowerTaskList.DebugPrintPower() -     TAG_CHANGE Entity=[entityName=UNKNOWN ENTITY [cardType=INVALID] id=92 zone=DECK zonePos=0 cardId= player=1] tag=DISPLAYED_CREATOR value=28 
D 15:13:22.0880429 PowerTaskList.DebugPrintPower() -     META_DATA - Meta=TARGET Data=0 Info=1
D 15:13:22.0880429 PowerTaskList.DebugPrintPower() -         Info[0] = [entityName=UNKNOWN ENTITY [cardType=INVALID] id=92 zone=DECK zonePos=0 cardId= player=1]
D 15:13:22.0880429 PowerTaskList.DebugPrintPower() -     FULL_ENTITY - Updating [entityName=UNKNOWN ENTITY [cardType=INVALID] id=94 zone=DECK zonePos=0 cardId= player=1] CardID=
D 15:13:22.0880429 PowerTaskList.DebugPrintPower() -         tag=ZONE value=DECK
D 15:13:22.0880429 PowerTaskList.DebugPrintPower() -         tag=CONTROLLER value=1
D 15:13:22.0880429 PowerTaskList.DebugPrintPower() -         tag=ENTITY_ID value=94
D 15:13:22.0880429 PowerTaskList.DebugPrintPower() -     FULL_ENTITY - Updating [entityName=UNKNOWN ENTITY [cardType=INVALID] id=95 zone=SETASIDE zonePos=0 cardId= player=1] CardID=
D 15:13:22.0880429 PowerTaskList.DebugPrintPower() -         tag=ZONE value=SETASIDE
D 15:13:22.0880429 PowerTaskList.DebugPrintPower() -         tag=CONTROLLER value=1
D 15:13:22.0880429 PowerTaskList.DebugPrintPower() -         tag=ENTITY_ID value=95
D 15:13:22.0880429 PowerTaskList.DebugPrintPower() -     TAG_CHANGE Entity=[entityName=UNKNOWN ENTITY [cardType=INVALID] id=95 zone=SETASIDE zonePos=0 cardId= player=1] tag=ZONE value=PLAY 
D 15:13:22.0880429 PowerTaskList.DebugPrintPower() -     TAG_CHANGE Entity=[entityName=UNKNOWN ENTITY [cardType=INVALID] id=94 zone=DECK zonePos=0 cardId= player=1] tag=DISPLAYED_CREATOR value=28 
D 15:13:22.0880429 PowerTaskList.DebugPrintPower() -     META_DATA - Meta=TARGET Data=0 Info=1
D 15:13:22.0880429 PowerTaskList.DebugPrintPower() -         Info[0] = [entityName=UNKNOWN ENTITY [cardType=INVALID] id=94 zone=DECK zonePos=0 cardId= player=1]
D 15:13:22.0880429 PowerTaskList.DebugPrintPower() -     FULL_ENTITY - Updating [entityName=UNKNOWN ENTITY [cardType=INVALID] id=96 zone=DECK zonePos=0 cardId= player=1] CardID=
D 15:13:22.0880429 PowerTaskList.DebugPrintPower() -         tag=ZONE value=DECK
D 15:13:22.0880429 PowerTaskList.DebugPrintPower() -         tag=CONTROLLER value=1
D 15:13:22.0880429 PowerTaskList.DebugPrintPower() -         tag=ENTITY_ID value=96
D 15:13:22.0880429 PowerTaskList.DebugPrintPower() -     FULL_ENTITY - Updating [entityName=UNKNOWN ENTITY [cardType=INVALID] id=97 zone=SETASIDE zonePos=0 cardId= player=1] CardID=
D 15:13:22.0880429 PowerTaskList.DebugPrintPower() -         tag=ZONE value=SETASIDE
D 15:13:22.0880429 PowerTaskList.DebugPrintPower() -         tag=CONTROLLER value=1
D 15:13:22.0880429 PowerTaskList.DebugPrintPower() -         tag=ENTITY_ID value=97
D 15:13:22.0885447 PowerTaskList.DebugPrintPower() -     TAG_CHANGE Entity=[entityName=UNKNOWN ENTITY [cardType=INVALID] id=97 zone=SETASIDE zonePos=0 cardId= player=1] tag=ZONE value=PLAY 
D 15:13:22.0885447 PowerTaskList.DebugPrintPower() -     TAG_CHANGE Entity=[entityName=UNKNOWN ENTITY [cardType=INVALID] id=96 zone=DECK zonePos=0 cardId= player=1] tag=DISPLAYED_CREATOR value=28 
D 15:13:22.0885447 PowerTaskList.DebugPrintPower() -     META_DATA - Meta=TARGET Data=0 Info=1
D 15:13:22.0885447 PowerTaskList.DebugPrintPower() -         Info[0] = [entityName=UNKNOWN ENTITY [cardType=INVALID] id=96 zone=DECK zonePos=0 cardId= player=1]
D 15:13:22.0885447 PowerTaskList.DebugPrintPower() - BLOCK_END
D 15:13:22.0885447 PowerProcessor.PrepareHistoryForCurrentTaskList() - m_currentTaskList=146
```
(Note: This is just for documentation, not the HDT log I'm asking for)

**Comment by jleclanche** [comment] 2018-08-07 22:28
GameState maybe?

**Comment by azeier** [comment] 2018-08-07 22:29
HDT only uses PTL

**Comment by azeier** [comment] 2018-08-07 22:39
Alright, this is an issue with Augmented Elekk + Academic Espionage:
- Academic Espionage creates all cards but keeps them hidden.
- Augmented Elekk creates copies of these cards but reveals the copies.

**Comment by azeier** [comment] 2018-08-07 22:48
![image](https://user-images.githubusercontent.com/7737910/43806555-4724ae80-9a59-11e8-9060-8930cab70c5a.png)

You can actually see all the cards created by Augmented Elekk in the sidebar, so this is a bug on Blizzards end, not in HDT.

**Comment by aalear** [comment] 2018-08-07 22:52
Ah, yeah, can confirm - I had an Augmented Elekk on the board at the time: https://hsreplay.net/replay/jSntSnmHHDotNcqWDzCMYm. Thanks for digging into it.

**Comment by azeier** [comment] 2018-08-07 22:54
I'm going to leave this open for a week or two to avoid the 20 duplicates :).

**Comment by aalear** [comment] 2018-08-09 19:38
@azeier Looks like a norepro with the Elekk now too, even in Blizzard's card log. I guess they fixed it on their end.

![image](https://user-images.githubusercontent.com/361657/43921587-2e57b5cc-9bea-11e8-81aa-3424a23d213b.png)

**Comment by azeier** [comment] 2018-08-11 20:35
Good job blizzard 😄

**Closed by azeier** 2018-08-11 20:35 UTC
Labels: boomsday, hearthstone-bug, won't fix
