### ISSUE TITLE
Doesn't update Automatically

### ISSUE THREAD

**Issue by hellclown210** [HearthSim/Hearthstone-Deck-Tracker#3597] opened 2018-03-16 17:10 UTC
### Expected Behavior
 When i press update now that the HDT tracker will start the download, and update automatically. 

### Actual Behavior
 Gives the errors in the picture .

### Steps to reproduce behavior
just pressing update now. 

### Log/Screenshots

![capture](https://user-images.githubusercontent.com/32193347/37534454-89eafac6-294d-11e8-8051-8814de0b1e00.PNG)

**Comment by riQQ** [comment] 2018-03-16 17:55
Duplicate of #3587

**Closed by riQQ** 2018-03-16 17:55 UTC
