### ISSUE TITLE
Suggestion: Stats and Replay - Jump to Deck

### ISSUE THREAD

**Issue by GiggliG** [HearthSim/Hearthstone-Deck-Tracker#2464] opened 2016-05-03 04:51 UTC
In the stats matches list, you have a number of buttons: Replay, opp Deck, Edit, etc.

I'd like a button to "select deck, so that it makes that deck the current one in the Deck list view. 

Often I'm looking through old games, and want to find the deck I played that match for. And finding that deck is a bit of a chore when they aren't sorted alphabetically and you have as many decks as I have stored.

**Comment by culinko** [comment] 2016-05-03 10:26
Dupe of #690, it's even your own issue :P

**Closed by culinko** 2016-05-03 10:26 UTC

**Comment by GiggliG** [comment] 2016-05-04 10:32
Yeah, but that's a year old and hasn't been done, and the stats have been completely revised since then.
