### ISSUE TITLE
Global Stat Tracking

### ISSUE THREAD

**Issue by Kryptor1987** [HearthSim/Hearthstone-Deck-Tracker#3052] opened 2016-12-29 13:38 UTC
I'd like to know, if there is a way to track the stats (wins and loss) globally.
The decks are synced and available for all machines using the same account, but it seems to me that the stats are saved just on local machine.

Is there a way to get the stats synced as well?

Thanks for your replies

**Comment by judge2020** [comment] 2016-12-29 17:39
You may be talking about hearthstats, you should try to not use that until we release a better system. The owner of HearthStats no longer maintains the website

**Comment by xLeitix** [comment] 2017-02-20 06:47
This "better system" that you are talking about - is this something that is being worked on, and is there an expected delivery date? At the moment I can't find a way to sync my stats between two gamng computers.

**Comment by judge2020** [comment] 2017-06-10 03:56
closed in favor of #3235

**Closed by judge2020** 2017-06-10 03:56 UTC

**Comment by judge2020** [comment] 2017-07-19 20:49
duplicate of #3235
