### ISSUE TITLE
Latest Update Doesn't Allow Access to Addon Settings

### ISSUE THREAD

**Issue by Dushku** [HearthSim/Hearthstone-Deck-Tracker#3453] opened 2017-10-19 16:50 UTC
## Bug report
With the latest update(s) to HDT, I can no longer access the Settings of individual Addons.

### Expected Behavior
Clicking on Settings while an Addon that has adjustable Settings is highlighted used to bring up a sub-panel that offered that Addon's adjustable settings.

### Actual Behavior
Nothing happens now. While the Addon with adjustable Settings is highlighted, when you press the Settings button, it just changes color to indicate you're no longer clicking it.

### Steps to reproduce behavior
Install an Addon that has adjustable Settings, Enable that Addon, then attempt to adjust its Settings.

### Log/Screenshots
N/A

**Comment by riQQ** [comment] 2017-10-19 17:13
I can't reproduce this with Collection Tracker. Which plugins don't work for you?

**Comment by Dushku** [comment] 2017-10-19 17:14
Sorry that I did not include that info up front. I assumed it would be an issue with HDT since that's what updated.

The Addon is called Graveyard.

**Comment by chWolfgang** [comment] 2017-10-19 17:20
I can confirm that I can no longer get into Options in Graveyard. Just turn it on and off.  Also, it reset its Options to default.

That being said, there has been some work on that plugin in since last Xpac - but not released, for what it is worth.

**Comment by riQQ** [comment] 2017-10-19 17:22
It is probably caused by the HDT update that also updated the UI Framework MahApps.Metro.

**Comment by azeier** [comment] 2017-10-19 17:28
```
7:26:51 PM|Error|PluginWrapper.OnButtonPress >> Graveyard
System.MissingMethodException: Method not found: 'Void MahApps.Metro.Controls.Flyout.set_Header(System.String)'.
   at HDT.Plugins.Graveyard.SettingsView.CreateSettingsFlyout()
   at HDT.Plugins.Graveyard.SettingsView.get_Flyout()
   at HDT.Plugins.Graveyard.GraveyardPlugin.OnButtonPress()
   at Hearthstone_Deck_Tracker.Plugins.PluginWrapper.OnButtonPress() in D:\GitHub\Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\Plugins\PluginWrapper.cs:line 144
```

This is an issue specifically with Graveyard. Needs to be fixed on the plugins side, sorry.

**Closed by azeier** 2017-10-19 17:28 UTC

**Comment by Dushku** [comment] 2017-10-19 17:46
Well is there a way for me to use an outdated version? I tried running C:\Users\TFAD\AppData\Local\HearthstoneDeckTracker\app-1.4.3\HearthstoneDeckTracker.exe

Its functionality is incomplete. I only play N'Zoth decks and need that addon to work as reliably as possible. I don't have a use for the HDT upgrades since that version. Rolling back would solve this issue for me while not rolling back makes HDT almost useless to me. Please advise.

**Comment by chWolfgang** [comment] 2017-10-19 19:48
Dushku:
I am using Graveyard right now. It works for me at DEFAULT settings. But I did have to go turn it on inside Deck Tracker/Options/Plugins/Graveyard

BUT I can not open SETTINGS for graveyard

**Comment by riQQ** [comment] 2017-10-19 20:35
Afaik the old version doesn't work with the latest Hearthstone update.

**Comment by Dushku** [comment] 2017-10-19 20:50
Thanks. Does anybody have an old version I can install that won't be updated or effected by the update?

**Comment by judge2020** [comment] 2017-10-19 20:57
The only HDT version that works with the latest HDT is 1.5.0/1.5.1, both of which are on the updated MahApps.Metro. A bug has been created over there https://github.com/RedHatter/Graveyard/issues/24.

**Comment by Dushku** [comment] 2017-10-20 01:18
Thanks, judge2020. I didn't understand why 1.4.3 wouldn't work, but your mention of HS changing answers it for me.

Now I'm just looking for somebody that has the ability and willingness to help me/us with an interim workaround. The Graveyard addon is notoriously un-supported. I intend to learn how to do these things for myself since it's pretty crucial to some of the things I'm doing.

Thanks to all who have helped to shed light on this.

**Comment by riQQ** [comment] 2017-10-20 06:04
See https://github.com/RedHatter/Graveyard/issues/26 for an unofficial update of the Graveyard plugin.

**Comment by Dushku** [comment] 2017-10-20 16:31
Thank you!
