### ISSUE TITLE
Some cards don't appear on the deck tracker

### ISSUE THREAD

**Issue by Pand3m0nia** [HearthSim/Hearthstone-Deck-Tracker#2535] opened 2016-05-27 16:00 UTC
Hi there,

I'm having an issue where one card isn't appearing in the deck tracker. I have tried restarting Battle.net and the Tracker as well as using different decks, but it always seems to be in a similar position where the card is missing.

Any help would be appreciated.

![untitled](https://cloud.githubusercontent.com/assets/10948053/15613491/fdc38b46-2433-11e6-89d5-405df926378a.png)

**Comment by riQQ** [comment] 2016-05-27 16:14
Probably #757.

**Comment by Pand3m0nia** [comment] 2016-05-27 16:15
If and when I draw the card then it appears back on the deck tracker.

**Comment by Epix37** [comment] 2016-05-27 16:39
Yup, duplicate of #757.

**Closed by Epix37** 2016-05-27 16:39 UTC
