### ISSUE TITLE
15th Card in player list is Invisible

### ISSUE THREAD

**Issue by Omen724** [HearthSim/Hearthstone-Deck-Tracker#2424] opened 2016-04-29 00:37 UTC
Imgur link [here](http://imgur.com/8lxPBlv) - (My mouse is hovering over the Entomb card)

Currently I'm having an issue whenever I start up HDT. In my card list UI for Hearthstone, the **15th** card slot is invisible for the player side. This happens for each single deck and is only fixed by restarting using the in-client "Restart HDT" function. Even after restarting in this fashion, switching to a different deck will make the 15th card invisible again. Ending the program and restarting it manually does not fix the problem.

Some clarification on what I mean by the "15th" card being invisible: In a Reno Jackson list, in which there are 30 different cards, the 15th card in that list will be invisible. However, in a list running 15 2ofs, the last card in the list will be invisible.

This issue began for me after the v0.14.1 release and has persisted with each new update. I had no issues with invisible cards before that update. I would appreciate any work on the issue, thanks.

**Comment by culinko** [comment] 2016-04-29 04:16
I think this is a dupe of #757.

**Closed by culinko** 2016-04-29 04:16 UTC
