### ISSUE TITLE
Crash when using Hearthstone-Collection-Tracker on v.0.14.8 and v.0.14.7

### ISSUE THREAD

**Issue by windswell** [HearthSim/Hearthstone-Deck-Tracker#2507] opened 2016-05-15 05:54 UTC
Crash HDT v.0.14.8 and v.0.14.7 when call Hearthstone-Collection-Tracker plugin main window.
[Crash report 1552016-232.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/264851/Crash.report.1552016-232.txt)

**Comment by riQQ** [comment] 2016-05-15 09:09
Do you have the latest version of the Hearthstone Collection Tracker plugin?

**Comment by windswell** [comment] 2016-05-15 13:11
Yes, I use Hearthstone-Collection-Tracker v0.4.1.

**Comment by Nibell** [comment] 2016-05-16 12:28
Hi
Have the issue crash on my setup as well have HDT v.0.14.8
[Crash report 1652016-1422.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/266067/Crash.report.1652016-1422.txt)

**Comment by Epix37** [comment] 2016-05-16 14:50
@ko-vasilev any ideas?

**Comment by ko-vasilev** [comment] 2016-05-18 04:08
For now I can't reproduce the issue or find what might cause it.

**Comment by culinko** [comment] 2016-06-22 06:04
Should be fixed.

**Closed by culinko** 2016-06-22 06:04 UTC
Labels: plugin
