### ISSUE TITLE
Feature request: Sync online replays (Arcane Tracker) with the PC app 

### ISSUE THREAD

**Issue by Moldavone** [HearthSim/Hearthstone-Deck-Tracker#3866] opened 2019-02-04 13:13 UTC
I'm playing HS on both PC and Android (Arcane Tracker), it would be great to have an automatic sync function, that would import Android replays into the PC app, so that the playing statistics remain up to date. I know you can do it manually, but it's too long of a process, when you need to import a lot of replays.

**Comment by riQQ** [comment] 2019-02-04 20:05
Duplicate of #3846

**Closed by riQQ** 2019-02-04 20:05 UTC

**Comment by marcabrus** [comment] 2019-02-09 11:25
How you can sync manually replays?

**Comment by Moldavone** [comment] 2019-02-09 13:18
Not the replays, but the games, for the sake of keeping all your statistics in one place:
How can I add games manually?
**Constructed**
Set the deck you want to add a game to as active
Go to STATS > CONSTRUCTED
Select Matches
Then click on ADD NEW GAME TO ACTIVE DECK

**Arena**
Go to STATS > ARENA
Select Runs & matches
Select the run you want to add a game to
Then click on ADD GAME

**Comment by marcabrus** [comment] 2019-02-09 15:32
Thank you for the answer. I thought that also arcane tracker could create the same replay files, and i could copy and paste in hdt folder
