### ISSUE TITLE
Whizbang's Wonderful Decks track

### ISSUE THREAD

**Issue by tameTNT** [HearthSim/Hearthstone-Deck-Tracker#3748] opened 2018-08-07 19:13 UTC
## Bug report
The tracker cannot yet detect the randomly-selected Whizbang deck when playing with whizbang. I imported all 18 current premade deck recipes into the tracker.

### Expected Behavior
The tracker would auto-select the correct premade deck based on the cards available for mulligan and function as normal.

### Actual Behavior
The tracker got stuck on the previously used deck and persisted to display it. After the active deck was manually changed to the correct randomly-selected whizbang deck, the tracker displayed it but didn't update the card counts once cards were drawn and played.

### Steps to reproduce behavior
-Import all 18 premade deck recipes into the tracker
-Start a whizbang game
-(Change the active deck manually to the chosen one)

**Comment by loxxyy** [comment] 2018-08-08 15:20
When i change to the deck chosen by whizbang, the deck tracker doesn't work (it registers the entire new deck but not when a card is drawn).

**Comment by Sedfer** [comment] 2018-08-08 21:56
Same issue.
I thought it might be caused by not having the deck in your Hearthstone decklist, but after some testing I can confirm that it doesn't work even if you have it. Starting the deck normaly works fine, so Whizbang himself somehow prevents the tracker from detecting decks properly.

**Comment by azeier** [comment] 2018-08-08 22:10
This is an issue with how Hearthstone handles the cards created by Whizbang. The release will include a fix for this (and most likely automatically create the decks).

**Comment by fredderico18** [comment] 2018-08-09 03:26
Not sure if someone else also said this, but when playing against someone using a Whizbang deck the deck tracker will mark all of their played cards with the gift icon. Probably something on Blizzard's end based on how they're handling the random deck each game, but the deck tracker probably should try to avoid showing this to users as Blizzard intentionally don't want players to know that they're facing a Whizbang deck.

**Comment by azeier** [comment] 2018-08-09 03:36
This and the opponent side of this have been fixed with https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/45405ff9579fe87bee77d4bdc95a8d537f7d6665

**Comment by azeier** [comment] 2018-08-09 04:46
Here's a test release that should fix all the tracking issues and automatically import all the deck recipes when the whizbang deck is found: https://github.com/HearthSim/HDT-dev-builds/releases/download/v1.7.2-dev3668/HDT-Installer.exe

This version will overwrite your current installation (keeps settings etc) and automatically update to the next stable release once available.

Let me know if you notice any issues.

**Comment by tameTNT** [comment] 2018-08-09 19:18
Thanks for the quick response and fix!

**Closed** 2018-08-09 19:18 UTC
Labels: boomsday, fixed-for-next-release

**Comment by riQQ** [comment] 2018-08-09 20:26
Deck importing for Whizbang decks is implemented in 87979c46e17c03da0561f1620f7538950056a4df
