### ISSUE TITLE
Monster Hunt starting cards change (maybe Dungeon Run too)

### ISSUE THREAD

**Issue by Trimutius** [HearthSim/Hearthstone-Deck-Tracker#3810] opened 2018-10-27 16:37 UTC
## Bug report
Started monster Hunt today and deck tracker starting 10 cards were off. I also don't remember having a flamewaker as Toki before. I would also suggest to double check all 13 decks from both Dungeon Run and Monster Hunt just to make sure there are no further changes. (As I see an earlier report about mage deck in Dungeon Run)

### Expected Behavior
Well I expected correct 10 cards to show up in tracker. Also when I clicked use no deck I was expecting it to stop trying to load those starting 10 cards which are incorrect...

### Actual Behavior
It failed to switch to no-deck mode and was trying to reload old version of starting Toki cards all the time. I would expect in best case scenario to load 10 correct new cards, but if failed at least let me play in no-deck mode.

### Steps to reproduce behavior
Just start a run with Toki in Monster Hunt. (probably some other classes in Dungeon Run and Monster Hunt are also affected)

**Comment by riQQ** [comment] 2018-10-27 17:00
Duplicate of #3808

**Closed by riQQ** 2018-10-27 17:00 UTC
