### ISSUE TITLE
hunterSecret(Hidden Cache)

### ISSUE THREAD

**Issue by joulu1225** [HearthSim/Hearthstone-Deck-Tracker#3464] opened 2017-10-28 15:59 UTC
### Actual Behavior

hunterSecret(Hidden Cache),opponent out of the card any hunterSecret,my hearthstone deck tracker show me hunterSecret possible,but when i out of the card,it didn't trigger,then my hearthstone deck tracker didn't show hunterSecret(Hidden Cache) to dark.

**Comment by MxSquareC** [comment] 2017-11-05 10:58
I've encountered the same issue, but I'll try to explain it better. So if any Hunter Secret is played, the list of all secrets is displayed, as expected. But if you play a minion, the secret : "Hidden cache" is still highlighted as if it is still a possibility , while it is clear that it isn't. Please attend.

**Comment by riQQ** [comment] 2017-11-05 11:10
Duplicate of #2987

**Closed by riQQ** 2017-11-05 11:10 UTC
