### ISSUE TITLE
Overlay offset using dual monitors with different scaling

### ISSUE THREAD

**Issue by jperotka** [HearthSim/Hearthstone-Deck-Tracker#3723] opened 2018-07-10 02:47 UTC
### Expected Behavior
When using two monitors with 100% scaling, overlay works as expected. When a second monitor is added and scaled to 125%, but the primary monitor is still at 100%, I would expect the overlay running on the primary monitor to still line up correctly.

### Actual Behavior
When the secondary monitor is scaled to 125% the overlay on the primary monitor scales.

### Steps to reproduce behavior
Switching the secondary monitor scaling back and forth between 100%/125% either fixes or introduces the issue.

**Comment by beheh** [comment] 2018-07-11 10:04
Duplicate of #3445

**Closed by beheh** 2018-07-11 10:04 UTC
Labels: duplicate
