### ISSUE TITLE
Recurrent updating issues.

### ISSUE THREAD

**Issue by 4lh** [HearthSim/Hearthstone-Deck-Tracker#2662] opened 2016-07-10 13:38 UTC
Hi, for the second time I have an update issue:

"There was an error installing the latest update. Press any key to open the website for manual download."

The first time I deleted and reinstalled Hearthstone Deck Tracker but it was annoying to reconfigure all my settings after that. I really enjoy your program ♥ but since I can almost never update it with updater and it's so long to reconfigure everything I skip updates now.

**Comment by Epix37** [comment] 2016-07-11 11:38
Duplicate of #2562. Closing in favor of that one.

Currently working on a new updating system. This issue should get resolved within the next few weeks.

**Closed by Epix37** 2016-07-11 11:38 UTC
