### ISSUE TITLE
Compare two decks in HDT

### ISSUE THREAD

**Issue by GaryKing** [HearthSim/Hearthstone-Deck-Tracker#2523] opened 2016-05-21 20:59 UTC
Perhaps add a feature to compare two decks in HDT? The ability to compare two decks already seems to exist in HDT, when viewing a deck's version history.

So it'd be nice to see the difference between two similar decks in our HDT, using the same interface.

**Comment by culinko** [comment] 2016-06-22 01:42
Duplicate of #771.

**Closed by culinko** 2016-06-22 01:42 UTC
