### ISSUE TITLE
Using a Constructed deck build for a Brawl changes that deck's type to Brawl instead of creating a Brawl-specific copy

### ISSUE THREAD

**Issue by ShotFromGuns** [HearthSim/Hearthstone-Deck-Tracker#3769] opened 2018-08-16 16:42 UTC
### Expected Behavior
When creating any Brawl deck—regardless of whether it happens to be identical to a Constructed deck that already exists in my HDT deck list—a new deck should be added to the list, with the Brawl type and unique stat tracking.

### Actual Behavior
Functions as expected when a unique Brawl deck is created. However, if the new Brawl deck matches an existing Constructed deck, that existing deck has its type changed to Brawl, and any Brawl stats are added onto the existing stats for the deck.

### Steps to Reproduce Behavior
Create and play with a Brawl deck that is identical to any Constructed deck currently in the user's HDT library.

### Other Notes
I've seen mention of this issue in a couple of other tickets, e.g., #3671 and #3695 , which had replies alerting users to the unintuitive workaround fix of tagging a Brawl deck as Favorite to move it back to Constructed (and then untagging Favorite if you don't want that tag on it). However, it seemed like those tickets didn't address the full issue (at most requesting a simpler way to remove the Brawl tag rather than correcting the problem altogether), so hopefully this isn't seen as a duplicate.

If this is indeed a feature working as intended and not a bug, adding a toggle setting and/or a confirmation dialogue for whether a duplicate Brawl deck should convert the existing Constructed deck or generate a copy with separate stat tracking would be greatly appreciated.

**Comment by azeier** [comment] 2018-08-28 15:01
This behavior should be fixed with the next release. Decks will not be tagged as brawl if they have any non-brawl games.

**Closed by azeier** 2018-08-28 15:01 UTC

**Comment by riQQ** [comment] 2018-08-28 17:52
Duplicate of #3671
