### ISSUE TITLE
Infoleak with card tracking when Baku is drawn

### ISSUE THREAD

**Issue by beheh** [HearthSim/Hearthstone-Deck-Tracker#3790] opened 2018-09-11 10:43 UTC
## Bug report

![grafik](https://user-images.githubusercontent.com/929769/45355148-e5961780-b5bf-11e8-9e8d-654ece6ff246.png)

Reported via Discord. This might also affect other Start of Game cards besides Baku.

### Expected Behavior
Baku should neither be a gifted card, nor should the tooltip show it's name or description. It should behave like every other card.

### Actual Behavior
When Card Tracking is enabled, Baku has a small purple gift icon next to the turn number. Additionally, the entities name and description is shown when hovering and tooltips are enabled.

### Steps to reproduce behavior
According to the reporting user, enable Card Tracking and tooltips and play against a player with Baku. Wait until Baku is drawn, hover the cards.

### Log/Screenshots
Not at this time, although awaiting a log/replay from the user.

**Comment by azeier** [comment] 2018-09-11 10:48
Good chance this is actually the same issue as #3771

**Comment by beheh** [comment] 2018-09-11 10:56
Isn't that the opposite?

Additionally it appears that for this report the opposing player was using Whizbang.

**Comment by beheh** [comment] 2018-09-11 10:58
[Replay](https://hsreplay.net/replay/jYfrXDAcxLWLNgnVXXhp8e) and [Power Log](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2370683/jYfrXDAcxLWLNgnVXXhp8e.power.log).

**Comment by ceceita** [comment] 2018-09-11 12:13
is more like entomb - psychic scream - etc info leak ..
riQQ words

> As the minion entities don't change, HDT knows, when this specific entity is drawn. So this is an info leak in Hearthstone itself.

**Comment by riQQ** [comment] 2019-03-11 22:25
Duplicate of #3627

**Closed by riQQ** 2019-03-11 22:25 UTC
Labels: decktracker
