### ISSUE TITLE
ui bug: 0 hours instead of 60 minutes

### ISSUE THREAD

**Issue by sshilovsky** [HearthSim/Hearthstone-Deck-Tracker#3388] opened 2017-08-21 17:50 UTC
### Bug report
`0 hour ago` is shown for a game in statistics area on main window for the game that happened an hour ago (see screenshot)

### Expected Behavior
the game was played about 60 minutes back at that time, so either `60 minutes` or `1 hour` should be displayed

### Screenshot
http://hmp.me/apls

**Comment by azeier** [comment] 2017-08-24 13:12
Duplicate of #3358

**Closed by azeier** 2017-08-24 13:12 UTC
