### ISSUE TITLE
[BUG] HDT lost cards in deck!

### ISSUE THREAD

**Issue by chip83** [HearthSim/Hearthstone-Deck-Tracker#3031] opened 2016-12-16 12:02 UTC
HDT lost card when restarted. I see my deck to 18 cards (over 30) when i restart HDT.
I have tried to unistall HDT, make a clean with ccleaner and re-install, but with no result.
Any suggestion?

Thanks.

**Comment by azeier** [comment] 2016-12-16 12:19
Are you logged in to hearthstats?

**Comment by chip83** [comment] 2016-12-16 14:42
yes

**Comment by judge2020** [comment] 2016-12-16 14:44
This may be because it detects those 18 cards in your deck when you press play in-game.

**Comment by azeier** [comment] 2016-12-16 14:56
HearthStats is not update for MSG and deck syncing will break your decks. Logging out should fix your issue.

**Comment by chip83** [comment] 2016-12-16 15:00
Thanks, I try.

**Comment by azeier** [comment] 2016-12-17 09:40
No you should not log in again, HearthStats is pretty broken right now.

**Comment by chip83** [comment] 2017-01-03 14:42
any news for when HearthStats work again?

**Comment by judge2020** [comment] 2017-01-03 18:34
@chip83 Hearthstats likely won't be coming back, as it is not actively being developed and Mean Streets cards haven't been added in yet.

**Comment by judge2020** [comment] 2017-06-10 04:05
Closed in favor of #3235

**Closed by judge2020** 2017-06-10 04:05 UTC
Labels: HearthStats, invalid

**Comment by judge2020** [comment] 2017-07-19 20:49
duplicate of #3235
