### ISSUE TITLE
United in Stormwind Whizbang decks not been imported into decktracker

### ISSUE THREAD

**Issue by Kummo33** [HearthSim/Hearthstone-Deck-Tracker#4331] opened 2021-08-08 11:26 UTC
The new United in Stormwind Whizbang recipes are not been imported into deck tracker, so that makes it go into a deck reload loop that makes the decklist on the side disappear and appear constantly when you play the new decks.

I've confirmed that the deck import is working by deleting all decks and relogging in. It successfully reimports the old whizbang decks from the last expansion (Raptor Frenzy, Magical Trio, etc) but the new recipes are not been imported.

**Comment by Dalarrus** [comment] 2021-11-28 13:52
This is still an issue. Deck reload loop when using a modern deck through Whizbang.

**Comment by beheh** [comment] 2023-12-16 01:20
Duplicate of #4046.

**Closed by beheh** 2023-12-16 01:20 UTC
