### ISSUE TITLE
Crashing every time I go to Stats

### ISSUE THREAD

**Issue by pauturvalles** [HearthSim/Hearthstone-Deck-Tracker#3998] opened 2020-01-17 08:58 UTC
### Expected Behavior
 I wanted to go to the Stats tab

### Actual Behavior
 The program crashed

### Steps to reproduce behavior
 Yes, every time I go to the Stats page

### Log/Screenshots

![Screenshot](https://user-images.githubusercontent.com/3404787/72669895-b6a37780-3a37-11ea-8eae-63a385231a65.png)

**Comment by riQQ** [comment] 2020-01-18 20:16
Can please post a screenshot after clicking `Show Stacktrace`.
Also please provide the HDT log corresponding to this problem. See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues#hdt-log-files.

**Comment by pauturvalles** [comment] 2020-01-18 21:45
> Can you please post a screenshot after clicking `Show Stacktrace`.
> Also please provide the HDT log corresponding to this problem. See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues#hdt-log-files.

Sure thing! Here's the screenshot:
https://i.imgur.com/wFU0Z6z.png

Here's the text:

> System.Windows.Markup.XamlParseException: Set connectionId threw an exception. ---> System.InvalidCastException: [A]MahApps.Metro.Controls.Flyout cannot be cast to [B]MahApps.Metro.Controls.Flyout. Type A originates from 'MahApps.Metro, Version=1.5.0.23, Culture=neutral, PublicKeyToken=f4fb5a3c4d1e5b4f' in the context 'LoadFrom' at location 'C:\Users\pautu\AppData\Local\HearthstoneDeckTracker\app-1.9.9\Plugins\Data Drinker\MahApps.Metro.dll'. Type B originates from 'MahApps.Metro, Version=1.5.0.23, Culture=neutral, PublicKeyToken=f4fb5a3c4d1e5b4f' in the context 'Default' at location 'C:\Users\pautu\AppData\Local\HearthstoneDeckTracker\app-1.9.9\MahApps.Metro.dll'.
   at Hearthstone_Deck_Tracker.Windows.StatsWindow.System.Windows.Markup.IComponentConnector.Connect(Int32 connectionId, Object target) in C:\projects\hearthstone-deck-tracker\Hearthstone Deck Tracker\Windows\StatsWindow.xaml:line 0
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetConnectionId(Object root, Int32 connectionId, Object instance)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at Hearthstone_Deck_Tracker.Windows.StatsWindow.InitializeComponent() in C:\projects\hearthstone-deck-tracker\Hearthstone Deck Tracker\Windows\StatsWindow.xaml:line 1
   at Hearthstone_Deck_Tracker.Windows.StatsWindow..ctor() in C:\projects\hearthstone-deck-tracker\Hearthstone Deck Tracker\Windows\StatsWindow.xaml.cs:line 17
   at Hearthstone_Deck_Tracker.Core.Windows.get_StatsWindow() in C:\projects\hearthstone-deck-tracker\Hearthstone Deck Tracker\Core.cs:line 340
   at Hearthstone_Deck_Tracker.Windows.MainWindow.ShowStats(Boolean arena, Boolean matches) in C:\projects\hearthstone-deck-tracker\Hearthstone Deck Tracker\Windows\MainWindow.xaml.cs:line 426
   at Hearthstone_Deck_Tracker.Windows.MainWindowControls.MainWindowMenuViewModel.<get_ConstructedStatsCommand>b__72_0() in C:\projects\hearthstone-deck-tracker\Hearthstone Deck Tracker\Windows\MainWindowControls\MainWindowMenuViewModel.cs:line 81
   at Hearthstone_Deck_Tracker.Utility.Command.Execute(Object parameter) in C:\projects\hearthstone-deck-tracker\Hearthstone Deck Tracker\Utility\Command.cs:line 17
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

And the log is attached as well.
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/4081810/hdt_log.txt)

**Comment by beheh** [comment] 2020-01-20 14:18
Looks like this is caused by the "Data Drinker" plugin shipping it's own version of the UI toolkit, so by uninstalling/disabling that plugin your stats page should start working again.

**Comment by beheh** [comment] 2020-01-20 15:12
Closing this issue then, as it's not an HDT bug.

**Closed by beheh** 2020-01-20 15:12 UTC
Labels: bug, crash
