### ISSUE TITLE
Issues with recording/tracking my games

### ISSUE THREAD

**Issue by TheMiziko** [HearthSim/Hearthstone-Deck-Tracker#2663] opened 2016-07-11 06:42 UTC
Sometimes, when my replay/game starts to record, after 2/3 min deck tracker resets, stops showing animations, and shows all the cards form my deck. After the game, replay or result from the game is not recorded. 

Is there any way to avoid it, or fix it ? I suppose, when HDT starts tracking the game already, there's not much that can go wrong, and I supposes HDT works fine, because I see changes in my deck. 
After that my HDT crashed with this windows results : 

```
Nazwa dziennika:Application
Źródło:        Windows Error Reporting
Data:          2016-07-11 12:04:55
Identyfikator zdarzenia:1001
Kategoria zadania:Brak
Poziom:        Informacje
Słowa kluczowe:Klasyczny
Użytkownik:    Nie dotyczy
Komputer:      Fireblade
Opis:
Pakiet błędów 133312604805, typ 5
Nazwa zdarzenia: MoAppCrash
Odpowiedź: Niedostępny
Identyfikator pliku Cab: 0

Sygnatura problemu:
P1: Microsoft.Messaging_2.15.20002.0_x86__8wekyb3d8bbwe
P2: praid:ppleae38af2e007f4358a809ac99a64a67c1
P3: 10.1.2123.36
P4: 56eb679c
P5: combase.dll
P6: 10.0.10586.103
P7: 56a84cbb
P8: 80004004
P9: 000b9e0b
P10: 

Dołączone pliki: 
C:\Users\TheMiziko\AppData\Local\Temp\WER7C33.tmp.WERInternalMetadata.xml

Te pliki mogą być dostępne tutaj:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Microsoft.Messag_24e2743892f95decf6aeed457199fe985cfb6a_37f1fbc4_2643804a

Symbol analizy: 
Ponowne sprawdzanie rozwiązania: 0
Identyfikator raportu: d1c4e35c-d180-46a1-922b-b08eddff7f55
Stan raportu: 0
Skrócony pakiet: 372a48d50980803cd28e2e12eecc8828
Kod XML zdarzenia:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" />
    <EventID Qualifiers="0">1001</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-07-11T10:04:55.432849200Z" />
    <EventRecordID>12349</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Fireblade</Computer>
    <Security />
  </System>
  <EventData>
    <Data>133312604805</Data>
    <Data>5</Data>
    <Data>MoAppCrash</Data>
    <Data>Niedostępny</Data>
    <Data>0</Data>
    <Data>Microsoft.Messaging_2.15.20002.0_x86__8wekyb3d8bbwe</Data>
    <Data>praid:ppleae38af2e007f4358a809ac99a64a67c1</Data>
    <Data>10.1.2123.36</Data>
    <Data>56eb679c</Data>
    <Data>combase.dll</Data>
    <Data>10.0.10586.103</Data>
    <Data>56a84cbb</Data>
    <Data>80004004</Data>
    <Data>000b9e0b</Data>
    <Data>
    </Data>
    <Data>
C:\Users\TheMiziko\AppData\Local\Temp\WER7C33.tmp.WERInternalMetadata.xml</Data>
    <Data>C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Microsoft.Messag_24e2743892f95decf6aeed457199fe985cfb6a_37f1fbc4_2643804a</Data>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>d1c4e35c-d180-46a1-922b-b08eddff7f55</Data>
    <Data>0</Data>
    <Data>372a48d50980803cd28e2e12eecc8828</Data>
  </EventData>
</Event>

Nazwa dziennika:Application
Źródło:        Application Error
Data:          2016-07-11 12:04:54
Identyfikator zdarzenia:1000
Kategoria zadania:(100)
Poziom:        Błędy
Słowa kluczowe:Klasyczny
Użytkownik:    Nie dotyczy
Komputer:      Fireblade
Opis:
Nazwa aplikacji powodującej błąd: SkypeHost.exe, wersja: 10.1.2123.36, sygnatura czasowa: 0x56eb679c
Nazwa modułu powodującego błąd: combase.dll, wersja: 10.0.10586.103, sygnatura czasowa: 0x56a84cbb
Kod wyjątku: 0xc000027b
Przesunięcie błędu: 0x00166fb1
Identyfikator procesu powodującego błąd: 0x17fc
Godzina uruchomienia aplikacji powodującej błąd: 0x01d1db599438d3c4
Ścieżka aplikacji powodującej błąd: C:\Program Files\WindowsApps\Microsoft.Messaging_2.15.20002.0_x86__8wekyb3d8bbwe\SkypeHost.exe
Ścieżka modułu powodującego błąd: C:\WINDOWS\SYSTEM32\combase.dll
Identyfikator raportu: d1c4e35c-d180-46a1-922b-b08eddff7f55
Pełna nazwa pakietu powodującego błąd: Microsoft.Messaging_2.15.20002.0_x86__8wekyb3d8bbwe
Identyfikator aplikacji względem pakietu powodującego błąd: ppleae38af2e007f4358a809ac99a64a67c1
Kod XML zdarzenia:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-07-11T10:04:54.270503400Z" />
    <EventRecordID>12348</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Fireblade</Computer>
    <Security />
  </System>
  <EventData>
    <Data>SkypeHost.exe</Data>
    <Data>10.1.2123.36</Data>
    <Data>56eb679c</Data>
    <Data>combase.dll</Data>
    <Data>10.0.10586.103</Data>
    <Data>56a84cbb</Data>
    <Data>c000027b</Data>
    <Data>00166fb1</Data>
    <Data>17fc</Data>
    <Data>01d1db599438d3c4</Data>
    <Data>C:\Program Files\WindowsApps\Microsoft.Messaging_2.15.20002.0_x86__8wekyb3d8bbwe\SkypeHost.exe</Data>
    <Data>C:\WINDOWS\SYSTEM32\combase.dll</Data>
    <Data>d1c4e35c-d180-46a1-922b-b08eddff7f55</Data>
    <Data>Microsoft.Messaging_2.15.20002.0_x86__8wekyb3d8bbwe</Data>
    <Data>ppleae38af2e007f4358a809ac99a64a67c1</Data>
  </EventData>
</Event>

Nazwa dziennika:Application
Źródło:        Windows Error Reporting
Data:          2016-07-11 11:55:37
Identyfikator zdarzenia:1001
Kategoria zadania:Brak
Poziom:        Informacje
Słowa kluczowe:Klasyczny
Użytkownik:    Nie dotyczy
Komputer:      Fireblade
Opis:
Pakiet błędów 129157276735, typ 5
Nazwa zdarzenia: CLR20r3
Odpowiedź: Niedostępny
Identyfikator pliku Cab: 0

Sygnatura problemu:
P1: Hearthstone Deck Tracker.exe
P2: 0.15.6.0
P3: 577fc752
P4: mscorlib
P5: 4.6.1080.0
P6: 570c5040
P7: 3b2c
P8: c
P9: System.OutOfMemoryException
P10: 

Dołączone pliki: 
C:\Users\TheMiziko\AppData\Local\Temp\WERF7C8.tmp.WERInternalMetadata.xml

Te pliki mogą być dostępne tutaj:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Hearthstone Deck_7282eb26e9eb8ffd5a1c4396be0287d85edce_2425278f_34cefcf8

Symbol analizy: 
Ponowne sprawdzanie rozwiązania: 0
Identyfikator raportu: 105e0229-8637-49d3-8431-3766e7b4d3ef
Stan raportu: 0
Skrócony pakiet: 438c919ab4c478c39bf1b8be7f30cda9
Kod XML zdarzenia:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" />
    <EventID Qualifiers="0">1001</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-07-11T09:55:37.524354400Z" />
    <EventRecordID>12347</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Fireblade</Computer>
    <Security />
  </System>
  <EventData>
    <Data>129157276735</Data>
    <Data>5</Data>
    <Data>CLR20r3</Data>
    <Data>Niedostępny</Data>
    <Data>0</Data>
    <Data>Hearthstone Deck Tracker.exe</Data>
    <Data>0.15.6.0</Data>
    <Data>577fc752</Data>
    <Data>mscorlib</Data>
    <Data>4.6.1080.0</Data>
    <Data>570c5040</Data>
    <Data>3b2c</Data>
    <Data>c</Data>
    <Data>System.OutOfMemoryException</Data>
    <Data>
    </Data>
    <Data>
C:\Users\TheMiziko\AppData\Local\Temp\WERF7C8.tmp.WERInternalMetadata.xml</Data>
    <Data>C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Hearthstone Deck_7282eb26e9eb8ffd5a1c4396be0287d85edce_2425278f_34cefcf8</Data>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>105e0229-8637-49d3-8431-3766e7b4d3ef</Data>
    <Data>0</Data>
    <Data>438c919ab4c478c39bf1b8be7f30cda9</Data>
  </EventData>
</Event>

Nazwa dziennika:Application
Źródło:        Application Error
Data:          2016-07-11 11:55:35
Identyfikator zdarzenia:1000
Kategoria zadania:(100)
Poziom:        Błędy
Słowa kluczowe:Klasyczny
Użytkownik:    Nie dotyczy
Komputer:      Fireblade
Opis:
Nazwa aplikacji powodującej błąd: Hearthstone Deck Tracker.exe, wersja: 0.15.6.0, sygnatura czasowa: 0x577fc752
Nazwa modułu powodującego błąd: KERNELBASE.dll, wersja: 10.0.10586.306, sygnatura czasowa: 0x571afb9a
Kod wyjątku: 0xe0434352
Przesunięcie błędu: 0x000bdae8
Identyfikator procesu powodującego błąd: 0x2ff4
Godzina uruchomienia aplikacji powodującej błąd: 0x01d1db5139b0923c
Ścieżka aplikacji powodującej błąd: C:\Users\TheMiziko\Downloads\Hearthstone Deck Tracker\Hearthstone Deck Tracker.exe
Ścieżka modułu powodującego błąd: C:\WINDOWS\SYSTEM32\KERNELBASE.dll
Identyfikator raportu: 105e0229-8637-49d3-8431-3766e7b4d3ef
Pełna nazwa pakietu powodującego błąd: 
Identyfikator aplikacji względem pakietu powodującego błąd: 
Kod XML zdarzenia:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-07-11T09:55:35.918481900Z" />
    <EventRecordID>12346</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Fireblade</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Hearthstone Deck Tracker.exe</Data>
    <Data>0.15.6.0</Data>
    <Data>577fc752</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.10586.306</Data>
    <Data>571afb9a</Data>
    <Data>e0434352</Data>
    <Data>000bdae8</Data>
    <Data>2ff4</Data>
    <Data>01d1db5139b0923c</Data>
    <Data>C:\Users\TheMiziko\Downloads\Hearthstone Deck Tracker\Hearthstone Deck Tracker.exe</Data>
    <Data>C:\WINDOWS\SYSTEM32\KERNELBASE.dll</Data>
    <Data>105e0229-8637-49d3-8431-3766e7b4d3ef</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event> 
```

**Comment by Epix37** [comment] 2016-07-11 11:34
This looks like https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/2584

**Comment by TheMiziko** [comment] 2016-07-11 17:51
@Epix37 In addition to that, I'm including logs from my previous session, where the deck tracker didn't track the game, and didn't save replay : 
[log_1172016-191336.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/357707/log_1172016-191336.txt)

The deck tracker doesn't work, unless my hearthstone is already running, And it doesn't record any game if I will not restart it after each game. Any ideas ?

**Comment by riQQ** [comment] 2017-09-27 21:17
Duplicate of #2584

**Closed by riQQ** 2017-09-27 21:17 UTC
Labels: duplicate
