### ISSUE TITLE
Experience counter has stopped appearing for several months

### ISSUE THREAD

**Issue by mechanicarts** [HearthSim/Hearthstone-Deck-Tracker#4469] opened 2023-05-25 12:02 UTC
### Expected Behavior
Show a bar in-game, next to the gold (default location) that tracks level in rewards path, and current progress.

### Actual Behavior
Experience counter does not show.

### Steps to reproduce behavior
None known.
HSDT has been reset and reinstalled multiple times, and it's the only thing not working.

**Comment by AstroNauta21** [comment] 2023-05-28 12:51
yep, already wrote in this post:

https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/4443

Hope this issue can be solved

**Comment by beheh** [comment] 2024-06-25 08:21
Duplicate of #4443

**Closed by beheh** 2024-06-25 08:21 UTC
