### ISSUE TITLE
Not adding games in Arena.

### ISSUE THREAD

**Issue by bombek92** [HearthSim/Hearthstone-Deck-Tracker#2570] opened 2016-06-03 06:52 UTC
Hi,

Yesterday on my arena run there were issues with HTD (on newest version). Firstly the games didn't record so I had to manually "add game" in arena run, secondly when I was at 5-2 and I won the game the record moved to 4-2 instead of 6-2. What was really strange.

Anyone discovered something like this?

Edit: Also it just crossed my mind that seret list which appear when enemy play a secret didn't appeared as well.

**Comment by Epix37** [comment] 2016-06-03 09:39
Please post the hdt logs when you see this happening the next time. See here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by bombek92** [comment] 2016-06-03 10:09
Thank you for your response. I attached the logs. Look at the time 13:34.

"13:34:59|Info|GameEventHandler.HandleLoss >> --- Game was lost! ---
13:34:59|Info|TurnTimer.Stop >> Stopping turn timer
13:34:59|Info|GameEventHandler.HandleGameEnd >> Game ended...
13:34:59|Info|GameStats.GameEnd >> Current Game ended after 9 turns
13:34:59|Info|GameEventHandler.HandleGameEnd >> Assigned current game to deck: Arena 02-06 12:04
13:34:59|Info|GameEventHandler.HandleGameEnd >> Waiting for game mode to be saved to game...
13:35:08|Info|GameV2.CurrentMode >> DRAFT
13:35:08|Info|GameEventHandler.HandleInMenu >> Game is now in menu.
13:35:08|Info|OverlayWindow.Update >> Refreshed overlay topmost status
13:35:08|Info|GameEventHandler.SaveAndUpdateStats >> Gamemode None is not supposed to be saved. Removed game from Arena 02-06 12:04 (Rogue).
13:35:14|Info|GameEventHandler.HandleGameEnd >> Game mode was saved, continuing.
13:35:14|Info|HearthStatsManager.UploadMatchAsync >> trying to upload match: Loss vs Paladin, 2016-06-02 13:29:13
13:35:14|Warning|HearthStatsAPI.IsValidGame >> Game Loss vs Paladin, 2016-06-02 13:29:13 is not valid (invalid game mode: None)"

[hdt_log_1464937078.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/297375/hdt_log_1464937078.txt)

**Comment by Epix37** [comment] 2016-06-03 10:21
Try running HDT as admin.

**Comment by riQQ** [comment] 2017-09-30 00:04
Same cause as #2570.

**Comment by riQQ** [comment] 2018-11-29 23:44
Duplicate of #2738

**Closed by riQQ** 2018-11-29 23:44 UTC
Labels: HearthMirror
