### ISSUE TITLE
[BUG] Does not recognize DK Paladin as Paladin Class for stats [WILD]

### ISSUE THREAD

**Issue by jnpablodi** [HearthSim/Hearthstone-Deck-Tracker#3572] opened 2018-02-24 05:21 UTC
### Expected Behavior
Matchup against player using DK Paladin should show as "VS Paladin" on stats

### Actual Behavior
Stats show class as "other", matches list is empty for both "Class" and "VS"

**Comment by riQQ** [comment] 2018-02-24 08:43
Can you provide the hdt log file at the time this happened? (https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues#hdt-log-files)

**Comment by riQQ** [comment] 2018-03-07 18:46
Duplicate of #3398

**Closed** 2018-03-07 18:46 UTC
Labels: duplicate
