### ISSUE TITLE
Keeps switching to No Deck Mode

### ISSUE THREAD

**Issue by Andrew-Usher** [HearthSim/Hearthstone-Deck-Tracker#4537] opened 2024-03-20 08:28 UTC
### Expected Behavior

I expect when I select the deck manually, it should keep that deck active.

### Actual Behavior

Tracker deselects my deck and returns to no deck mode, only tracking cards it's seen.

### Steps to reproduce behavior

I assume it's the Tradable keyword which is doing this; run any card with tradable.

**Comment by beheh** [comment] 2024-03-20 09:23
Thanks for your report! Are you running a Whizbang deck by any chance? We have some specific logic around him that could cause this.

**Comment by beheh** [comment] 2024-03-20 21:34
We've since seen further reports about this and are investigating. One of the affected decks seems to be this one: `AAEBAZICBIW4AsX9ArD6Bb6ZBg2kB4oOj/YC8NQDr4AErp8EuaAErsAEgdQEoukF/Y0GqZ4GmqAGAAA=`

**Comment by Andrew-Usher** [comment] 2024-03-22 07:58
@beheh  Attached is a recorded game where I experienced the issue described.

**Comment by Andrew-Usher** [comment] 2024-03-22 11:03
[https://drive.google.com/drive/u/0/folders/1tpXiRZwVxeuyjmc2OD1sZ2oBbnMe1bk2](url)

**Comment by beheh** [comment] 2024-03-28 18:24
@Andrew-Usher Is this still happening to you? We're struggling to reproduce this on our end.

**Comment by RohanHinton** [comment] 2024-03-30 07:40
Happening nearly every game when I use the Plaguebringer loaner deck.

**Comment by Luaccs** [comment] 2024-04-08 02:23
> Happening nearly every game when I use the Plaguebringer loaner deck.

Same here, anything else and it seems to be fine

**Comment by beheh** [comment] 2024-04-08 10:02
Thanks, we'll continue investigating!

**Comment by bmitzel** [comment] 2024-05-26 16:56
I'm not sure if this additional info will help at all, but this happens to me 100% of the time upon clicking the Play button in Hearthstone. HDT immediately auto-enables No-Deck Mode every single time. This has been going on for 10+ games now, across 5 different Standard decks, all of which I manually created as New decks from within HDT. The 5 decks are all from the pool of Hearthstone's Loaner Decks, and I've included their links below. This is all on a fresh install of HDT v1.28.3 on a Windows 10 PC that had never had HDT installed on it previously.

[Rise of the Earthen](https://hsreplay.net/decks/FVQBYuCRo0jrnsUcxWouCd/)
[Wishing for a Win](https://hsreplay.net/decks/MV6u2MWtWWRzrZDNpvYulh/)
[Holli'dae Break](https://hsreplay.net/decks/UDk7FBF77QnAHrVh6fVQuh/)
[Sludge-Covered Slugfest](https://hsreplay.net/decks/Ey9sQ43p2yvHneoShY8KXb/)
[Odyn's Aegis](https://hsreplay.net/decks/ELvgLsuEdW8P5FObtOPaib/)

**Comment by beheh** [comment] 2024-05-31 19:26
This is fixed in https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/5b65587604c3bd9c7c9075d0c2f51f6446391b58 and loaner decks will be automatically imported in the upcoming HDT version.

**Closed by beheh** 2024-05-31 19:26 UTC
Labels: bug
