### ISSUE TITLE
Error uploading replays in app, SSL protocol error on site.

### ISSUE THREAD

**Issue by Endorphine71** [HearthSim/Hearthstone-Deck-Tracker#4374] opened 2022-01-05 09:25 UTC
### Expected Behavior
Upload Replays

### Actual Behavior
Get error message:
Error uploading replay.
Please Try Again Later.

### Steps to reproduce behavior
Click on Replay and get a red error message window at the top of the application.

I was also getting this same error when trying to access the website in Chrome.  After I cleared the cache it is working again.  I uninstalled hsreplay app and also Hearthstone after cleaning everything up.  Still won't let me upload any replays.  Started happening around 6 days ago.  I see others were also getting this error and posted on the SubReddit:  https://www.reddit.com/r/hsreplay/comments/rvus9d/issues_accessing_hsreplay/

In the logs:  System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: The handshake failed due to an unexpected packet format.

[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/7813678/hdt_log.txt)

**Comment by Endorphine71** [comment] 2022-01-05 09:30
I also just tired logging out and back in getting a new token and got:

HSReplay.net Error

Could not load HSReplay.net account status.  Please try again later.
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/7813719/hdt_log.txt)

**Comment by Endorphine71** [comment] 2022-01-05 09:56
Strange behavior... I played another game.. then clicked to upload.. same error.. then clicked on it 4-5 times fast and it finally went.  Here are the logs....

[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/7813882/hdt_log.txt)

**Comment by malakada** [comment] 2022-01-05 18:25
I've been experiencing this for a few days now. I am completely unable to access `https://hsreplay.net` on Firefox or Chrome. This causes my tracker to not connect, despite me paying for a ✨premium account✨. 💁‍♀️ The error I get in the web browser is this:

![image](https://user-images.githubusercontent.com/992688/148268216-b6316f04-14cb-4242-a38c-8a5c1c2cd073.png)

(text from image below for screenreaders/accessibility, it should be noted as well in the screenshot that the URL is listed as `https`, yet the browser is warning me that the page is not secure within the URL bar)

> Secure Connection Failed
> 
> An error occurred during a connection to hsreplay.net. SSL received a record that exceeded the maximum permissible length.
> 
> Error code: SSL_ERROR_RX_RECORD_TOO_LONG
> 
> * The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
> * Please contact the website owners to inform them of this problem.
> 
> [Learn more...](https://support.mozilla.org/1/firefox/95.0.2/WINNT/en-US/connection-not-secure)

So, I'm an engineer right? 😅 I thought it was my firewall because it said that it was up when I checked downdetector.com or whatever it's called. So I tried adding `hsreplay.net` to the whitelist, and when that didn't work I turned it completely off. Still couldn't access `https://hsreplay.net`. 

Then I thought "maybe it's my router? or something on my network?" so I did a `tracert hsreplay.net`, and here are the results:

```
> tracert hsreplay.net

Tracing route to hsreplay.net [172.67.73.29]
over a maximum of 30 hops:

  1    <1 ms    <1 ms    <1 ms  router.asus.com [192.168.1.1]
  2     6 ms     7 ms     7 ms  [redacted]
  3     7 ms     8 ms     8 ms  [redacted]
  4     9 ms     7 ms    10 ms  [redacted]
  5    23 ms    20 ms    19 ms  langbprj01-ae1.rd.la.cox.net [68.1.1.13]
  6    20 ms    21 ms    22 ms  72.215.224.171
  7    19 ms    19 ms    20 ms  172.70.212.2
  8    21 ms    19 ms    19 ms  172.67.73.29

Trace complete.
```

....probably doxing myself with some of those IP's (I'm not a network engineer 😬), so I redacted the ones between obvious home IP and when it hit my ISP successfully and continued on from there.

When I navigate directly to `172.67.73.29` I land on cloudflare's page that tells me this:

> Error 1003 Ray ID: 6c8eb9a9f8427cec • 2022-01-05 18:21:15 UTC
> Direct IP access not allowed

And, of course, when I check out [MXToolbox](https://mxtoolbox.com/SuperTool.aspx?action=a%3ahsreplay.net&run=toolpage) I can see that the IP that I land on with my `tracert` is the correct IP. I'm getting there, but something is still wrong with the SSL header.

At this point, I feel fairly certain that "it's you, not me" is likely correct here.

I'd like to contact customer service to put my account on hold until this resolves, but I can't access the webpage to even ask that they stop charging me. :joy:

If there's any extra info or debugging I can assist you with, please let me know. You can contact me via my email: malakjanus@gmail.com (which is tied to this github account).

Cheers, and best wishes in the new year!

Malak

**Comment by azeier** [comment] 2022-01-05 20:04
Thanks for the detailed info @malakada! We'll be reaching out via email regarding your subscription.

We are actively investigating the issue. 

Our current theory is that this is a problem related to certain routers using an automated blacklist from`global.sitesafety.trendmicro.com`, where `https://hsreplay.net` was mistakenly listed as a phishing site. It looks like we managed to get that fixed within in the last couple of hours. I am unsure how long this will take to propagate, but hopefully this was the root cause and the issue should be resolved soon.

**Comment by malakada** [comment] 2022-01-05 21:18
Looks like it propagated rather quickly on my end! I'm able to reach `https://hsreplay.net` again! Also, it looks like the games recorded while I was unable to reach the service were able to upload. 😌 

Thanks for the speedy reply, from my end I'd consider the SSL issues resolved. 👍 Great work team! 🎉

**Comment by Endorphine71** [comment] 2022-01-05 22:01
Thanks for the update.  The one thing I forgot to check was the anti-virus on my AX11000 router.  Ugh.

Yep, it was detecting the site as phishing.  Thanks for the quick fix! :)

**Comment by azeier** [comment] 2022-01-05 22:20
Glad to hear this resolved quickly!

**Closed by azeier** 2022-01-05 22:20 UTC
