### ISSUE TITLE
Plague Counter when Helya is already played

### ISSUE THREAD

**Issue by Paul-Cdrt** [HearthSim/Hearthstone-Deck-Tracker#4555] opened 2024-06-02 19:27 UTC
### Expected Behavior

I play Death Knight
I play Helya, making the plague unending and giving 3 plagues to the opponent (1 of each)
A plague in the enemy deck is drawn.
It is not destroy and goes back into the deck.

The deck helper shows now 4 plague in the enemy deck.

### Actual Behavior

The deck helper should shows 3 plague in the enemy deck, not 4
The bug occurs also with more than 3 plagues.
So each time a plague is drawn, a plague is added to the counter from the deck helper (showing enemy deck)

**Comment by beheh** [comment] 2024-07-12 08:53
Duplicate of #4498

**Closed by beheh** 2024-07-12 08:53 UTC
Labels: bug
