### ISSUE TITLE
Shadow Reflection bug(s?)

### ISSUE THREAD

**Issue by Dushku** [HearthSim/Hearthstone-Deck-Tracker#3440] opened 2017-10-06 05:30 UTC
## Bug report
I've been playing a deck with Valeera the Hollow exclusively since KFT. I have noticed several bugs regarding the Shadow Reflection card she gives you with HDT. One of which, I had reported before (attack counter not accounting for minions played via Shadow Reflection). One of which I had posted on the addon Graveyard's page, that I now believe to be a problem with HDT itself. And now this new issue...

### Expected Behavior
Cards played via Shadow Reflection should be tracked as the cards that they are.

### Actual Behavior
1 Attack Counter will never consider minions played via Shadow Reflection.
2 Minions played via Shadow Reflection that are killed are not considered as having died. Hence why the addon Graveyard isn't displaying them even though N'Zoth will resurrect Shadow Reflected deathrattles for example.
3 **Minions played via Shadow Reflection are calculated as if they are spells. Both in the context of Mage secrets and spell counter (see screenshots below).**

### Steps to reproduce behavior
Play a minion via Shadow Reflection.

### Log/Screenshots
https://i.imgur.com/qwGEzAn.jpg
https://i.imgur.com/Y7GNh3L.jpg (Valeera the Hollow is in play via turn 7 Preparation -> Mimic Pod -> Counterfeit Coin)

**Comment by Zawodowiec1532** [comment] 2017-10-06 09:34
Duplicate of your other issue: #3396 
Anyway, thanks for your report and additional info.
It will be fixed Soon™.

**Comment by Dushku** [comment] 2017-10-06 10:17
For clarification purposes, I wanted to point out that this is NOT a duplicate. While I have reiterated the other issue mentioned, this issue offers new insight in that minions are treated as spells. My apologies if it would've been preferred that I add to that one.

**Comment by azeier** [comment] 2017-10-22 10:52
Fixed with https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/f48fcae3084d350d5b2c5450ba56cef8966916e3

**Closed by azeier** 2017-10-22 10:52 UTC
Labels: bug, decktracker
