### ISSUE TITLE
Collection doesn't upload, logs get spammed

### ISSUE THREAD

**Issue by moopypieloopy** [HearthSim/Hearthstone-Deck-Tracker#4071] opened 2020-05-12 21:14 UTC
### Expected Behavior
I expect the deck collections to upload and the overlays to work

### Actual Behavior
Deck collection is not uploaded, no overlays, slow computer performance due to deck tracker's logs being constantly written to with an error message.

### Steps to reproduce behavior
I launch hearthstone, and I launch deck tracker as admin. 

### Log/Screenshots

[hdt_log_1589315476.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/4618490/hdt_log_1589315476.txt)

This message is written to the log file over and over as long as deck tracker is running:
4:27:20 PM|Warning|Core.Initialize >> HearthMirror Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.BitConverter.ToInt32(Byte[] value, Int32 startIndex)
   at HearthMirror.ProcessView.GetExport(String name)
   at HearthMirror.Mirror.get_Root()
   at HearthMirror.Reflection.GetAccountIdInternal()
   at HearthMirror.Reflection.TryGetInternal[T](Func`1 action, Boolean clearCache)
4:27:21 PM|Info|LogWatcherManager.OnLogFileFound >> LoadingScreen
4:27:22 PM|Warning|Core.Initialize >> HearthMirror Exception: System.ArgumentNullException: Value cannot be null.

**Comment by zijiewu3** [comment] 2020-05-12 21:55
I have the same issue.

**Comment by Richelieu77** [comment] 2020-05-12 22:22
Same repeated error message in log, tracker won't upload new deck/recognize old decks.  This is still happening after (1) restarting computer, (2) uninstalling the tracker, (3) deleting all tracker Appdata folders, and (4) fresh install of the tracker.  It began about an hour ago after I created a new deck.

**Comment by moopypieloopy** [comment] 2020-05-12 22:37
Like Richelieu77, I have followed the wiki steps. I have also uninstalled/reinstalled Hearthstone/battleNet/Deck Tracker. I have wiped out the AppData folders after the uninstall. Everything installs properly but the logs are spammed as soon as Hearthstone is launched. It also cripples the ability to click around the interface/menus of the tracker until Hearthstone is closed.

**Comment by alterNERDtive** [comment] 2020-05-13 00:07
For me, the tracker is freezing completely whenever I start a game. Log gets spammed with the same error message.

**Comment by Venaseph** [comment] 2020-05-13 02:24
Same here, something is amiss

**Comment by jcam61** [comment] 2020-05-13 04:04
Same issue.

**Comment by RaulBaldoy** [comment] 2020-05-13 12:07
Same issue

**Comment by ScroungerHS** [comment] 2020-05-13 12:35
Same here. But I have additions to add. In addition to the decks not updating when in the play menu, any decks that are made and imported, they do not track when playing a game. Plus, opponents' decks do not track when in game. There is also now considerable lag when opening the constructed stats. And one more thing, the tracking for galakrond/c'thun/spells played etc, they are stuck at 1/1 or 6/6 with respect to each of their own.

I also exhausted the three options listed as a fix for this, the copying and pasting of the log file, the inclusion of the game path, and the uninstall+full deletion and then fresh install.

Additionally, I have deck tracker installed on two completely separate computers. Both were functioning just fine until yesterday(5/12/2020), both are now completely non functional.

**Comment by slickag** [comment] 2020-05-13 13:05
Likely caused by the last HS patch yesterday. Probably will get fixed pretty soon.

**Comment by MxBrst** [comment] 2020-05-13 13:06
Same issue

**Comment by bunny-creater** [comment] 2020-05-13 15:37
I have the same issue.

**Comment by RaulBaldoy** [comment] 2020-05-14 17:04
Fixed the bug with v1.12.0

**Comment by nathanmchoi** [comment] 2020-05-15 17:40
Working for me now on 1.12.0.

**Closed** 2020-05-17 10:13 UTC
Labels: bug
