### ISSUE TITLE
Count number of deathrattle dead minions for N'Zoth

### ISSUE THREAD

**Issue by GaryKing** [HearthSim/Hearthstone-Deck-Tracker#2471] opened 2016-05-04 19:39 UTC
Perhaps add a counter for N'Zoth? Since we have one for C'Thun and Yogg as well.

If HDT sees that we have N'Zoth in our deck, then show a counter during the game, which keeps track of the number of deathrattle minions that died. 

Yes I know that we can just check our deck list for this, ultimately, but there are some cases where it's useful. For instance, of course it's easier to see the counter than to count the minions, especially when we can't recall if we had two Harvest Golems or one in our deck, and only one died, or when we discovered deathrattle minions from the Museum Curator, etc.

It's particularly useful for when we only want to play N'Zoth to get full value, so we wait for the counter to hit 6, and then we know that we'll get a full board when we play him.

**Comment by culinko** [comment] 2016-05-04 21:21
Duplicate of #2439. This will probably be implemented only as #868, though.

**Closed by culinko** 2016-05-04 21:21 UTC

**Comment by izogfif** [comment] 2016-06-27 01:48
This is how I have implemented it. You might need to add line
`    <string>Dead deathrattle minions counter</string>`
in your 
`c:\Users\USERNAME\AppData\Roaming\HearthstoneDeckTracker\config.xml`
file before lines
`  </PanelOrderOpponent>`
and
` </PanelOrderPlayer>`
[dead_deathrattle_minions.zip](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/333975/dead_deathrattle_minions.zip)
