### ISSUE TITLE
Opponents in Stats are by Class Only, not type, i.e. "Shaman" not "Midrange Shaman" (Pic attached)

### ISSUE THREAD

**Issue by eversor431** [HearthSim/Hearthstone-Deck-Tracker#2891] opened 2016-10-15 15:14 UTC
Hi,

I used this program a long time ago and just recently got a laptop that can run it (was playing on tablet).

I love the software; great work!

However, I thought you were able to classify your opponents manually/automatically i.e. did I play against agrro midrange or control shaman? I can't figure out how to do that. I've manually added them with the "note" function below.

Not sure if it's related, but there's a "select deck" button in the options for a match in Stats which does nothing when I click on it. There doesn't seem to be any space for what type of deck opponent was running i.e. categorically. It's great that it is recorded and you can see it, but I'd love to be able to see my winrate against not just "shaman" but against aggro or midrange etc.

I downloaded the software from your website a few days ago and it updated with the recent HS patch this week.

Thanks for your help,
eversor431

![image](https://cloud.githubusercontent.com/assets/15005423/19411094/98000ed4-92c8-11e6-9fc6-5a6483b1c35b.png)

**Comment by culinko** [comment] 2016-12-25 09:35
Duplicate of #2879.

**Closed by culinko** 2016-12-25 09:35 UTC
