### ISSUE TITLE
Can't choose Shieldbearer as an arena reward, HDT doesn't recognize the card.

### ISSUE THREAD

**Issue by zcythustk** [HearthSim/Hearthstone-Deck-Tracker#3403] opened 2017-09-02 09:32 UTC
### Actual Behavior
Can't choose Shieldbearer as an arena reward, HDT doesn't recognize the card.

### Log/Screenshots
https://scontent.fbkk1-4.fna.fbcdn.net/v/t35.0-12/21329743_10211955663985223_654563748_o.png?oh=2fbc3d43f2402a690a043638b2ab07c5&oe=59AD338F

**Comment by riQQ** [comment] 2017-09-02 10:19
Duplicate of #3394.

**Closed** 2017-09-02 10:20 UTC
