### ISSUE TITLE
Merging old with new

### ISSUE THREAD

**Issue by PuppetMaster000** [HearthSim/Hearthstone-Deck-Tracker#3072] opened 2017-01-11 20:44 UTC
Hi there, first time posting so excuse me if I am not formal.

I haven't found this issue or question anywhere so I would like to ask about it. Basically I updated my PC and it has new windows and hard drive and all that, but while waiting for my previous hard drive to be examined from the IT guys (it was damaged) I still used a fresh newly installed Deck Tracker. Now what I want to do is basically merge the new data and statistics from that one with the stats that I have from the previous hard drive. I have both files from the AppData, Local and Roaming, but how do I merge them without losing anything on either of them? Especially since some decks are completely the same but with different stats.

**Comment by PuppetMaster000** [comment] 2017-01-14 14:45
Anyone know anything?

**Comment by riQQ** [comment] 2017-01-14 14:59
You can do this by manually editing the XML files, but it's probably not that easy.

**Comment by PuppetMaster000** [comment] 2017-02-06 03:54
Sorry had exams so I didn't respond for a while. I understand that it wouldn't be easy but I really want all of my progress so any additional input would be appreciated?

**Comment by jleclanche** [comment] 2017-02-06 06:37
@PuppetMaster000 if you're concerned with the hsreplay.net stats those can be merged very easily. It's just the local ones that are hard.

**Comment by PuppetMaster000** [comment] 2017-02-06 07:01
Since I have the backup from both, can I connect both profiles to the website you mentioned and then merge them that way?

**Comment by jleclanche** [comment] 2017-02-06 07:16
Yes, if you log in with the same account, that's what will happen. Your replays will be under the same account.

The local data (decks) are not mergeable yet tho :(

**Comment by PuppetMaster000** [comment] 2017-02-06 09:59
Awh man, and I want my deck progress too :(

**Comment by jleclanche** [comment] 2017-02-06 10:03
Can you email your config files to contact@hearthsim.info? I'll see what I can do.

**Comment by PuppetMaster000** [comment] 2017-02-06 10:05
config.xml? sure thing, sending over right away! Thanks man :)

**Comment by jleclanche** [comment] 2017-02-06 10:07
Yeah, both the old and new ones. I'll take a look at them tomorrow see if there's a way to merge them.

**Comment by PuppetMaster000** [comment] 2017-02-17 16:14
Any progress? ^^

**Comment by PuppetMaster000** [comment] 2017-03-06 22:25
Gonna try bump this one more time and hope I get something, been a month since I last heard some info :(

**Comment by judge2020** [comment] 2017-06-10 03:53
closing in favor of #3235, should handle merging stats

**Closed by judge2020** 2017-06-10 03:53 UTC
Labels: stats, support

**Comment by judge2020** [comment] 2017-07-19 20:48
duplicate of #3235
