### ISSUE TITLE
Arena HearthStats sync not syncing prizes

### ISSUE THREAD

**Issue by scottrick** [HearthSim/Hearthstone-Deck-Tracker#2452] opened 2016-05-01 17:09 UTC
Gold rewards aaren't synced to the HearthStats website.  Maybe dust as well, but not sure.

**Comment by jleclanche** [comment] 2016-05-01 17:18
Dupe of #2380

**Closed by jleclanche** 2016-05-01 17:18 UTC

**Comment by riQQ** [comment] 2016-05-01 22:19
Not a dupe of #2380.

**Comment by scottrick** [comment] 2016-05-02 14:59
Yeah, this doesn't look like a duplicate.

**Comment by scottrick** [comment] 2016-05-02 15:00
Maybe it was fixed at the same time, though.
