### ISSUE TITLE
hearthstone deck tracker crashing every time I launch hearthstone

### ISSUE THREAD

**Issue by Empowerment2017** [HearthSim/Hearthstone-Deck-Tracker#3285] opened 2017-06-08 02:15 UTC
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Hearthstone_Deck_Tracker.Importing.DeckImporter.GetConstructedDecks()
   at Hearthstone_Deck_Tracker.Importing.DeckImporter.get_ConstructedDecksCache()
   at Hearthstone_Deck_Tracker.LogReader.Handlers.FullScreenFxHandler.AutoSelectDeckById()
   at Hearthstone_Deck_Tracker.LogReader.Handlers.FullScreenFxHandler.Handle(LogLineItem logLine, IGame game)
   at Hearthstone_Deck_Tracker.LogReader.LogReaderManager.ProcessNewLines()
   at Hearthstone_Deck_Tracker.LogReader.LogReaderManager.<StartLogReaders>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Empowerment2017** [comment] 2017-06-08 02:38
I tried running HDT as admin, but HDT still crashes every time I launch it.

**Comment by riQQ** [comment] 2017-06-08 06:22
Stacktrace is the same as #3267. Which version of HDT are you using?

**Comment by Empowerment2017** [comment] 2017-06-08 06:30
1.3.5

**Comment by azeier** [comment] 2017-06-08 08:34
Try reinstalling HDT. The only way this crash could happen on 1.3.5 is if one of the libraries didn't get updated.

**Comment by riQQ** [comment] 2017-09-22 19:05
Duplicate of #3267

**Closed by riQQ** 2017-09-22 19:05 UTC
Labels: crash, duplicate
