### ISSUE TITLE
Account

### ISSUE THREAD

**Issue by dechbo** [HearthSim/Hearthstone-Deck-Tracker#3281] opened 2017-06-06 19:31 UTC
Are there anyway to save your data and decks on and account and move them between computers. I play on 4 different PCs and would like to have my win/lose stats with me.

Is that possible

**Comment by judge2020** [comment] 2017-06-07 00:54
Closed in favor of #3235

**Closed by judge2020** 2017-06-07 00:54 UTC

**Comment by judge2020** [comment] 2017-07-19 20:48
duplicate of #3235
