### ISSUE TITLE
Defender of Argus does not change stats of units it was placed beside in Replay

### ISSUE THREAD

**Issue by BVA64** [HearthSim/Hearthstone-Deck-Tracker#540] opened 2015-01-06 22:20 UTC
https://www.mediafire.com/?xf2107dyzt1bzcz

Turn 13: Opponent summons Silver Hand Recruit and plays Defender of Argus. From that point on the SHR should have been shown as a 2/2 with Taunt but it was shown as a 1/1.

The log of the tracker: http://pastebin.com/JcMP7X23 The HS log was deleted. :(

**Comment by Epix37** [comment] 2015-01-10 09:07
On turn 19, the unit is just not updated until the following attack by the peacekeeper, same as turn 21. That's to be expected since triggers are not included in the replay and happen after summons/plays.

Not really sure what the issue with defender of argus might be. The original log now being included in the replays should help us figure this out.

**Comment by anonymous555** [comment] 2015-01-11 14:55
The behavior looks like a general problem, stat boosts are applied in the NEXT action, not during the spell/summon action in which their effects would occur as viewed by the player.

**Comment by Epix37** [comment] 2015-01-11 14:57
Yes, that's just how it currently works. The issue is though, that buffs are sometimes not appearing at all.

**Comment by judge2020** [comment] 2016-11-17 15:35
This is an old issue regarding replays which are now not maintained. Also, HSreplays.net does update the minion's stats when Argus is played.

**Comment by jleclanche** [comment] 2016-11-17 15:42
Yeah this is no longer maintained. Closing.

**Closed by jleclanche** 2016-11-17 15:42 UTC
Labels: bug, replays
