### ISSUE TITLE
Arena Game tracking not working

### ISSUE THREAD

**Issue by radryan** [HearthSim/Hearthstone-Deck-Tracker#2677] opened 2016-07-15 00:13 UTC
The app will import arena decks correctly and it will show the record correctly. If I choose stats, arena, runs and matches there is nothing there. Its like the arena run/deck doesnt exist.

**Comment by pagem** [comment] 2016-07-15 15:40
Duplicate of #2653 ?

**Closed** 2016-08-10 07:03 UTC
Labels: duplicate
