### ISSUE TITLE
Direhorn Hatchling always appears created

### ISSUE THREAD

**Issue by mSterian** [HearthSim/Hearthstone-Deck-Tracker#3656] opened 2018-04-24 08:02 UTC
Direhorn Hatchling always appears as being created in opponent's hand rather than being drawn.

To reproduce just play against someone with Direhorn Hatchlings in the deck.
When he plays the Hatchling that was drawn, Deck Tracker shows it with the "created" icon even though it was not created by another card.

**Comment by riQQ** [comment] 2018-04-24 17:12
Duplicate of #3644

**Closed by riQQ** 2018-04-24 17:12 UTC
