### ISSUE TITLE
Rampage card not listed in possible cards included for an arena reward

### ISSUE THREAD

**Issue by alex4tino** [HearthSim/Hearthstone-Deck-Tracker#3407] opened 2017-09-04 03:24 UTC
The title ans this image say it all.

![image](https://user-images.githubusercontent.com/31606659/30010601-e99f1610-90fe-11e7-9788-c3f0d764e563.png)

**Comment by jleclanche** [comment] 2017-09-04 05:06
Duplicate of #3394.

**Closed by jleclanche** 2017-09-04 05:06 UTC
