### ISSUE TITLE
Mulliganed cards are being ordered wrong in the deck list

### ISSUE THREAD

**Issue by g0rill4z** [HearthSim/Hearthstone-Deck-Tracker#3561] opened 2018-02-06 22:53 UTC
### Expected Behavior

Cards I mulligan should be reordered in the list with respect to their mana cost or alphabetically. 

### Actual Behavior

Cards that cards that are just included one time (or you draw both) are not being ordered properly. 

### Steps to reproduce behavior

Enable removing grayed-out cards in the Deck Tracker. Mulligan a card that's just included once. I found this bug a long time ago while playing Big Priest.

### Log/Screenshots

![image](https://user-images.githubusercontent.com/20730726/35888513-2fb72e44-0b98-11e8-8f78-dca255f4348f.png)
(Shadowreaper Anduin should be between Free From Amber and The Lich King)

**Comment by riQQ** [comment] 2018-02-06 22:54
Duplicate of #3397

**Closed by riQQ** 2018-02-06 22:54 UTC

**Comment by riQQ** [comment] 2018-02-10 19:58
Duplicate of #2649
