### ISSUE TITLE
Whizbang imports old decks/recipes

### ISSUE THREAD

**Issue by ceceita** [HearthSim/Hearthstone-Deck-Tracker#4516] opened 2023-11-23 18:37 UTC
### Expected Behavior

Whizbang to import last deck/recipes

### Actual Behavior

Whizbang imports old deck/recipes

### Log/Screenshots

![whizbad](https://github.com/HearthSim/Hearthstone-Deck-Tracker/assets/15253437/10952e22-4a77-45e7-b4bd-767c433ff393)

**Comment by ceceita** [comment] 2023-11-23 18:43
with last patch blizzard finally fix a old bug where whizbang was working with 6 recipes every class making the importer always fail , now hearthstone correctly works with only last 2 recipes for every class but the HDT deck tracker is still importing old recipes .

Back in august @beheh  updated it , i think there is something to change here
https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/5353e8fa287458edc59d6a5ce71caa5d67404a3b

**Comment by beheh** [comment] 2023-12-16 01:20
Duplicate of #4046

**Closed by beheh** 2023-12-16 01:20 UTC
Labels: bug
