### ISSUE TITLE
Deck Tracker stopped working after hitting Legend

### ISSUE THREAD

**Issue by donggiring** [HearthSim/Hearthstone-Deck-Tracker#3799] opened 2018-10-04 08:16 UTC
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2445458/hdt_log.txt)
[hdt_log_1538640503.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2445459/hdt_log_1538640503.txt)

here is my log
 deck tracker stop

**Comment by TheCat93** [comment] 2018-10-04 09:12
I have the same problem

**Comment by azeier** [comment] 2018-10-04 15:39
Duplicate of #3798

**Closed by azeier** 2018-10-04 15:39 UTC
