### ISSUE TITLE
Random HDT Crash after various play modes

### ISSUE THREAD

**Issue by ScottAllen11** [HearthSim/Hearthstone-Deck-Tracker#3113] opened 2017-02-23 22:54 UTC
## Bug report
HDT unexpectedly crashed during a ranked play session on EU server, shortly after a successful tavern brawl (also on EU), with a rogue deck as I recall. I usually play on NA, where I have a different rogue deck.

### Expected Behavior
HDT doesn't crash during the match.

### Actual Behavior
HDT unexpectedly crashes mid-game and terminates.

### Steps to reproduce behavior
Issue is intermittent. Seems more frequent when I am playing on off servers (EU, Asia) and thus rarely played decks.

### Log/Screenshots
[hdt_log_1487864024.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/797923/hdt_log_1487864024.txt)
Windows Event Viewer:
Application: HearthstoneDeckTracker.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OutOfMemoryException
   at System.IO.FileStream.Read(Byte[], Int32, Int32)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.get_EndOfStream()
   at Hearthstone_Deck_Tracker.LogReader.LogReader.ReadLogFile()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

Faulting application name: HearthstoneDeckTracker.exe, version: 1.1.6.1, time stamp: 0x58971953
Faulting module name: KERNELBASE.dll, version: 10.0.14393.479, time stamp: 0x58256d37
Exception code: 0xe0434352
Fault offset: 0x000da832
Faulting process id: 0x1240
Faulting application start time: 0x01d28afc2b523f82
Faulting application path: C:\Users\Scott\AppData\Local\HearthstoneDeckTracker\app-1.1.6.1\HearthstoneDeckTracker.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 5c65069d-beb1-4e6a-ae99-1e2431700e1d
Faulting package full name: 
Faulting package-relative application ID:

**Comment by riQQ** [comment] 2017-02-23 23:11
Duplicate of #3054.

**Comment by judge2020** [comment] 2017-06-10 03:38
closed in favor of #3054

**Closed by judge2020** 2017-06-10 03:38 UTC
Labels: duplicate
