### ISSUE TITLE
Direhorn Hatchling death

### ISSUE THREAD

**Issue by Chachos713** [HearthSim/Hearthstone-Deck-Tracker#3647] opened 2018-04-18 12:17 UTC

**Comment by Chachos713** [comment] 2018-04-18 12:18
When a direhorn hatchling dies, it adds the matriarch to the deck list. It also readds the htachling to the list.

**Comment by riQQ** [comment] 2018-04-18 20:16
Duplicate of #3644

**Closed by riQQ** 2018-04-18 20:16 UTC
