### ISSUE TITLE
Suggestion: Stats - Mass Edit

### ISSUE THREAD

**Issue by GiggliG** [HearthSim/Hearthstone-Deck-Tracker#2465] opened 2016-05-03 04:54 UTC
In my match history, I have around 1100 games that predate the time HDT stored region data, so they are listed as Unknown.

For a lot of these I can identify which server they were played in. but going through and manually editing them one by one is a lot of work (1100 games remember!).

It would be great if HDT had "Mass Edit" button, you chose a field (like server), change it, click OK, and it changes that field in all the currently selected games.

**Comment by culinko** [comment] 2016-05-03 10:22
Dupe of #967.

**Closed by culinko** 2016-05-03 10:22 UTC
