### ISSUE TITLE
Faceless Manipulator not a valid card name to enter in Arena Rewards screen

### ISSUE THREAD

**Issue by cameronneil** [HearthSim/Hearthstone-Deck-Tracker#3405] opened 2017-09-03 00:12 UTC
## Bug report
Received a Faceless Manipulator as an Arena reward. HS Deck Tracker would not allow me to add that card.
### Expected Behavior
"Faceless Manipulator" is a valid card name to add to Arena rewards.

### Actual Behavior
"Faceless Manipulator" not recognized.
![hsdtbug](https://user-images.githubusercontent.com/6542755/29999534-aa8060b8-9001-11e7-8a0f-908fb4cd2707.png)

### Steps to reproduce behavior
Attempt to add "Faceless Manipulator" when inputting Arena Rewards after a run.

**Comment by riQQ** [comment] 2017-09-03 01:20
Duplicate of #3394.

**Comment by jleclanche** [comment] 2017-09-04 05:05
Dupe of #3394.

**Closed by jleclanche** 2017-09-04 05:05 UTC
