### ISSUE TITLE
Stats are added in Spectator Mode

### ISSUE THREAD

**Issue by kaskoscuro** [HearthSim/Hearthstone-Deck-Tracker#3343] opened 2017-07-30 12:04 UTC
### Expected Behavior
Don't add Spectator matches to statistics if the option "Spectator" is disabled.

### Actual Behavior
After seeing a friend's match in Spectator Mode, his match is added to my selected deck's statistics. The option "Spectator" was disabled.

![image](https://user-images.githubusercontent.com/29385381/28753118-460ca098-752f-11e7-8eca-ffccb661ea76.png)

### Steps to reproduce behavior
- Select the deck. In my case a priest deck.
- Go statistics, filter for "Active deck only".
- Go to HS to see a new match of your friend in Spectator Mode (in this case Warlock vs Hunter)
- When the match is finished, the result is saved. See the images below.

### Log/Screenshots

![image](https://user-images.githubusercontent.com/29385381/28753128-a49d10a2-752f-11e7-91c5-7ee03758ada0.png)

![image](https://user-images.githubusercontent.com/29385381/28753132-b4f61a20-752f-11e7-97e1-9d2765516761.png)

**Comment by soeltjen** [comment] 2017-07-31 10:10
I wasn't able to reproduce this. When entering spectator mode my active deck is switched to No-Deck Mode.  Also trying to select an active deck while in spectator mode reverts back to No Deck Mode

**Comment by dor-levi** [comment] 2017-09-23 11:20
I don't know exactly how to reproduce this, but it happened to me more then once.
In the image below, the first mage loss was actually a spectated match.
This also messed up the arena rewards popup, which appeared after the druid loss, which was actually just the second arena loss, not the third.

![image](https://user-images.githubusercontent.com/11015255/30772725-5904d74a-a06a-11e7-9037-13ce88ec82e6.png)

**Comment by riQQ** [comment] 2017-09-23 13:23
We need a HDT log of a game where this happened: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues#hdt-log-files.

I couldn't reproduce this myself. This is probably dependent on specific settings and / or properties of the game played.

**Comment by dor-levi** [comment] 2017-09-23 15:16
Sure thing, here's the log file from that time, I validated the spectated match is there (searched "MrFunnyPants", the username of the friend I spectated)
[hdt_log_1506164976.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1326615/hdt_log_1506164976.txt)

**Comment by riQQ** [comment] 2017-10-26 21:59
These are the interesting lines, looks like the game was first assigned to the default Druid, then removed from the default Druid and then assigned to the Arena Deck.

```
11:08:58 PM|Info|GameEventHandler.HandleLoss >> --- Game was lost! ---
11:08:58 PM|Info|TurnTimer.Stop >> Stopping turn timer
11:08:58 PM|Info|GameEventHandler.HandleGameEnd >> Game ended...
11:08:58 PM|Info|GameEventHandler.HandleGameEnd >> Format: 
11:08:58 PM|Info|GameStats.GameEnd >> Current Game ended after 8 turns
11:08:58 PM|Info|GameEventHandler.HandleGameEnd >> Assigned current deck to default Druid deck.
11:08:58 PM|Info|GameEventHandler.LogIsComplete >> GOLD_REWARD_STATE not found
11:08:58 PM|Info|LogUploader.Upload >> Uploading -1052604653...
11:08:58 PM|Info|LogUploader.TryUpload >> Creating upload request...
11:08:59 PM|Info|LogUploader.TryUpload >> Upload Id: qFhBaFqqfg7Rf5gfWUEsGH
11:09:01 PM|Info|LogUploader.TryUpload >> Upload complete
11:09:01 PM|Info|LogUploader.Upload >> -1052604653 complete. Success=True
11:09:09 PM|Warning|GameEventHandler.HandleGameEnd >> HandleGameEnd was already called.
11:09:09 PM|Info|GameV2.CurrentMode >> HUB
11:09:09 PM|Info|GameEventHandler.HandleInMenu >> Game is now in menu.
11:09:09 PM|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
11:09:09 PM|Info|GameEventHandler.SaveAndUpdateStats >> Gamemode Spectator is not supposed to be saved. Removed game from default Druid.
11:09:11 PM|Warning|GameEventHandler.HandleGameEnd >> HandleGameEnd was already called.
11:09:44 PM|Info|GameV2.CurrentMode >> DRAFT
11:09:45 PM|Info|DeckManager.AutoImportArena >> Found new complete HERO_06 arena deck!
11:09:45 PM|Info|DeckManager.AutoImportArena >> ...but we already have that one. Discarding.
11:09:45 PM|Info|FullScreenFxHandler.Handle >> Now in queue (9/22/2017 11:09:45 PM)
11:09:45 PM|Info|FullScreenFxHandler.AutoSelectArenaDeck >> Switching to arena deck deck: Arena 20-09 12:12
11:09:45 PM|Info|MainWindow.SelectDeck >> Switched to deck: Arena 20-09 12:12 (v1.0)
11:09:45 PM|Info|DeckList.ActiveDeck >> Set active deck to: Arena 20-09 12:12 (Druid)
11:09:46 PM|Info|GameV2.Reset >> -------- Reset ---------
23:09:47|Info|LogWatcherManager.OnLogFileFound >> Power
23:09:47|Info|LogWatcherManager.OnLogFileFound >> Rachelle
23:09:47|Info|LogWatcherManager.OnLogFileFound >> LoadingScreen
11:09:47 PM|Info|GameEventHandler.HandleGameEnd >> Game ended...
11:09:47 PM|Info|GameEventHandler.HandleGameEnd >> Format: 
11:09:47 PM|Info|GameStats.GameEnd >> Current Game ended after 0 turns
11:09:47 PM|Info|GameEventHandler.HandleGameEnd >> Assigned current game to deck: Arena 20-09 12:12
```

**Comment by dor-levi** [comment] 2017-10-27 07:34
@riQQ is there anything else you need to help investigate the issue?

**Comment by riQQ** [comment] 2017-10-27 17:00
No, should be enough for now.

**Comment by riQQ** [comment] 2018-01-31 20:13
This can only happen, if the option `Discard game if deck does not match cards` is disabled.

**Closed** 2018-01-31 22:30 UTC
Labels: bug, can't reproduce, stats
