### ISSUE TITLE
Overlay disappearing

### ISSUE THREAD

**Issue by Stally18** [HearthSim/Hearthstone-Deck-Tracker#3783] opened 2018-09-02 16:01 UTC
I use two monitors in my system. Usually i open HS on main screen, and HDT on secondary.
I play Hearthstone in windowed mode, so i can switch to other things, like browser or Discord while playing.
Some time ago i run into problem with HDT overlay disappearing, after i switch on any other window with alt+tab or just clicking on second screen.
Then i have to restart HDT so overlay turns on again.
(even if overlay dies, HDT is still working, like, tracking my decks and wins\loses)
I tried to move HDT to main screen, but that didn't help.
Restarting HDT 5-6 times every game is a little bit uncomfortable, to say the least.

**Comment by riQQ** [comment] 2018-10-11 22:17
Probably the same as some people in #3143 and linked threads.

**Comment by Stally18** [comment] 2018-10-12 20:03
minimizing/maximizing gets no difference

looked over by the linked thread, will try some of the old suggested solutions

**Comment by Stally18** [comment] 2018-10-12 22:35
Okay, most useful solutions was to tick "hide if HS is in background" and to hotkey the overlay toggle
"Hiding" works as intended and hotkey too, but first solution is more comfortable cause with the hotkey you need to press ONE extra button :p

**Comment by riQQ** [comment] 2018-11-01 11:00
Duplicate of #3143

**Closed by riQQ** 2018-11-01 11:00 UTC
