### ISSUE TITLE
Inara Stormcrash not adding to the Damage Counter Properly

### ISSUE THREAD

**Issue by abrownhearth** [HearthSim/Hearthstone-Deck-Tracker#4314] opened 2021-07-01 14:46 UTC
### Expected Behavior
Inara Stormcrash's ability should add 4 to the damage counter (After a turn, she should add 4 for her ability and 4 for her attack, for 8 total)

### Actual Behavior
Inara Stormcrash's ability adds 2 to the damage counter

### Steps to reproduce behavior
Play Inara Stormcrash with the damage counter turned on in HDT

### Log/Screenshots
![inara](https://user-images.githubusercontent.com/46356239/124143885-b8ed6c00-da48-11eb-85e6-ac996bbec7c2.png)

**Comment by beheh** [comment] 2023-12-10 16:33
Duplicate of #4176

**Closed by beheh** 2023-12-10 16:33 UTC
