### ISSUE TITLE
flavor text does not appear for cards in hand

### ISSUE THREAD

**Issue by mikek12003** [HearthSim/Hearthstone-Deck-Tracker#3991] opened 2019-12-23 13:40 UTC
after new expansion I cannot see any flavor text for card in hand -works fine for cards on field

**Comment by mikek12003** [comment] 2019-12-23 13:41
Saw another one already posted this issue

**Comment by riQQ** [comment] 2019-12-23 16:19
Duplicate of #3991

**Closed by riQQ** 2019-12-23 16:19 UTC
Labels: duplicate
