### ISSUE TITLE
Hearthstone Deck Tracker crash on startup

### ISSUE THREAD

**Issue by SeaJayClark** [HearthSim/Hearthstone-Deck-Tracker#3513] opened 2017-12-27 17:16 UTC
Hi, my Hearthstone Deck Tracker keeps crashing upon starting the program. I have uninstalled/reinstalled many times. My graphics driver and .NET are up to date as of posting this. 
I receive no error message; Windows simply states: "Hearthstone Deck Tracker has stopped working" and prompts me to Close Program. I don't know what is causing this issue, but it happens 100% of the time.

I checked Windows log files, and three different errors show up each time I replicate this issue (2 Application Errors, and 1 .NET Runtime error). Below is the data. Please let me know if you need more data, (and I apologize if I have too MUCH data. This is my first post and I don't know exactly what I need to include.)

**Event data:**

**-Error**:  _.NET Runtime_; Event ID "**1026**"; Task Category "None":
Application: HearthstoneDeckTracker.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000096, exception address 5FF181D1

**-Error**:  _Application Error_; Event ID "**1000**"; Task Category "(100):
Faulting application name: HearthstoneDeckTracker.exe, version: 1.5.10.3385, time stamp: 0x5a36ff2b
Faulting module name: d3d9.dll, version: 10.0.16299.98, time stamp: 0xe2fbf0fc
Exception code: 0xc0000096
Fault offset: 0x000481d1
Faulting process id: 0x2f68
Faulting application start time: 0x01d37f319bfaa1d1
Faulting application path: C:\Users\CJ\AppData\Local\HearthstoneDeckTracker\app-1.5.10\HearthstoneDeckTracker.exe
Faulting module path: C:\WINDOWS\SYSTEM32\d3d9.dll
Report Id: 0c1ec951-0e73-4692-a2b1-a2ae040136cf
Faulting package full name: 
Faulting package-relative application ID: 

**-Error**: _Application Error_; Event ID "**1005**"; Task Category "(100):
Additional Data
Error value: 00000246
Disk type: 0

**Comment by riQQ** [comment] 2017-12-27 17:23
Please see #3494 and the issues linked in there.
Duplicate of #3494

**Closed by riQQ** 2017-12-27 17:23 UTC
